SMOKE_SCENARIOS=(
  one-to-one
  shared-media-search
  saved-messages
  default-dialog-filter
  dialog-filters
  basic-group
  channel
  channel-polls
  megagroup-slow-mode
  contacts-search
  langpack
  username-registration
  username-password-reset
  pollprobe
  admin-proxy-login
)
