SMOKE_SCENARIOS=(
  launch-getters
  reset-authorizations
  one-to-one
  photo-media
  shared-media-search
  saved-messages
  default-dialog-filter
  dialog-pins
  dialog-filters
  cloud-drafts
  manual-dialog-unread-mark
  basic-group
  channel
  mtproto-service-messages
  channel-polls
  megagroup-slow-mode
  contacts-search
  full-user-profile
  langpack
  username-registration
  username-password-reset
  pollprobe
  pollprobe-channels
  secret-chat-exchange
  provisioned-account-login
  admin-proxy-login
)
