// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authKeyByID = `-- name: AuthKeyByID :one
SELECT ak.id, ak.key_value, ak.user_id, ak.created_at, ak.last_seen_at, ak.pending_user_id,
       ak.pending_started_at,
       GREATEST(
           0::bigint,
           COALESCE(
               FLOOR(EXTRACT(EPOCH FROM (
                   ak.pending_started_at
                   + ($1::bigint * interval '1 microsecond')
                   - clock_timestamp()
               )) * 1000000)::bigint,
               0::bigint
           )
       )::bigint AS pending_remaining_micros,
       u.login_mode,
       (up.user_id IS NOT NULL) AS has_password
FROM auth_keys ak
LEFT JOIN users u ON u.id = ak.user_id
LEFT JOIN user_passwords up ON up.user_id = ak.user_id
WHERE ak.id = $2
`

type AuthKeyByIDParams struct {
	PendingLifetimeMicros int64
	ID                    int64
}

type AuthKeyByIDRow struct {
	ID                     int64
	KeyValue               []byte
	UserID                 *int64
	CreatedAt              pgtype.Timestamptz
	LastSeenAt             pgtype.Timestamptz
	PendingUserID          *int64
	PendingStartedAt       pgtype.Timestamptz
	PendingRemainingMicros int64
	LoginMode              *string
	HasPassword            interface{}
}

func (q *Queries) AuthKeyByID(ctx context.Context, arg AuthKeyByIDParams) (AuthKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, authKeyByID, arg.PendingLifetimeMicros, arg.ID)
	var i AuthKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.KeyValue,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.PendingUserID,
		&i.PendingStartedAt,
		&i.PendingRemainingMicros,
		&i.LoginMode,
		&i.HasPassword,
	)
	return i, err
}

const authKeysByUser = `-- name: AuthKeysByUser :many
SELECT id, key_value, user_id, created_at, last_seen_at, pending_user_id, pending_started_at FROM auth_keys WHERE user_id = $1
`

func (q *Queries) AuthKeysByUser(ctx context.Context, userID *int64) ([]AuthKey, error) {
	rows, err := q.db.Query(ctx, authKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthKey
	for rows.Next() {
		var i AuthKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyValue,
			&i.UserID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.PendingUserID,
			&i.PendingStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bindAuthKeyUser = `-- name: BindAuthKeyUser :execrows
UPDATE auth_keys SET user_id = $2, pending_user_id = NULL, pending_started_at = NULL WHERE id = $1
`

type BindAuthKeyUserParams struct {
	ID     int64
	UserID *int64
}

func (q *Queries) BindAuthKeyUser(ctx context.Context, arg BindAuthKeyUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindAuthKeyUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearExpiredPendingUser = `-- name: ClearExpiredPendingUser :execrows
UPDATE auth_keys
SET pending_user_id = NULL, pending_started_at = NULL
WHERE id = $1
  AND pending_user_id = $2
  AND pending_started_at IS NOT DISTINCT FROM $3::timestamptz
  AND (
      pending_started_at IS NULL
      OR pending_started_at + ($4::bigint * interval '1 microsecond') <= clock_timestamp()
  )
`

type ClearExpiredPendingUserParams struct {
	ID             int64
	UserID         *int64
	StartedAt      pgtype.Timestamptz
	LifetimeMicros int64
}

func (q *Queries) ClearExpiredPendingUser(ctx context.Context, arg ClearExpiredPendingUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearExpiredPendingUser,
		arg.ID,
		arg.UserID,
		arg.StartedAt,
		arg.LifetimeMicros,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAuthKey = `-- name: DeleteAuthKey :exec
DELETE FROM auth_keys WHERE id = $1
`

func (q *Queries) DeleteAuthKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthKey, id)
	return err
}

const lockUnboundAuthKey = `-- name: LockUnboundAuthKey :one
SELECT id FROM auth_keys
WHERE id = $1 AND user_id IS NULL
FOR UPDATE
`

// Locks the key admission will bind, rejecting keys already authorized. A
// pending password challenge is cleared by the same transaction when signup
// binds the still-unbound key.
func (q *Queries) LockUnboundAuthKey(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUnboundAuthKey, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const pendingLoginByID = `-- name: PendingLoginByID :one
SELECT pending_user_id, pending_started_at,
       COALESCE(
           pending_started_at + ($1::bigint * interval '1 microsecond') > clock_timestamp(),
           false
       ) AS active
FROM auth_keys
WHERE id = $2 AND pending_user_id IS NOT NULL
`

type PendingLoginByIDParams struct {
	LifetimeMicros int64
	ID             int64
}

type PendingLoginByIDRow struct {
	PendingUserID    *int64
	PendingStartedAt pgtype.Timestamptz
	Active           interface{}
}

func (q *Queries) PendingLoginByID(ctx context.Context, arg PendingLoginByIDParams) (PendingLoginByIDRow, error) {
	row := q.db.QueryRow(ctx, pendingLoginByID, arg.LifetimeMicros, arg.ID)
	var i PendingLoginByIDRow
	err := row.Scan(&i.PendingUserID, &i.PendingStartedAt, &i.Active)
	return i, err
}

const promotePendingUser = `-- name: PromotePendingUser :execrows
UPDATE auth_keys
SET user_id = $1, pending_user_id = NULL, pending_started_at = NULL
WHERE id = $2
  AND pending_user_id = $1
  AND pending_started_at = $3::timestamptz
  AND pending_started_at IS NOT NULL
  AND pending_started_at + ($4::bigint * interval '1 microsecond') > clock_timestamp()
`

type PromotePendingUserParams struct {
	UserID         *int64
	ID             int64
	StartedAt      pgtype.Timestamptz
	LifetimeMicros int64
}

func (q *Queries) PromotePendingUser(ctx context.Context, arg PromotePendingUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, promotePendingUser,
		arg.UserID,
		arg.ID,
		arg.StartedAt,
		arg.LifetimeMicros,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveAuthKey = `-- name: SaveAuthKey :exec
INSERT INTO auth_keys (id, key_value)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
  SET key_value = EXCLUDED.key_value,
      last_seen_at = now()
`

type SaveAuthKeyParams struct {
	ID       int64
	KeyValue []byte
}

func (q *Queries) SaveAuthKey(ctx context.Context, arg SaveAuthKeyParams) error {
	_, err := q.db.Exec(ctx, saveAuthKey, arg.ID, arg.KeyValue)
	return err
}

const setPendingUser = `-- name: SetPendingUser :one
UPDATE auth_keys
SET user_id = NULL, pending_user_id = $1, pending_started_at = clock_timestamp()
WHERE id = $2
RETURNING pending_started_at,
       GREATEST(
           0::bigint,
           FLOOR(EXTRACT(EPOCH FROM (
               pending_started_at
               + ($3::bigint * interval '1 microsecond')
               - clock_timestamp()
           )) * 1000000)::bigint
       )::bigint AS pending_remaining_micros
`

type SetPendingUserParams struct {
	UserID         *int64
	ID             int64
	LifetimeMicros int64
}

type SetPendingUserRow struct {
	PendingStartedAt       pgtype.Timestamptz
	PendingRemainingMicros int64
}

func (q *Queries) SetPendingUser(ctx context.Context, arg SetPendingUserParams) (SetPendingUserRow, error) {
	row := q.db.QueryRow(ctx, setPendingUser, arg.UserID, arg.ID, arg.LifetimeMicros)
	var i SetPendingUserRow
	err := row.Scan(&i.PendingStartedAt, &i.PendingRemainingMicros)
	return i, err
}

const touchAuthKey = `-- name: TouchAuthKey :exec
UPDATE auth_keys SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchAuthKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAuthKey, id)
	return err
}
