// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channelmsgs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpChannelPtsOnly = `-- name: BumpChannelPtsOnly :one
UPDATE channel_state SET pts = pts + 1, date = now()
WHERE channel_id = $1
RETURNING pts
`

// BumpChannelPtsOnly appends a durable edit/delete event without allocating a
// new message id.
func (q *Queries) BumpChannelPtsOnly(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, bumpChannelPtsOnly, channelID)
	var pts int64
	err := row.Scan(&pts)
	return pts, err
}

const bumpChannelState = `-- name: BumpChannelState :one
UPDATE channel_state
SET pts = pts + 1, next_local_id = next_local_id + 1, date = now()
WHERE channel_id = $1
RETURNING pts, (next_local_id - 1)::bigint AS local_id
`

type BumpChannelStateRow struct {
	Pts     int64
	LocalID int64
}

// BumpChannelState allocates the next local_id and advances pts in one step. It
// returns the new pts and the local_id just consumed (pre-increment value).
func (q *Queries) BumpChannelState(ctx context.Context, channelID int64) (BumpChannelStateRow, error) {
	row := q.db.QueryRow(ctx, bumpChannelState, channelID)
	var i BumpChannelStateRow
	err := row.Scan(&i.Pts, &i.LocalID)
	return i, err
}

const channelEventsWindow = `-- name: ChannelEventsWindow :many
SELECT channel_id, pts, type, local_id FROM channel_events
WHERE channel_id = $1 AND pts > $2 AND pts <= $3
ORDER BY pts
LIMIT $4::int
`

type ChannelEventsWindowParams struct {
	ChannelID int64
	FromPts   int64
	ToPts     int64
	Lim       int32
}

// ChannelEventsWindow returns events in (from_pts, to_pts] ordered, capped by
// lim. The upper bound pins the read to a pts snapshot so the difference never
// advertises a pts past an event it omitted.
func (q *Queries) ChannelEventsWindow(ctx context.Context, arg ChannelEventsWindowParams) ([]ChannelEvent, error) {
	rows, err := q.db.Query(ctx, channelEventsWindow,
		arg.ChannelID,
		arg.FromPts,
		arg.ToPts,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelEvent
	for rows.Next() {
		var i ChannelEvent
		if err := rows.Scan(
			&i.ChannelID,
			&i.Pts,
			&i.Type,
			&i.LocalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelHistoryPage = `-- name: ChannelHistoryPage :many
SELECT channel_id, local_id, from_id, date, message, edit_date, deleted, random_id, file_id, reply_to_msg_id, action_type
FROM channel_messages
WHERE channel_id = $1 AND deleted = false
  AND ($2::bigint = 0 OR local_id < $2::bigint)
ORDER BY local_id DESC
LIMIT $3::int
`

type ChannelHistoryPageParams struct {
	ChannelID int64
	OffsetID  int64
	Lim       int32
}

type ChannelHistoryPageRow struct {
	ChannelID    int64
	LocalID      int64
	FromID       int64
	Date         pgtype.Timestamptz
	Message      string
	EditDate     pgtype.Timestamptz
	Deleted      bool
	RandomID     int64
	FileID       *int64
	ReplyToMsgID *int32
	ActionType   int16
}

func (q *Queries) ChannelHistoryPage(ctx context.Context, arg ChannelHistoryPageParams) ([]ChannelHistoryPageRow, error) {
	rows, err := q.db.Query(ctx, channelHistoryPage, arg.ChannelID, arg.OffsetID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelHistoryPageRow
	for rows.Next() {
		var i ChannelHistoryPageRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.LocalID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.ActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelMessageByLocal = `-- name: ChannelMessageByLocal :one
SELECT channel_id, local_id, from_id, date, message, edit_date, deleted, random_id, file_id, reply_to_msg_id, action_type
FROM channel_messages WHERE channel_id = $1 AND local_id = $2
`

type ChannelMessageByLocalParams struct {
	ChannelID int64
	LocalID   int64
}

type ChannelMessageByLocalRow struct {
	ChannelID    int64
	LocalID      int64
	FromID       int64
	Date         pgtype.Timestamptz
	Message      string
	EditDate     pgtype.Timestamptz
	Deleted      bool
	RandomID     int64
	FileID       *int64
	ReplyToMsgID *int32
	ActionType   int16
}

func (q *Queries) ChannelMessageByLocal(ctx context.Context, arg ChannelMessageByLocalParams) (ChannelMessageByLocalRow, error) {
	row := q.db.QueryRow(ctx, channelMessageByLocal, arg.ChannelID, arg.LocalID)
	var i ChannelMessageByLocalRow
	err := row.Scan(
		&i.ChannelID,
		&i.LocalID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.FileID,
		&i.ReplyToMsgID,
		&i.ActionType,
	)
	return i, err
}

const channelMessageByRandomID = `-- name: ChannelMessageByRandomID :one
SELECT channel_id, local_id, from_id, date, message, edit_date, deleted, random_id, file_id, reply_to_msg_id, action_type
FROM channel_messages WHERE channel_id = $1 AND random_id = $2 AND random_id <> 0
`

type ChannelMessageByRandomIDParams struct {
	ChannelID int64
	RandomID  int64
}

type ChannelMessageByRandomIDRow struct {
	ChannelID    int64
	LocalID      int64
	FromID       int64
	Date         pgtype.Timestamptz
	Message      string
	EditDate     pgtype.Timestamptz
	Deleted      bool
	RandomID     int64
	FileID       *int64
	ReplyToMsgID *int32
	ActionType   int16
}

func (q *Queries) ChannelMessageByRandomID(ctx context.Context, arg ChannelMessageByRandomIDParams) (ChannelMessageByRandomIDRow, error) {
	row := q.db.QueryRow(ctx, channelMessageByRandomID, arg.ChannelID, arg.RandomID)
	var i ChannelMessageByRandomIDRow
	err := row.Scan(
		&i.ChannelID,
		&i.LocalID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.FileID,
		&i.ReplyToMsgID,
		&i.ActionType,
	)
	return i, err
}

const channelMessagesByLocalIDs = `-- name: ChannelMessagesByLocalIDs :many
SELECT channel_id, local_id, from_id, date, message, edit_date, deleted, random_id, file_id, reply_to_msg_id, action_type
FROM channel_messages
WHERE channel_id = $1 AND local_id = ANY($2::bigint[])
`

type ChannelMessagesByLocalIDsParams struct {
	ChannelID int64
	LocalIds  []int64
}

type ChannelMessagesByLocalIDsRow struct {
	ChannelID    int64
	LocalID      int64
	FromID       int64
	Date         pgtype.Timestamptz
	Message      string
	EditDate     pgtype.Timestamptz
	Deleted      bool
	RandomID     int64
	FileID       *int64
	ReplyToMsgID *int32
	ActionType   int16
}

func (q *Queries) ChannelMessagesByLocalIDs(ctx context.Context, arg ChannelMessagesByLocalIDsParams) ([]ChannelMessagesByLocalIDsRow, error) {
	rows, err := q.db.Query(ctx, channelMessagesByLocalIDs, arg.ChannelID, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMessagesByLocalIDsRow
	for rows.Next() {
		var i ChannelMessagesByLocalIDsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.LocalID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.ActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelPostExistsActive = `-- name: ChannelPostExistsActive :one
SELECT local_id FROM channel_messages
WHERE channel_id = $1 AND local_id = $2 AND deleted = false AND action_type = 0
`

type ChannelPostExistsActiveParams struct {
	ChannelID int64
	LocalID   int64
}

// ChannelPostExistsActive returns the local_id of an existing, non-deleted post
// in channelID. Used to validate reply_to_msg_id inside the post transaction.
//
// LOCK INVARIANT: callers must hold the channel_state row lock (LockChannelState)
// before calling this. A future channel-post delete path must acquire the same
// lock before writing deleted = true, or the snapshot read here can race it and
// accept a reply reference to a post that is deleted by the time we commit.
func (q *Queries) ChannelPostExistsActive(ctx context.Context, arg ChannelPostExistsActiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, channelPostExistsActive, arg.ChannelID, arg.LocalID)
	var local_id int64
	err := row.Scan(&local_id)
	return local_id, err
}

const countFilteredChannelPosts = `-- name: CountFilteredChannelPosts :one
SELECT count(*)::bigint
FROM channel_messages post
WHERE post.channel_id = $1::bigint
  AND post.deleted = false
  AND post.action_type = 0
  AND EXISTS (
      SELECT 1 FROM channel_participants cp
      WHERE cp.channel_id = post.channel_id
        AND cp.user_id = $2::bigint
        AND (cp.banned_until IS NULL OR cp.banned_until <= now())
  )
  AND CASE $3::smallint
      WHEN 1 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
      )
      WHEN 2 THEN false
      WHEN 3 THEN post.message ~* '(^|[^[:alnum:]_@])(([[:alpha:]][[:alnum:]+.-]*://|www[.])[^[:space:]]+|[[:alnum:]-]+[.][[:alpha:]]{2,}(:[0-9]{1,5})?(/[[:graph:]]*)?)'
      WHEN 4 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
            AND f.subtype_rights @> ARRAY['send_videos']::text[]
      )
      WHEN 5 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
            AND f.subtype_rights @> ARRAY['send_gifs']::text[]
      )
      WHEN 6 THEN false
      WHEN 7 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
            AND f.subtype_rights && ARRAY['send_roundvideos', 'send_voices']::text[]
      )
      WHEN 8 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
            AND f.subtype_rights @> ARRAY['send_audios']::text[]
      )
      ELSE false
  END
  AND ($4::text = '' OR post.message_tsv @@ plainto_tsquery('simple', $4))
`

type CountFilteredChannelPostsParams struct {
	ChannelID int64
	OwnerID   int64
	Filter    int16
	Query     string
}

// Filtered shared-media channel searches keep admission in both the count and
// page query. Channel posts are shared rows, so membership is the authorized
// scope; an access hash alone never widens it. subtype_rights is the sender's
// declared classification, not an authorization signal. Unknown (NULL),
// generic and unstored files never match a subtype filter.
func (q *Queries) CountFilteredChannelPosts(ctx context.Context, arg CountFilteredChannelPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredChannelPosts,
		arg.ChannelID,
		arg.OwnerID,
		arg.Filter,
		arg.Query,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureChannelState = `-- name: EnsureChannelState :exec
INSERT INTO channel_state (channel_id) VALUES ($1) ON CONFLICT (channel_id) DO NOTHING
`

func (q *Queries) EnsureChannelState(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, ensureChannelState, channelID)
	return err
}

const getChannelState = `-- name: GetChannelState :one
SELECT channel_id, pts, next_local_id, date FROM channel_state WHERE channel_id = $1
`

func (q *Queries) GetChannelState(ctx context.Context, channelID int64) (ChannelState, error) {
	row := q.db.QueryRow(ctx, getChannelState, channelID)
	var i ChannelState
	err := row.Scan(
		&i.ChannelID,
		&i.Pts,
		&i.NextLocalID,
		&i.Date,
	)
	return i, err
}

const insertChannelCreateMessage = `-- name: InsertChannelCreateMessage :exec
INSERT INTO channel_messages (channel_id, local_id, from_id, message, action_type)
VALUES ($1, $2, $3, $4, 1)
`

type InsertChannelCreateMessageParams struct {
	ChannelID int64
	LocalID   int64
	FromID    int64
	Message   string
}

func (q *Queries) InsertChannelCreateMessage(ctx context.Context, arg InsertChannelCreateMessageParams) error {
	_, err := q.db.Exec(ctx, insertChannelCreateMessage,
		arg.ChannelID,
		arg.LocalID,
		arg.FromID,
		arg.Message,
	)
	return err
}

const insertChannelEvent = `-- name: InsertChannelEvent :exec
INSERT INTO channel_events (channel_id, pts, type, local_id) VALUES ($1, $2, $3, $4)
`

type InsertChannelEventParams struct {
	ChannelID int64
	Pts       int64
	Type      int16
	LocalID   int64
}

func (q *Queries) InsertChannelEvent(ctx context.Context, arg InsertChannelEventParams) error {
	_, err := q.db.Exec(ctx, insertChannelEvent,
		arg.ChannelID,
		arg.Pts,
		arg.Type,
		arg.LocalID,
	)
	return err
}

const insertChannelMessage = `-- name: InsertChannelMessage :exec
INSERT INTO channel_messages (channel_id, local_id, from_id, message, random_id, file_id, reply_to_msg_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertChannelMessageParams struct {
	ChannelID    int64
	LocalID      int64
	FromID       int64
	Message      string
	RandomID     int64
	FileID       *int64
	ReplyToMsgID *int32
}

func (q *Queries) InsertChannelMessage(ctx context.Context, arg InsertChannelMessageParams) error {
	_, err := q.db.Exec(ctx, insertChannelMessage,
		arg.ChannelID,
		arg.LocalID,
		arg.FromID,
		arg.Message,
		arg.RandomID,
		arg.FileID,
		arg.ReplyToMsgID,
	)
	return err
}

const lockChannelState = `-- name: LockChannelState :one
SELECT channel_id, pts, next_local_id, date FROM channel_state WHERE channel_id = $1 FOR UPDATE
`

// LockChannelState takes the channel_state row lock ahead of the dedup read, so
// two concurrent posts carrying the same random_id cannot both miss it. It is
// the same row the bump below locks, taken one statement earlier.
func (q *Queries) LockChannelState(ctx context.Context, channelID int64) (ChannelState, error) {
	row := q.db.QueryRow(ctx, lockChannelState, channelID)
	var i ChannelState
	err := row.Scan(
		&i.ChannelID,
		&i.Pts,
		&i.NextLocalID,
		&i.Date,
	)
	return i, err
}

const newChannelPostPts = `-- name: NewChannelPostPts :one
SELECT pts FROM channel_events
WHERE channel_id = $1 AND local_id = $2 AND type = 1
`

type NewChannelPostPtsParams struct {
	ChannelID int64
	LocalID   int64
}

// NewChannelPostPts is NewMessagePts for a channel's log, and carries the same
// contract: one row per post, type = 1 spelled as a literal for the partial
// index.
func (q *Queries) NewChannelPostPts(ctx context.Context, arg NewChannelPostPtsParams) (int64, error) {
	row := q.db.QueryRow(ctx, newChannelPostPts, arg.ChannelID, arg.LocalID)
	var pts int64
	err := row.Scan(&pts)
	return pts, err
}

const searchChannelPostsPage = `-- name: SearchChannelPostsPage :many
SELECT channel_id, local_id, from_id, date, message, edit_date, deleted, random_id, file_id, reply_to_msg_id, action_type
FROM channel_messages
WHERE channel_id = $1 AND deleted = false
  AND action_type = 0
  AND message_tsv @@ plainto_tsquery('simple', $2)
  AND ($3::bigint = 0 OR local_id < $3::bigint)
ORDER BY local_id DESC
LIMIT $4::int
`

type SearchChannelPostsPageParams struct {
	ChannelID int64
	Query     string
	OffsetID  int64
	Lim       int32
}

type SearchChannelPostsPageRow struct {
	ChannelID    int64
	LocalID      int64
	FromID       int64
	Date         pgtype.Timestamptz
	Message      string
	EditDate     pgtype.Timestamptz
	Deleted      bool
	RandomID     int64
	FileID       *int64
	ReplyToMsgID *int32
	ActionType   int16
}

// SearchChannelPostsPage is ChannelHistoryPage narrowed by a full-text match.
// It carries no caller predicate: a channel keeps one shared row per post
// rather than one copy per member, so there is no owner column to filter on and
// membership is the caller's whole gate, checked before this runs.
// message_tsv is index-backed (GIN), so the match is not a sequential scan.
func (q *Queries) SearchChannelPostsPage(ctx context.Context, arg SearchChannelPostsPageParams) ([]SearchChannelPostsPageRow, error) {
	rows, err := q.db.Query(ctx, searchChannelPostsPage,
		arg.ChannelID,
		arg.Query,
		arg.OffsetID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChannelPostsPageRow
	for rows.Next() {
		var i SearchChannelPostsPageRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.LocalID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.ActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFilteredChannelPostsPage = `-- name: SearchFilteredChannelPostsPage :many
SELECT post.channel_id, post.local_id, post.from_id, post.date, post.message,
       post.edit_date, post.deleted, post.random_id, post.file_id, post.reply_to_msg_id, post.action_type
FROM channel_messages post
WHERE post.channel_id = $1::bigint
  AND post.deleted = false
  AND post.action_type = 0
  AND EXISTS (
      SELECT 1 FROM channel_participants cp
      WHERE cp.channel_id = post.channel_id
        AND cp.user_id = $2::bigint
        AND (cp.banned_until IS NULL OR cp.banned_until <= now())
  )
  AND CASE $3::smallint
      WHEN 1 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
      )
      WHEN 2 THEN false
      WHEN 3 THEN post.message ~* '(^|[^[:alnum:]_@])(([[:alpha:]][[:alnum:]+.-]*://|www[.])[^[:space:]]+|[[:alnum:]-]+[.][[:alpha:]]{2,}(:[0-9]{1,5})?(/[[:graph:]]*)?)'
      WHEN 4 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
            AND f.subtype_rights @> ARRAY['send_videos']::text[]
      )
      WHEN 5 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
            AND f.subtype_rights @> ARRAY['send_gifs']::text[]
      )
      WHEN 6 THEN false
      WHEN 7 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
            AND f.subtype_rights && ARRAY['send_roundvideos', 'send_voices']::text[]
      )
      WHEN 8 THEN post.file_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = post.file_id AND f.stored = true
            AND f.subtype_rights @> ARRAY['send_audios']::text[]
      )
      ELSE false
  END
  AND ($4::text = '' OR post.message_tsv @@ plainto_tsquery('simple', $4))
  AND ($5::bigint = 0 OR post.local_id < $5::bigint)
ORDER BY post.local_id DESC
LIMIT $6::int
`

type SearchFilteredChannelPostsPageParams struct {
	ChannelID int64
	OwnerID   int64
	Filter    int16
	Query     string
	OffsetID  int64
	Lim       int32
}

type SearchFilteredChannelPostsPageRow struct {
	ChannelID    int64
	LocalID      int64
	FromID       int64
	Date         pgtype.Timestamptz
	Message      string
	EditDate     pgtype.Timestamptz
	Deleted      bool
	RandomID     int64
	FileID       *int64
	ReplyToMsgID *int32
	ActionType   int16
}

func (q *Queries) SearchFilteredChannelPostsPage(ctx context.Context, arg SearchFilteredChannelPostsPageParams) ([]SearchFilteredChannelPostsPageRow, error) {
	rows, err := q.db.Query(ctx, searchFilteredChannelPostsPage,
		arg.ChannelID,
		arg.OwnerID,
		arg.Filter,
		arg.Query,
		arg.OffsetID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFilteredChannelPostsPageRow
	for rows.Next() {
		var i SearchFilteredChannelPostsPageRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.LocalID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.ActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPinnedChannelPostForMember = `-- name: SearchPinnedChannelPostForMember :many
SELECT post.channel_id, post.local_id, post.from_id, post.date, post.message,
       post.edit_date, post.deleted, post.random_id, post.file_id, post.reply_to_msg_id, post.action_type
FROM channels c
JOIN channel_participants participant
  ON participant.channel_id = c.id
 AND participant.user_id = $1::bigint
 AND (participant.banned_until IS NULL OR participant.banned_until <= now())
JOIN channel_messages post
  ON post.channel_id = c.id
 AND post.local_id = c.pinned_message_id
 AND post.deleted = false
 AND post.action_type = 0
WHERE c.id = $2::bigint
  AND c.pinned_message_id IS NOT NULL
  AND ($3::text = '' OR post.message_tsv @@ plainto_tsquery('simple', $3))
  AND ($4::bigint = 0 OR post.local_id < $4::bigint)
ORDER BY post.local_id DESC
LIMIT $5::int
`

type SearchPinnedChannelPostForMemberParams struct {
	OwnerID   int64
	ChannelID int64
	Query     string
	OffsetID  int64
	Lim       int32
}

type SearchPinnedChannelPostForMemberRow struct {
	ChannelID    int64
	LocalID      int64
	FromID       int64
	Date         pgtype.Timestamptz
	Message      string
	EditDate     pgtype.Timestamptz
	Deleted      bool
	RandomID     int64
	FileID       *int64
	ReplyToMsgID *int32
	ActionType   int16
}

// SearchPinnedChannelPostForMember returns the active pinned post only while
// the viewer still has an unbanned participant row for the channel. Posts are
// shared, so unlike chat pins the channel local_id is already the wire id.
func (q *Queries) SearchPinnedChannelPostForMember(ctx context.Context, arg SearchPinnedChannelPostForMemberParams) ([]SearchPinnedChannelPostForMemberRow, error) {
	rows, err := q.db.Query(ctx, searchPinnedChannelPostForMember,
		arg.OwnerID,
		arg.ChannelID,
		arg.Query,
		arg.OffsetID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPinnedChannelPostForMemberRow
	for rows.Next() {
		var i SearchPinnedChannelPostForMemberRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.LocalID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.ActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelMessageEditDate = `-- name: SetChannelMessageEditDate :execrows
UPDATE channel_messages SET edit_date = now()
WHERE channel_id = $1 AND local_id = $2 AND deleted = false
`

type SetChannelMessageEditDateParams struct {
	ChannelID int64
	LocalID   int64
}

func (q *Queries) SetChannelMessageEditDate(ctx context.Context, arg SetChannelMessageEditDateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelMessageEditDate, arg.ChannelID, arg.LocalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
