// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminedPublicChannels = `-- name: AdminedPublicChannels :many
SELECT c.id, c.title, c.about, c.creator_id, c.megagroup, c.version, c.date,
       c.pinned_message_id, un.handle, p.role
FROM channel_participants p
JOIN channels c ON c.id = p.channel_id
JOIN usernames un ON un.owner_type = 'channel' AND un.owner_id = c.id
WHERE p.user_id = $1
  AND p.role >= 1
  AND (p.banned_until IS NULL OR p.banned_until <= now())
ORDER BY c.id
`

type AdminedPublicChannelsRow struct {
	ID              int64
	Title           string
	About           string
	CreatorID       int64
	Megagroup       bool
	Version         int32
	Date            pgtype.Timestamptz
	PinnedMessageID *int32
	Handle          string
	Role            int16
}

// AdminedPublicChannels is scoped to the caller's own current admin rows. The
// usernames row is the authority for publicness and for the handle we return;
// channels.username is only a denormalized copy.
func (q *Queries) AdminedPublicChannels(ctx context.Context, userID int64) ([]AdminedPublicChannelsRow, error) {
	rows, err := q.db.Query(ctx, adminedPublicChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminedPublicChannelsRow
	for rows.Next() {
		var i AdminedPublicChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.About,
			&i.CreatorID,
			&i.Megagroup,
			&i.Version,
			&i.Date,
			&i.PinnedMessageID,
			&i.Handle,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advanceChannelReadState = `-- name: AdvanceChannelReadState :exec
INSERT INTO channel_read_state (channel_id, user_id, read_max_id)
VALUES ($1::bigint, $2::bigint,
        GREATEST($3::bigint, 0))
ON CONFLICT (channel_id, user_id) DO UPDATE
SET read_max_id = EXCLUDED.read_max_id
WHERE channel_read_state.read_max_id < EXCLUDED.read_max_id
`

type AdvanceChannelReadStateParams struct {
	ChannelID int64
	UserID    int64
	ReadMaxID int64
}

// AdvanceChannelReadState changes only a strictly higher marker. Lower and
// repeated positions are no-ops, and the store clamps max_id under the same
// channel_state lock used by post allocation.
func (q *Queries) AdvanceChannelReadState(ctx context.Context, arg AdvanceChannelReadStateParams) error {
	_, err := q.db.Exec(ctx, advanceChannelReadState, arg.ChannelID, arg.UserID, arg.ReadMaxID)
	return err
}

const channelActiveInviteByChannel = `-- name: ChannelActiveInviteByChannel :one
SELECT hash, channel_id, creator_id, date, revoked_at FROM channel_invites
WHERE channel_id = $1 AND revoked_at IS NULL
ORDER BY date DESC, hash DESC
LIMIT 1
`

// ChannelActiveInviteByChannel returns one existing active invite for a full
// info response. It is read-only; getFullChannel never creates or rotates one.
func (q *Queries) ChannelActiveInviteByChannel(ctx context.Context, channelID int64) (ChannelInvite, error) {
	row := q.db.QueryRow(ctx, channelActiveInviteByChannel, channelID)
	var i ChannelInvite
	err := row.Scan(
		&i.Hash,
		&i.ChannelID,
		&i.CreatorID,
		&i.Date,
		&i.RevokedAt,
	)
	return i, err
}

const channelByID = `-- name: ChannelByID :one
SELECT id, title, about, creator_id, megagroup, version, date, pinned_message_id, username, title_tsv, publicly_discoverable, default_banned_rights, slowmode_seconds FROM channels WHERE id = $1
`

func (q *Queries) ChannelByID(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, channelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.Username,
		&i.TitleTsv,
		&i.PubliclyDiscoverable,
		&i.DefaultBannedRights,
		&i.SlowmodeSeconds,
	)
	return i, err
}

const channelDeliverySnapshot = `-- name: ChannelDeliverySnapshot :many
SELECT participant.channel_id, participant.user_id, participant.role, participant.banned_until, participant.join_pts, participant.date, participant.last_post_at, state.pts
FROM channel_participants AS participant
JOIN channel_state AS state ON state.channel_id = participant.channel_id
WHERE participant.channel_id = $1
ORDER BY participant.user_id
`

type ChannelDeliverySnapshotRow struct {
	ChannelID   int64
	UserID      int64
	Role        int16
	BannedUntil pgtype.Timestamptz
	JoinPts     int64
	Date        pgtype.Timestamptz
	LastPostAt  pgtype.Timestamptz
	Pts         int64
}

// ChannelDeliverySnapshot binds the member authorization rows and the event
// ceiling to one statement snapshot. Live delivery must not authorize from an
// older member read and then include events committed after a later state read.
func (q *Queries) ChannelDeliverySnapshot(ctx context.Context, channelID int64) ([]ChannelDeliverySnapshotRow, error) {
	rows, err := q.db.Query(ctx, channelDeliverySnapshot, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelDeliverySnapshotRow
	for rows.Next() {
		var i ChannelDeliverySnapshotRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Role,
			&i.BannedUntil,
			&i.JoinPts,
			&i.Date,
			&i.LastPostAt,
			&i.Pts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelDialogsForUser = `-- name: ChannelDialogsForUser :many
SELECT
    c.id AS channel_id,
    c.title,
    c.about,
    c.creator_id,
    c.megagroup,
    c.version,
    c.username,
    c.default_banned_rights,
    c.date AS channel_date,
    p.role AS member_role,
    p.banned_until AS member_banned_until,
    p.join_pts AS member_join_pts,
    COALESCE(read_state.read_max_id, 0)::bigint AS read_inbox_max_id,
    unread.unread_count,
    unread.entitled AS summary_entitled,
    unread.status_exists AS summary_status_exists,
    unread.summary_version,
    unread.summary_ready,
    unread.total_live AS summary_total_live,
    unread.author_live AS summary_author_live,
    cs.pts,
    cs.next_local_id,
    cs.date AS state_date,
    COALESCE(top.local_id, 0)  AS top_local_id,
    COALESCE(top.from_id, 0)   AS top_from_id,
    top.date                   AS top_date,
    COALESCE(top.message, '')  AS top_message,
    top.edit_date              AS top_edit_date,
    COALESCE(top.deleted, false) AS top_deleted,
    COALESCE(top.random_id, 0) AS top_random_id,
    top.file_id                AS top_file_id,
    top.reply_to_msg_id        AS top_reply_to_msg_id,
    COALESCE(top.action_type, 0)::smallint AS top_action_type,
    EXISTS (
        SELECT 1 FROM user_dialog_pins pin
        WHERE pin.owner_id = p.user_id AND pin.peer_type = 3
          AND pin.peer_id = c.id AND pin.position IS NOT NULL
    ) AS pinned
FROM channels c
JOIN channel_participants p ON p.channel_id = c.id
JOIN channel_state cs ON cs.channel_id = c.id
LEFT JOIN channel_read_state read_state
  ON read_state.channel_id = c.id AND read_state.user_id = p.user_id
CROSS JOIN LATERAL (
    SELECT LEAST(GREATEST(summary.total_live - summary.author_live, 0), 1000)::int AS unread_count,
           summary.entitled::boolean AS entitled,
           summary.status_exists::boolean AS status_exists,
           summary.summary_version::smallint AS summary_version,
           summary.summary_ready::boolean AS summary_ready,
           summary.total_live::bigint AS total_live,
           summary.author_live::bigint AS author_live
    FROM channel_post_unread_suffix_counts(
        c.id,
        p.user_id,
        COALESCE(read_state.read_max_id, 0)
    ) AS summary(entitled, status_exists, summary_version, summary_ready, total_live, author_live)
) AS unread
LEFT JOIN LATERAL (
    SELECT cm.channel_id, cm.local_id, cm.from_id, cm.date, cm.message, cm.edit_date, cm.deleted, cm.random_id, cm.file_id, cm.reply_to_msg_id, cm.action_type
    FROM channel_messages cm
    WHERE cm.channel_id = c.id AND cm.deleted = false
    ORDER BY cm.local_id DESC
    LIMIT 1
) top ON true
WHERE p.user_id = $1
  AND (p.banned_until IS NULL OR p.banned_until <= now())
  AND (NOT $2::boolean OR NOT EXISTS (
        SELECT 1 FROM user_dialog_pins pin
        WHERE pin.owner_id = p.user_id AND pin.peer_type = 3
          AND pin.peer_id = c.id AND pin.position IS NOT NULL
  ))
ORDER BY c.id
`

type ChannelDialogsForUserParams struct {
	UserID        int64
	ExcludePinned bool
}

type ChannelDialogsForUserRow struct {
	ChannelID           int64
	Title               string
	About               string
	CreatorID           int64
	Megagroup           bool
	Version             int32
	Username            *string
	DefaultBannedRights []string
	ChannelDate         pgtype.Timestamptz
	MemberRole          int16
	MemberBannedUntil   pgtype.Timestamptz
	MemberJoinPts       int64
	ReadInboxMaxID      int64
	UnreadCount         int32
	SummaryEntitled     bool
	SummaryStatusExists bool
	SummaryVersion      int16
	SummaryReady        bool
	SummaryTotalLive    int64
	SummaryAuthorLive   int64
	Pts                 int64
	NextLocalID         int64
	StateDate           pgtype.Timestamptz
	TopLocalID          int64
	TopFromID           int64
	TopDate             pgtype.Timestamptz
	TopMessage          string
	TopEditDate         pgtype.Timestamptz
	TopDeleted          bool
	TopRandomID         int64
	TopFileID           *int64
	TopReplyToMsgID     *int32
	TopActionType       int16
	Pinned              bool
}

// ChannelDialogsForUser returns every unbanned channel the user belongs to,
// including empty channels, alongside the member row, channel pts, and newest
// non-deleted post (the dialog's top message). Empty channels have top_local_id
// 0 and still produce a dialog. LEFT JOIN ensures they count toward the bounded
// 500-channel account cap.
// COALESCE guards against NULL from the lateral join; local_id >= 1 so 0 is
// a safe sentinel for "no row".
func (q *Queries) ChannelDialogsForUser(ctx context.Context, arg ChannelDialogsForUserParams) ([]ChannelDialogsForUserRow, error) {
	rows, err := q.db.Query(ctx, channelDialogsForUser, arg.UserID, arg.ExcludePinned)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelDialogsForUserRow
	for rows.Next() {
		var i ChannelDialogsForUserRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Title,
			&i.About,
			&i.CreatorID,
			&i.Megagroup,
			&i.Version,
			&i.Username,
			&i.DefaultBannedRights,
			&i.ChannelDate,
			&i.MemberRole,
			&i.MemberBannedUntil,
			&i.MemberJoinPts,
			&i.ReadInboxMaxID,
			&i.UnreadCount,
			&i.SummaryEntitled,
			&i.SummaryStatusExists,
			&i.SummaryVersion,
			&i.SummaryReady,
			&i.SummaryTotalLive,
			&i.SummaryAuthorLive,
			&i.Pts,
			&i.NextLocalID,
			&i.StateDate,
			&i.TopLocalID,
			&i.TopFromID,
			&i.TopDate,
			&i.TopMessage,
			&i.TopEditDate,
			&i.TopDeleted,
			&i.TopRandomID,
			&i.TopFileID,
			&i.TopReplyToMsgID,
			&i.TopActionType,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelFullInfoStats = `-- name: ChannelFullInfoStats :one
SELECT
    count(*)::bigint AS participants_count,
    count(*) FILTER (WHERE role >= 1 AND (banned_until IS NULL OR banned_until <= now()))::bigint AS admins_count,
    count(*) FILTER (WHERE banned_until > now())::bigint AS banned_count
FROM channel_participants
WHERE channel_id = $1
`

type ChannelFullInfoStatsRow struct {
	ParticipantsCount int64
	AdminsCount       int64
	BannedCount       int64
}

// ChannelFullInfoStats is read in the same repeatable-read transaction as the
// channel and viewer membership. The public participant count keeps the
// existing row-count meaning used by the public channel renderer; administrative
// counts include only current admins and bans.
func (q *Queries) ChannelFullInfoStats(ctx context.Context, channelID int64) (ChannelFullInfoStatsRow, error) {
	row := q.db.QueryRow(ctx, channelFullInfoStats, channelID)
	var i ChannelFullInfoStatsRow
	err := row.Scan(&i.ParticipantsCount, &i.AdminsCount, &i.BannedCount)
	return i, err
}

const channelInviteByHash = `-- name: ChannelInviteByHash :one
SELECT hash, channel_id, creator_id, date, revoked_at FROM channel_invites WHERE hash = $1 AND revoked_at IS NULL
`

// ChannelInviteByHash is the ONLY way into a channel. It is keyed on the hash
// alone and takes no channel id, so a channel id is not an admission input. An
// unknown hash and an unusable one are one rejection upstream — see
// JoinChannelByInvite. Revoked invites are excluded: a revoked hash must refuse
// admission the same way an unknown one does.
func (q *Queries) ChannelInviteByHash(ctx context.Context, hash string) (ChannelInvite, error) {
	row := q.db.QueryRow(ctx, channelInviteByHash, hash)
	var i ChannelInvite
	err := row.Scan(
		&i.Hash,
		&i.ChannelID,
		&i.CreatorID,
		&i.Date,
		&i.RevokedAt,
	)
	return i, err
}

const channelInviteByHashForUpdate = `-- name: ChannelInviteByHashForUpdate :one
SELECT hash, channel_id, creator_id, date, revoked_at FROM channel_invites WHERE hash = $1 AND revoked_at IS NULL FOR UPDATE
`

// ChannelInviteByHashForUpdate is the locked variant used by JoinChannelByInvite.
// The row lock serialises admission against revocation: a concurrent
// RevokeChannelInvite UPDATE blocks until the join commits or rolls back. The
// preview path (ChannelByInvite) keeps the unlocked ChannelInviteByHash.
func (q *Queries) ChannelInviteByHashForUpdate(ctx context.Context, hash string) (ChannelInvite, error) {
	row := q.db.QueryRow(ctx, channelInviteByHashForUpdate, hash)
	var i ChannelInvite
	err := row.Scan(
		&i.Hash,
		&i.ChannelID,
		&i.CreatorID,
		&i.Date,
		&i.RevokedAt,
	)
	return i, err
}

const channelMegagroup = `-- name: ChannelMegagroup :one
SELECT megagroup FROM channels WHERE id = $1
`

// ChannelMegagroup reads only the channel kind needed for post authorization.
// In particular, this check must not fetch slow-mode state before membership
// and ban authorization has passed.
func (q *Queries) ChannelMegagroup(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, channelMegagroup, id)
	var megagroup bool
	err := row.Scan(&megagroup)
	return megagroup, err
}

const channelParticipantByUser = `-- name: ChannelParticipantByUser :one
SELECT channel_id, user_id, role, banned_until, join_pts, date, last_post_at FROM channel_participants WHERE channel_id = $1 AND user_id = $2
`

type ChannelParticipantByUserParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) ChannelParticipantByUser(ctx context.Context, arg ChannelParticipantByUserParams) (ChannelParticipant, error) {
	row := q.db.QueryRow(ctx, channelParticipantByUser, arg.ChannelID, arg.UserID)
	var i ChannelParticipant
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Role,
		&i.BannedUntil,
		&i.JoinPts,
		&i.Date,
		&i.LastPostAt,
	)
	return i, err
}

const channelParticipants = `-- name: ChannelParticipants :many
SELECT channel_id, user_id, role, banned_until, join_pts, date, last_post_at FROM channel_participants WHERE channel_id = $1 ORDER BY user_id
`

func (q *Queries) ChannelParticipants(ctx context.Context, channelID int64) ([]ChannelParticipant, error) {
	rows, err := q.db.Query(ctx, channelParticipants, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelParticipant
	for rows.Next() {
		var i ChannelParticipant
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Role,
			&i.BannedUntil,
			&i.JoinPts,
			&i.Date,
			&i.LastPostAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelParticipantsForViewer = `-- name: ChannelParticipantsForViewer :many
SELECT channel_id, user_id, role, banned_until, join_pts, date, last_post_at FROM channel_participants
WHERE user_id = $1::bigint
  AND channel_id = ANY($2::bigint[])
`

type ChannelParticipantsForViewerParams struct {
	ViewerID   int64
	ChannelIds []int64
}

// ChannelParticipantsForViewer answers "which of these channels is this caller
// in" in one query, for a caller-supplied set bounded by a page. It returns the
// whole participant row rather than a boolean so the ban stays ChannelMember's
// decision: this feeds a rendering choice, not a row set that a LIMIT then cuts,
// so there is no reason to spell the predicate a second time here.
func (q *Queries) ChannelParticipantsForViewer(ctx context.Context, arg ChannelParticipantsForViewerParams) ([]ChannelParticipant, error) {
	rows, err := q.db.Query(ctx, channelParticipantsForViewer, arg.ViewerID, arg.ChannelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelParticipant
	for rows.Next() {
		var i ChannelParticipant
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Role,
			&i.BannedUntil,
			&i.JoinPts,
			&i.Date,
			&i.LastPostAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelParticipantsPage = `-- name: ChannelParticipantsPage :many
SELECT cp.channel_id, cp.user_id, cp.role, cp.banned_until, cp.join_pts, cp.date, cp.last_post_at
FROM channel_participants cp
JOIN users u ON u.id = cp.user_id
LEFT JOIN usernames un ON un.owner_type = 'user' AND un.owner_id = cp.user_id
WHERE cp.channel_id = $1::bigint
  AND (
      ($2::int = 0 AND (cp.banned_until IS NULL OR cp.banned_until <= now()))
      OR ($2::int = 1 AND cp.role >= 1 AND (cp.banned_until IS NULL OR cp.banned_until <= now()))
      OR ($2::int IN (2, 3) AND cp.banned_until > now())
      OR ($2::int = 4 AND (cp.banned_until IS NULL OR cp.banned_until <= now())
          AND (u.name_tsv @@ plainto_tsquery('simple', $3::text)
               OR strpos(lower(COALESCE(un.handle, '')), lower($3::text)) > 0))
      OR ($2::int = 5 AND (cp.banned_until IS NULL OR cp.banned_until <= now())
          AND EXISTS (
              SELECT 1 FROM user_contacts uc
              WHERE uc.owner_id = $4::bigint
                AND uc.contact_id = cp.user_id
          ))
  )
  AND ($2::int NOT IN (2, 3) OR $3::text = ''
       OR u.name_tsv @@ plainto_tsquery('simple', $3::text)
       OR strpos(lower(COALESCE(un.handle, '')), lower($3::text)) > 0)
ORDER BY cp.user_id
LIMIT $6::int OFFSET $5::int
`

type ChannelParticipantsPageParams struct {
	ChannelID  int64
	Filter     int32
	Query      string
	ViewerID   int64
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ChannelParticipantsPage(ctx context.Context, arg ChannelParticipantsPageParams) ([]ChannelParticipant, error) {
	rows, err := q.db.Query(ctx, channelParticipantsPage,
		arg.ChannelID,
		arg.Filter,
		arg.Query,
		arg.ViewerID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelParticipant
	for rows.Next() {
		var i ChannelParticipant
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Role,
			&i.BannedUntil,
			&i.JoinPts,
			&i.Date,
			&i.LastPostAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelParticipantsPageCount = `-- name: ChannelParticipantsPageCount :one
SELECT count(*)::bigint
FROM channel_participants cp
JOIN users u ON u.id = cp.user_id
LEFT JOIN usernames un ON un.owner_type = 'user' AND un.owner_id = cp.user_id
WHERE cp.channel_id = $1::bigint
  AND (
      ($2::int = 0 AND (cp.banned_until IS NULL OR cp.banned_until <= now()))
      OR ($2::int = 1 AND cp.role >= 1 AND (cp.banned_until IS NULL OR cp.banned_until <= now()))
      OR ($2::int IN (2, 3) AND cp.banned_until > now())
      OR ($2::int = 4 AND (cp.banned_until IS NULL OR cp.banned_until <= now())
          AND (u.name_tsv @@ plainto_tsquery('simple', $3::text)
               OR strpos(lower(COALESCE(un.handle, '')), lower($3::text)) > 0))
      OR ($2::int = 5 AND (cp.banned_until IS NULL OR cp.banned_until <= now())
          AND EXISTS (
              SELECT 1 FROM user_contacts uc
              WHERE uc.owner_id = $4::bigint
                AND uc.contact_id = cp.user_id
          ))
  )
  AND ($2::int NOT IN (2, 3) OR $3::text = ''
       OR u.name_tsv @@ plainto_tsquery('simple', $3::text)
       OR strpos(lower(COALESCE(un.handle, '')), lower($3::text)) > 0)
`

type ChannelParticipantsPageCountParams struct {
	ChannelID int64
	Filter    int32
	Query     string
	ViewerID  int64
}

// Participant list reads run in one repeatable-read transaction with the
// viewer's membership check. The handler chooses only filters it can serve;
// both the count and page use the same filter so offsets cannot disclose rows
// outside the selected set.
func (q *Queries) ChannelParticipantsPageCount(ctx context.Context, arg ChannelParticipantsPageCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, channelParticipantsPageCount,
		arg.ChannelID,
		arg.Filter,
		arg.Query,
		arg.ViewerID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const channelPollParticipantForUpdate = `-- name: ChannelPollParticipantForUpdate :one
SELECT channel_id, user_id, role, banned_until, join_pts, date, last_post_at FROM channel_participants WHERE channel_id = $1 AND user_id = $2 FOR UPDATE
`

type ChannelPollParticipantForUpdateParams struct {
	ChannelID int64
	UserID    int64
}

// ChannelPollParticipantForUpdate serializes poll authorization with a ban,
// leave, or role change before a channel poll is mutated.
func (q *Queries) ChannelPollParticipantForUpdate(ctx context.Context, arg ChannelPollParticipantForUpdateParams) (ChannelParticipant, error) {
	row := q.db.QueryRow(ctx, channelPollParticipantForUpdate, arg.ChannelID, arg.UserID)
	var i ChannelParticipant
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Role,
		&i.BannedUntil,
		&i.JoinPts,
		&i.Date,
		&i.LastPostAt,
	)
	return i, err
}

const channelPostDefaults = `-- name: ChannelPostDefaults :one
SELECT megagroup, default_banned_rights FROM channels WHERE id = $1
`

type ChannelPostDefaultsRow struct {
	Megagroup           bool
	DefaultBannedRights []string
}

// ChannelPostDefaults reads the stored restrictions after post authorization
// and random_id deduplication. Keep slowmode_seconds out of this projection so
// a default-rights refusal takes precedence without observing slow-mode state.
func (q *Queries) ChannelPostDefaults(ctx context.Context, id int64) (ChannelPostDefaultsRow, error) {
	row := q.db.QueryRow(ctx, channelPostDefaults, id)
	var i ChannelPostDefaultsRow
	err := row.Scan(&i.Megagroup, &i.DefaultBannedRights)
	return i, err
}

const channelReadStateForViewer = `-- name: ChannelReadStateForViewer :one
SELECT COALESCE(read_state.read_max_id, 0)::bigint AS read_max_id,
       LEAST(GREATEST(unread.total_live - unread.author_live, 0), 1000)::int AS unread_count,
       unread.entitled::boolean AS summary_entitled,
       unread.status_exists::boolean AS summary_status_exists,
       unread.summary_version::smallint,
       unread.summary_ready::boolean,
       unread.total_live::bigint AS summary_total_live,
       unread.author_live::bigint AS summary_author_live
FROM channel_participants participant
LEFT JOIN channel_read_state read_state
  ON read_state.channel_id = participant.channel_id
 AND read_state.user_id = participant.user_id
CROSS JOIN LATERAL channel_post_unread_suffix_counts(
    participant.channel_id,
    participant.user_id,
    COALESCE(read_state.read_max_id, 0)
) AS unread(entitled, status_exists, summary_version, summary_ready, total_live, author_live)
WHERE participant.channel_id = $1::bigint
  AND participant.user_id = $2::bigint
  AND (participant.banned_until IS NULL OR participant.banned_until <= now())
`

type ChannelReadStateForViewerParams struct {
	ChannelID int64
	UserID    int64
}

type ChannelReadStateForViewerRow struct {
	ReadMaxID            int64
	UnreadCount          int32
	SummaryEntitled      bool
	SummaryStatusExists  bool
	UnreadSummaryVersion int16
	UnreadSummaryReady   bool
	SummaryTotalLive     int64
	SummaryAuthorLive    int64
}

// ChannelReadStateForViewer returns only the entitled member's read state and
// exact unread count from the bounded summary suffix lookup.
func (q *Queries) ChannelReadStateForViewer(ctx context.Context, arg ChannelReadStateForViewerParams) (ChannelReadStateForViewerRow, error) {
	row := q.db.QueryRow(ctx, channelReadStateForViewer, arg.ChannelID, arg.UserID)
	var i ChannelReadStateForViewerRow
	err := row.Scan(
		&i.ReadMaxID,
		&i.UnreadCount,
		&i.SummaryEntitled,
		&i.SummaryStatusExists,
		&i.UnreadSummaryVersion,
		&i.UnreadSummaryReady,
		&i.SummaryTotalLive,
		&i.SummaryAuthorLive,
	)
	return i, err
}

const channelSlowModePostState = `-- name: ChannelSlowModePostState :one
SELECT c.slowmode_seconds,
       GREATEST(cp.last_post_at, cpm.last_post_at)::timestamptz AS last_post_at,
       clock_timestamp()::timestamptz AS checked_at
FROM channels c
JOIN channel_participants cp ON cp.channel_id = c.id
LEFT JOIN channel_post_markers cpm
    ON cpm.channel_id = c.id AND cpm.user_id = cp.user_id
WHERE c.id = $1::bigint
  AND cp.user_id = $2::bigint
`

type ChannelSlowModePostStateParams struct {
	ChannelID int64
	UserID    int64
}

type ChannelSlowModePostStateRow struct {
	SlowmodeSeconds int16
	LastPostAt      pgtype.Timestamptz
	CheckedAt       pgtype.Timestamptz
}

// ChannelSlowModePostState is called only after membership, ban, post rights,
// deduplication and default restrictions are decided. clock_timestamp() is
// sampled after the caller took channel_state FOR UPDATE, so a transaction that
// waited for another post cannot compare against a stale transaction start. The
// durable marker survives leave/rejoin; the participant value remains as a
// fallback for rows written by older binaries during a rolling deploy.
func (q *Queries) ChannelSlowModePostState(ctx context.Context, arg ChannelSlowModePostStateParams) (ChannelSlowModePostStateRow, error) {
	row := q.db.QueryRow(ctx, channelSlowModePostState, arg.ChannelID, arg.UserID)
	var i ChannelSlowModePostStateRow
	err := row.Scan(&i.SlowmodeSeconds, &i.LastPostAt, &i.CheckedAt)
	return i, err
}

const channelStateForUpdate = `-- name: ChannelStateForUpdate :one
SELECT channel_id, pts, next_local_id, date FROM channel_state WHERE channel_id = $1 FOR UPDATE
`

// ChannelStateForUpdate takes the channel_state row lock that serialises
// admission to one channel: the pts a joiner records and the participant count
// the caps are decided on are both read under it. See the lock-order comment at
// the top of channels.go.
func (q *Queries) ChannelStateForUpdate(ctx context.Context, channelID int64) (ChannelState, error) {
	row := q.db.QueryRow(ctx, channelStateForUpdate, channelID)
	var i ChannelState
	err := row.Scan(
		&i.ChannelID,
		&i.Pts,
		&i.NextLocalID,
		&i.Date,
	)
	return i, err
}

const channelsForUser = `-- name: ChannelsForUser :many
SELECT c.id, c.title, c.about, c.creator_id, c.megagroup, c.version, c.date, c.pinned_message_id, c.username, c.title_tsv, c.publicly_discoverable, c.default_banned_rights, c.slowmode_seconds FROM channels c
JOIN channel_participants p ON p.channel_id = c.id
WHERE p.user_id = $1
ORDER BY c.id
`

func (q *Queries) ChannelsForUser(ctx context.Context, userID int64) ([]Channel, error) {
	rows, err := q.db.Query(ctx, channelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.About,
			&i.CreatorID,
			&i.Megagroup,
			&i.Version,
			&i.Date,
			&i.PinnedMessageID,
			&i.Username,
			&i.TitleTsv,
			&i.PubliclyDiscoverable,
			&i.DefaultBannedRights,
			&i.SlowmodeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countChannelParticipants = `-- name: CountChannelParticipants :one
SELECT count(*) FROM channel_participants WHERE channel_id = $1
`

func (q *Queries) CountChannelParticipants(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelParticipants, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChannelsForUser = `-- name: CountChannelsForUser :one
SELECT count(*) FROM channel_participants WHERE user_id = $1
`

// CountChannelsForUser backs the per-account cap. It counts memberships, so a
// channel the account was removed from stops counting against it.
func (q *Queries) CountChannelsForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChannelParticipant = `-- name: DeleteChannelParticipant :execrows
DELETE FROM channel_participants WHERE channel_id = $1 AND user_id = $2
`

type DeleteChannelParticipantParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) DeleteChannelParticipant(ctx context.Context, arg DeleteChannelParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelParticipant, arg.ChannelID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelPinnedMessage = `-- name: GetChannelPinnedMessage :one
SELECT pinned_message_id FROM channels WHERE id = $1
`

// GetChannelPinnedMessage reads the current pinned message id for a channel.
func (q *Queries) GetChannelPinnedMessage(ctx context.Context, id int64) (*int32, error) {
	row := q.db.QueryRow(ctx, getChannelPinnedMessage, id)
	var pinned_message_id *int32
	err := row.Scan(&pinned_message_id)
	return pinned_message_id, err
}

const insertChannel = `-- name: InsertChannel :one
INSERT INTO channels (id, title, about, creator_id, megagroup) VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, about, creator_id, megagroup, version, date, pinned_message_id, username, title_tsv, publicly_discoverable, default_banned_rights, slowmode_seconds
`

type InsertChannelParams struct {
	ID        int64
	Title     string
	About     string
	CreatorID int64
	Megagroup bool
}

// InsertChannel takes the id from the caller rather than from channels_id_seq.
// A new channel's id is a random draw over a sparse range (newChannelID in
// channels.go): a dense id set discloses, through its gaps, how many private
// channels exist and where in creation order each one sits. A repeated draw
// arrives here as a channels_pkey unique violation, which the caller answers by
// redrawing — never by letting the sequence supply the id.
func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, insertChannel,
		arg.ID,
		arg.Title,
		arg.About,
		arg.CreatorID,
		arg.Megagroup,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.Username,
		&i.TitleTsv,
		&i.PubliclyDiscoverable,
		&i.DefaultBannedRights,
		&i.SlowmodeSeconds,
	)
	return i, err
}

const insertChannelInvite = `-- name: InsertChannelInvite :exec
INSERT INTO channel_invites (hash, channel_id, creator_id) VALUES ($1, $2, $3)
`

type InsertChannelInviteParams struct {
	Hash      string
	ChannelID int64
	CreatorID int64
}

func (q *Queries) InsertChannelInvite(ctx context.Context, arg InsertChannelInviteParams) error {
	_, err := q.db.Exec(ctx, insertChannelInvite, arg.Hash, arg.ChannelID, arg.CreatorID)
	return err
}

const insertChannelParticipant = `-- name: InsertChannelParticipant :exec
INSERT INTO channel_participants (channel_id, user_id, role, join_pts) VALUES ($1, $2, $3, $4)
`

type InsertChannelParticipantParams struct {
	ChannelID int64
	UserID    int64
	Role      int16
	JoinPts   int64
}

func (q *Queries) InsertChannelParticipant(ctx context.Context, arg InsertChannelParticipantParams) error {
	_, err := q.db.Exec(ctx, insertChannelParticipant,
		arg.ChannelID,
		arg.UserID,
		arg.Role,
		arg.JoinPts,
	)
	return err
}

const insertChannelParticipantIfAbsent = `-- name: InsertChannelParticipantIfAbsent :execrows
INSERT INTO channel_participants (channel_id, user_id, role, join_pts) VALUES ($1, $2, $3, $4)
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type InsertChannelParticipantIfAbsentParams struct {
	ChannelID int64
	UserID    int64
	Role      int16
	JoinPts   int64
}

// InsertChannelParticipantIfAbsent reports 0 rows when the user already holds a
// row, which is what makes a repeated join a no-op instead of an error — and in
// particular never lowers an existing join_pts or clears an existing ban.
func (q *Queries) InsertChannelParticipantIfAbsent(ctx context.Context, arg InsertChannelParticipantIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertChannelParticipantIfAbsent,
		arg.ChannelID,
		arg.UserID,
		arg.Role,
		arg.JoinPts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertChannelReadStateForNewMember = `-- name: InsertChannelReadStateForNewMember :exec
INSERT INTO channel_read_state (channel_id, user_id, read_max_id)
VALUES ($1::bigint, $2::bigint,
        GREATEST($3::bigint, 0))
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type InsertChannelReadStateForNewMemberParams struct {
	ChannelID int64
	UserID    int64
	TopID     int64
}

// InsertChannelReadStateForNewMember starts a membership at the committed
// channel top captured while the caller holds channel_state FOR UPDATE. A
// repeated admission never rewrites an existing marker.
func (q *Queries) InsertChannelReadStateForNewMember(ctx context.Context, arg InsertChannelReadStateForNewMemberParams) error {
	_, err := q.db.Exec(ctx, insertChannelReadStateForNewMember, arg.ChannelID, arg.UserID, arg.TopID)
	return err
}

const insertChannelState = `-- name: InsertChannelState :exec
INSERT INTO channel_state (channel_id) VALUES ($1)
`

func (q *Queries) InsertChannelState(ctx context.Context, channelID int64) error {
	_, err := q.db.Exec(ctx, insertChannelState, channelID)
	return err
}

const isChannelMember = `-- name: IsChannelMember :one
SELECT EXISTS(SELECT 1 FROM channel_participants WHERE channel_id = $1 AND user_id = $2)
`

type IsChannelMemberParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelMember, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockChannel = `-- name: LockChannel :one
SELECT id, title, about, creator_id, megagroup, version, date, pinned_message_id, username, title_tsv, publicly_discoverable, default_banned_rights, slowmode_seconds FROM channels WHERE id = $1 FOR NO KEY UPDATE
`

// LockChannel serialises rights mutations while allowing FK key-share checks on
// channels to proceed. In particular, an invite can hold channel_state while a
// concurrent post inserts its channel_messages row without forming a lock cycle.
// The caller's and target's participant rows are read under this lock, so a
// demotion cannot interleave with the promotion it revokes. See channels.go.
func (q *Queries) LockChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, lockChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.Username,
		&i.TitleTsv,
		&i.PubliclyDiscoverable,
		&i.DefaultBannedRights,
		&i.SlowmodeSeconds,
	)
	return i, err
}

const revokeChannelInvite = `-- name: RevokeChannelInvite :execrows
UPDATE channel_invites SET revoked_at = COALESCE(revoked_at, now()) WHERE hash = $1 AND channel_id = $2
`

type RevokeChannelInviteParams struct {
	Hash      string
	ChannelID int64
}

func (q *Queries) RevokeChannelInvite(ctx context.Context, arg RevokeChannelInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeChannelInvite, arg.Hash, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchMemberChannels = `-- name: SearchMemberChannels :many
SELECT c.id, c.title, c.about, c.creator_id, c.megagroup, c.version, c.date,
       c.pinned_message_id, un.handle, p.role
FROM channels c
JOIN channel_participants p ON p.channel_id = c.id AND p.user_id = $1::bigint
LEFT JOIN usernames un ON un.owner_type = 'channel' AND un.owner_id = c.id
WHERE c.id IN (
    SELECT tc.id FROM channels tc
    WHERE tc.id = ANY($2::bigint[])
      AND tc.title_tsv @@ plainto_tsquery('simple', $3)
    UNION
    SELECT hu.owner_id FROM usernames hu WHERE hu.owner_type = 'channel' AND hu.handle = $4
)
  AND (p.banned_until IS NULL OR p.banned_until <= now())
ORDER BY c.id
LIMIT $5::int
`

type SearchMemberChannelsParams struct {
	ViewerID   int64
	ChannelIds []int64
	Query      string
	Handle     string
	Lim        int32
}

type SearchMemberChannelsRow struct {
	ID              int64
	Title           string
	About           string
	CreatorID       int64
	Megagroup       bool
	Version         int32
	Date            pgtype.Timestamptz
	PinnedMessageID *int32
	Handle          *string
	Role            int16
}

// SearchMemberChannels finds the channels the caller belongs to by title or by
// handle, public and private alike. Membership is the join, so a channel the
// caller never joined can never appear here whatever its title.
//
// The ban predicate is written here rather than left to ChannelMember.Banned
// for the reason FileForDownload records: it decides the row set that LIMIT
// then cuts, so a retained participant row of a banned member would otherwise
// displace a channel the caller may actually see. It must stay spelled the same
// way as Banned — NULL is not banned, "may act" is banned_until IS NULL OR
// banned_until <= now().
//
// The match is the same union of single-relation subqueries SearchPublicChannels
// uses, for the same planner reason, but the title disjunct here is scoped by
// channel_ids instead of by publicness. This arm cannot take the publicness
// marker — a member has to be able to find their own private channel by title,
// which is the whole point of the arm — so the bound it gets instead is the
// caller's own membership, spelled inside the statement.
//
// channel_ids is a scope, never the authorization, exactly as in
// SearchGlobalPage: it carries the caller's own unbanned channel ids, read
// separately off the index on channel_participants (user_id), and the join to
// channel_participants above is what decides who may see what. A stale or wrong
// id list can only narrow this arm, never widen it past the membership the join
// re-checks in the same statement.
//
// It is written as an explicit id set rather than left to the planner because
// the bound has to be structural. Without it the candidate set is every channel
// whose title matches, private ones included, filtered down to the caller's
// afterwards — so the cost of an empty answer counts the private channels
// sharing the token, which is the oracle M16 closed. A plan that avoids that by
// preference rather than by construction is one statistics change away from
// returning to it, and "index-driven" does not rule it out: a bitmap scan of a
// whole-table title index followed by a membership filter is index-driven and
// is precisely the leaking shape. With the id set in the predicate, and no
// index over every title left to scan, the plan is a primary-key scan over at
// most the per-account channel cap (channels.go, defaultMaxChannelsPerUser),
// whatever the corpus behind it looks like.
//
// The handle disjunct stays unscoped, and needs no scope: it is a primary-key
// lookup on usernames yielding at most one row, so it costs the same whatever
// the corpus holds, and a private channel has no row there to find. A channel
// it names that the caller does not belong to is dropped by the join above.
//
// No participant count here, unlike the public arm: a member is rendered by
// channelToTL, which carries no participants_count field, so counting would be
// a per-row aggregate over channel_participants whose result is discarded.
func (q *Queries) SearchMemberChannels(ctx context.Context, arg SearchMemberChannelsParams) ([]SearchMemberChannelsRow, error) {
	rows, err := q.db.Query(ctx, searchMemberChannels,
		arg.ViewerID,
		arg.ChannelIds,
		arg.Query,
		arg.Handle,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemberChannelsRow
	for rows.Next() {
		var i SearchMemberChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.About,
			&i.CreatorID,
			&i.Megagroup,
			&i.Version,
			&i.Date,
			&i.PinnedMessageID,
			&i.Handle,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublicChannels = `-- name: SearchPublicChannels :many
SELECT c.id, c.title, c.about, c.creator_id, c.megagroup, c.version, c.date,
       c.pinned_message_id, un.handle,
       (SELECT count(*) FROM channel_participants cp WHERE cp.channel_id = c.id) AS participants_count
FROM channels c
JOIN usernames un ON un.owner_type = 'channel' AND un.owner_id = c.id
WHERE c.id IN (
    SELECT tc.id FROM channels tc
    WHERE tc.publicly_discoverable
      AND tc.title_tsv @@ plainto_tsquery('simple', $1)
    UNION
    SELECT hu.owner_id FROM usernames hu WHERE hu.owner_type = 'channel' AND hu.handle = $2
)
ORDER BY c.id
LIMIT $3::int
`

type SearchPublicChannelsParams struct {
	Query  string
	Handle string
	Lim    int32
}

type SearchPublicChannelsRow struct {
	ID                int64
	Title             string
	About             string
	CreatorID         int64
	Megagroup         bool
	Version           int32
	Date              pgtype.Timestamptz
	PinnedMessageID   *int32
	Handle            string
	ParticipantsCount int64
}

// SearchPublicChannels finds the channels any account may discover by title or
// by handle: exactly those owning a row in usernames.
//
// The publicness predicate lives in the WHERE and therefore runs before LIMIT.
// That position is the whole security property. A private channel matching the
// tsquery must never occupy a row inside LIMIT that is then dropped in Go: the
// caller reads the shortfall in the returned row count as "a private channel
// matching my query exists", and probing LIMIT positions turns titles into an
// enumeration oracle over channels that are supposed to be invisible.
//
// The query takes no viewer, deliberately. Results is public discovery and is
// identical for every caller, so nothing in it can vary with the caller's own
// membership or ban state and be read back as information.
//
// Publicness is decided by the usernames row rather than the denormalized
// channels.username column. The two are written in one transaction today
// (ClaimChannelUsername), but only the usernames row is authoritative, and a
// future writer that releases a handle without clearing the copy must not leave
// the channel discoverable. The handle returned to the caller comes from the
// same row for the same reason: the username shown is the one that admitted the
// channel to this result, never the copy.
//
// publicly_discoverable in the title disjunct is not a second publicness test
// and must never be read as one. The join above stays the only thing deciding
// what this query returns; the marker decides what it costs. It is there so the
// candidate set holds public channels only: a private title matching the token
// was previously scanned, probed against usernames and discarded, so the time
// an empty answer took counted the private channels sharing a guessed word.
// With the marker in the predicate the partial index over public titles is the
// only index that can answer it, so the cost of this arm tracks the public
// matches — which the response discloses anyway — and nothing else.
//
// The match is a union of two single-relation subqueries rather than one OR
// spanning channels and usernames, and that shape is load-bearing rather than
// stylistic. An OR across two relations cannot be answered from either index:
// the planner scans every channel, joins every channel handle, and evaluates
// the disjunction as a join filter, so a query matching nothing costs the whole
// table (162.8 ms at 200k channels, against 1.99 ms here) and an authenticated
// account picks that worst case for free by sending a nonsense token. Each
// disjunct here restricts on its own relation, so the title arm is a bitmap
// scan of channels_public_title_tsv_idx and the handle arm a lookup on the
// usernames primary key.
func (q *Queries) SearchPublicChannels(ctx context.Context, arg SearchPublicChannelsParams) ([]SearchPublicChannelsRow, error) {
	rows, err := q.db.Query(ctx, searchPublicChannels, arg.Query, arg.Handle, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPublicChannelsRow
	for rows.Next() {
		var i SearchPublicChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.About,
			&i.CreatorID,
			&i.Megagroup,
			&i.Version,
			&i.Date,
			&i.PinnedMessageID,
			&i.Handle,
			&i.ParticipantsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelDefaultBannedRights = `-- name: SetChannelDefaultBannedRights :one
UPDATE channels
SET default_banned_rights = $2, version = version + 1
WHERE id = $1
RETURNING id, title, about, creator_id, megagroup, version, date, pinned_message_id, username, title_tsv, publicly_discoverable, default_banned_rights, slowmode_seconds
`

type SetChannelDefaultBannedRightsParams struct {
	ID                  int64
	DefaultBannedRights []string
}

// SetChannelDefaultBannedRights writes defaults after the caller's current
// membership, role, channel kind and equality have been checked under LockChannel.
func (q *Queries) SetChannelDefaultBannedRights(ctx context.Context, arg SetChannelDefaultBannedRightsParams) (Channel, error) {
	row := q.db.QueryRow(ctx, setChannelDefaultBannedRights, arg.ID, arg.DefaultBannedRights)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.Username,
		&i.TitleTsv,
		&i.PubliclyDiscoverable,
		&i.DefaultBannedRights,
		&i.SlowmodeSeconds,
	)
	return i, err
}

const setChannelPinnedMessage = `-- name: SetChannelPinnedMessage :one
UPDATE channels SET pinned_message_id = $2, version = version + 1 WHERE id = $1 RETURNING id, title, about, creator_id, megagroup, version, date, pinned_message_id, username, title_tsv, publicly_discoverable, default_banned_rights, slowmode_seconds
`

type SetChannelPinnedMessageParams struct {
	ID              int64
	PinnedMessageID *int32
}

// SetChannelPinnedMessage sets or clears the pinned message id on a channel.
// The pinned_message_id is the local_id of the pinned channel post. NULL clears
// the pin.
func (q *Queries) SetChannelPinnedMessage(ctx context.Context, arg SetChannelPinnedMessageParams) (Channel, error) {
	row := q.db.QueryRow(ctx, setChannelPinnedMessage, arg.ID, arg.PinnedMessageID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.Username,
		&i.TitleTsv,
		&i.PubliclyDiscoverable,
		&i.DefaultBannedRights,
		&i.SlowmodeSeconds,
	)
	return i, err
}

const setChannelSlowMode = `-- name: SetChannelSlowMode :one
UPDATE channels
SET slowmode_seconds = $2
WHERE id = $1
RETURNING id, title, about, creator_id, megagroup, version, date, pinned_message_id, username, title_tsv, publicly_discoverable, default_banned_rights, slowmode_seconds
`

type SetChannelSlowModeParams struct {
	ID              int64
	SlowmodeSeconds int16
}

// SetChannelSlowMode writes the megagroup interval after current admin authority
// and equality have been checked under LockChannel.
func (q *Queries) SetChannelSlowMode(ctx context.Context, arg SetChannelSlowModeParams) (Channel, error) {
	row := q.db.QueryRow(ctx, setChannelSlowMode, arg.ID, arg.SlowmodeSeconds)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.Username,
		&i.TitleTsv,
		&i.PubliclyDiscoverable,
		&i.DefaultBannedRights,
		&i.SlowmodeSeconds,
	)
	return i, err
}

const setChannelUsername = `-- name: SetChannelUsername :execrows
UPDATE channels c
SET username = $1,
    publicly_discoverable = EXISTS (
        SELECT 1 FROM usernames un
        WHERE un.owner_type = 'channel' AND un.owner_id = c.id
    )
WHERE c.id = $2
`

type SetChannelUsernameParams struct {
	Username *string
	ID       int64
}

// SetChannelUsername writes the denormalized handle copy and, with it,
// recomputes publicly_discoverable from the usernames table.
//
// The two live in one statement because there is one moment at which both are
// true: every writer of a channel handle — SetChannelUsername and
// ClaimChannelUsername, claim path and release path alike — mutates the
// usernames row and then calls this, inside the transaction that does both. A
// marker maintained at each of those call sites instead would be four places to
// keep in step; here there is one, and it reads the authoritative table rather
// than the argument, so it is a recomputation and not a second copy of the same
// assertion.
//
// A future writer that changes usernames without coming through here leaves the
// marker stale, and that is survivable by construction rather than by luck:
// publicly_discoverable decides cost only, the pre-LIMIT JOIN usernames in
// SearchPublicChannels decides disclosure, and a stale marker in the permissive
// direction costs a wasted candidate row that the join drops. See the migration
// header for the full asymmetry.
func (q *Queries) SetChannelUsername(ctx context.Context, arg SetChannelUsernameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelUsername, arg.Username, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelParticipantBan = `-- name: UpdateChannelParticipantBan :execrows
UPDATE channel_participants SET banned_until = $3 WHERE channel_id = $1 AND user_id = $2
`

type UpdateChannelParticipantBanParams struct {
	ChannelID   int64
	UserID      int64
	BannedUntil pgtype.Timestamptz
}

// banned_until takes SQL NULL to unban and 'infinity' for a permanent ban, so
// the parameter is a pgtype.Timestamptz — the same type the column decodes into.
func (q *Queries) UpdateChannelParticipantBan(ctx context.Context, arg UpdateChannelParticipantBanParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelParticipantBan, arg.ChannelID, arg.UserID, arg.BannedUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelParticipantRole = `-- name: UpdateChannelParticipantRole :execrows
UPDATE channel_participants SET role = $3 WHERE channel_id = $1 AND user_id = $2
`

type UpdateChannelParticipantRoleParams struct {
	ChannelID int64
	UserID    int64
	Role      int16
}

// UpdateChannelParticipantRole and UpdateChannelParticipantBan only ever update:
// neither may create a participant row, so 0 rows affected means the target is
// not a member and the caller rejects.
func (q *Queries) UpdateChannelParticipantRole(ctx context.Context, arg UpdateChannelParticipantRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelParticipantRole, arg.ChannelID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelPostMarker = `-- name: UpdateChannelPostMarker :execrows
WITH updated_participant AS (
    UPDATE channel_participants AS participant
    SET last_post_at = clock_timestamp()
    WHERE participant.channel_id = $1 AND participant.user_id = $2
    RETURNING participant.channel_id, participant.user_id, participant.last_post_at
)
INSERT INTO channel_post_markers (channel_id, user_id, last_post_at)
SELECT updated_participant.channel_id, updated_participant.user_id, updated_participant.last_post_at
FROM updated_participant
ON CONFLICT (channel_id, user_id) DO UPDATE
SET last_post_at = EXCLUDED.last_post_at
`

type UpdateChannelPostMarkerParams struct {
	ChannelID int64
	UserID    int64
}

// Posts already hold channel_state FOR UPDATE. Update both the membership-scoped
// compatibility value and the durable marker from one database timestamp.
func (q *Queries) UpdateChannelPostMarker(ctx context.Context, arg UpdateChannelPostMarkerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChannelPostMarker, arg.ChannelID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
