// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_polls.sql

package db

import (
	"context"
)

const channelPollMessageLocalIDs = `-- name: ChannelPollMessageLocalIDs :many
SELECT local_id
FROM channel_poll_messages
WHERE channel_id = $1::bigint
  AND local_id = ANY($2::bigint[])
ORDER BY local_id
`

type ChannelPollMessageLocalIDsParams struct {
	ChannelID int64
	LocalIds  []int64
}

func (q *Queries) ChannelPollMessageLocalIDs(ctx context.Context, arg ChannelPollMessageLocalIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, channelPollMessageLocalIDs, arg.ChannelID, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var local_id int64
		if err := rows.Scan(&local_id); err != nil {
			return nil, err
		}
		items = append(items, local_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelPollRecipients = `-- name: ChannelPollRecipients :many
SELECT user_id
FROM channel_participants
WHERE channel_id = $1
  AND (banned_until IS NULL OR banned_until <= clock_timestamp())
ORDER BY user_id
`

func (q *Queries) ChannelPollRecipients(ctx context.Context, channelID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, channelPollRecipients, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChannelPollMessage = `-- name: InsertChannelPollMessage :execrows
INSERT INTO channel_poll_messages (channel_id, local_id, poll_id)
VALUES ($1, $2, $3)
ON CONFLICT (channel_id, local_id) DO NOTHING
`

type InsertChannelPollMessageParams struct {
	ChannelID int64
	LocalID   int64
	PollID    int64
}

func (q *Queries) InsertChannelPollMessage(ctx context.Context, arg InsertChannelPollMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertChannelPollMessage, arg.ChannelID, arg.LocalID, arg.PollID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pollByChannelMessage = `-- name: PollByChannelMessage :one
SELECT p.id, p.creator_id, p.random_id, p.source_local_id, p.question, p.public_voters, p.multiple_choice, p.quiz, p.shuffle_answers, p.revoting_disabled, p.closed, p.close_date, p.solution, p.created_at
FROM polls p
JOIN channel_poll_messages cpm ON cpm.poll_id = p.id
JOIN channel_messages cm ON cm.channel_id = cpm.channel_id AND cm.local_id = cpm.local_id
WHERE cpm.channel_id = $1
  AND cpm.local_id = $2
  AND cm.deleted = false
`

type PollByChannelMessageParams struct {
	ChannelID int64
	LocalID   int64
}

func (q *Queries) PollByChannelMessage(ctx context.Context, arg PollByChannelMessageParams) (Poll, error) {
	row := q.db.QueryRow(ctx, pollByChannelMessage, arg.ChannelID, arg.LocalID)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.RandomID,
		&i.SourceLocalID,
		&i.Question,
		&i.PublicVoters,
		&i.MultipleChoice,
		&i.Quiz,
		&i.ShuffleAnswers,
		&i.RevotingDisabled,
		&i.Closed,
		&i.CloseDate,
		&i.Solution,
		&i.CreatedAt,
	)
	return i, err
}

const pollChannelMessageForViewer = `-- name: PollChannelMessageForViewer :one
SELECT cpm.channel_id, cpm.local_id
FROM channel_poll_messages cpm
JOIN channel_participants cp ON cp.channel_id = cpm.channel_id
WHERE cpm.poll_id = $1
  AND cp.user_id = $2
  AND (cp.banned_until IS NULL OR cp.banned_until <= clock_timestamp())
`

type PollChannelMessageForViewerParams struct {
	PollID int64
	UserID int64
}

type PollChannelMessageForViewerRow struct {
	ChannelID int64
	LocalID   int64
}

func (q *Queries) PollChannelMessageForViewer(ctx context.Context, arg PollChannelMessageForViewerParams) (PollChannelMessageForViewerRow, error) {
	row := q.db.QueryRow(ctx, pollChannelMessageForViewer, arg.PollID, arg.UserID)
	var i PollChannelMessageForViewerRow
	err := row.Scan(&i.ChannelID, &i.LocalID)
	return i, err
}
