// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package db

import (
	"context"
)

const bumpChatVersion = `-- name: BumpChatVersion :one
UPDATE chats SET version = version + 1 WHERE id = $1 RETURNING id, title, creator_id, version, date, pinned_message_id, default_banned_rights
`

func (q *Queries) BumpChatVersion(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, bumpChatVersion, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.DefaultBannedRights,
	)
	return i, err
}

const chatAdminEventRecipientsByEvent = `-- name: ChatAdminEventRecipientsByEvent :many
SELECT recipient.owner_id
FROM chat_admin_event_recipients AS recipient
JOIN chat_admin_events AS event ON event.id = recipient.event_id
JOIN chat_participants AS participant
  ON participant.chat_id = recipient.chat_id
 AND participant.user_id = recipient.owner_id
WHERE recipient.event_id = $1
  AND recipient.chat_id = event.chat_id
  AND recipient.target_id = event.user_id
ORDER BY recipient.owner_id
`

// ChatAdminEventRecipientsByEvent returns only recipients who remain members;
// a delayed live push must not disclose an admin event after a member leaves.
func (q *Queries) ChatAdminEventRecipientsByEvent(ctx context.Context, eventID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, chatAdminEventRecipientsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var owner_id int64
		if err := rows.Scan(&owner_id); err != nil {
			return nil, err
		}
		items = append(items, owner_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatAdminEventsByIDs = `-- name: ChatAdminEventsByIDs :many
SELECT id, chat_id, user_id, is_admin, version FROM chat_admin_events
WHERE id = ANY($1::bigint[])
ORDER BY id
`

func (q *Queries) ChatAdminEventsByIDs(ctx context.Context, eventIds []int64) ([]ChatAdminEvent, error) {
	rows, err := q.db.Query(ctx, chatAdminEventsByIDs, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatAdminEvent
	for rows.Next() {
		var i ChatAdminEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.IsAdmin,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatAdminSnapshotsForMember = `-- name: ChatAdminSnapshotsForMember :many
SELECT marker.event_id,
       marker.chat_id,
       marker.target_id AS user_id,
       target.is_admin,
       chat.version
FROM chat_admin_state_markers AS marker
JOIN chat_admin_events AS event
  ON event.id = marker.event_id
 AND event.chat_id = marker.chat_id
 AND event.user_id = marker.target_id
JOIN chat_participants AS viewer
  ON viewer.chat_id = marker.chat_id
 AND viewer.user_id = marker.owner_id
JOIN chats AS chat ON chat.id = marker.chat_id
JOIN chat_participants AS target
  ON target.chat_id = marker.chat_id
 AND target.user_id = marker.target_id
WHERE marker.owner_id = $1
ORDER BY marker.event_id
LIMIT $2::int
`

type ChatAdminSnapshotsForMemberParams struct {
	OwnerID int64
	Lim     int32
}

type ChatAdminSnapshotsForMemberRow struct {
	EventID int64
	ChatID  int64
	UserID  int64
	IsAdmin bool
	Version int32
}

// ChatAdminSnapshotsForMember returns the current role state for each target
// with a pending pull marker. EventID lets the response-success hook consume
// only versions included in this response, preserving newer concurrent changes.
func (q *Queries) ChatAdminSnapshotsForMember(ctx context.Context, arg ChatAdminSnapshotsForMemberParams) ([]ChatAdminSnapshotsForMemberRow, error) {
	rows, err := q.db.Query(ctx, chatAdminSnapshotsForMember, arg.OwnerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatAdminSnapshotsForMemberRow
	for rows.Next() {
		var i ChatAdminSnapshotsForMemberRow
		if err := rows.Scan(
			&i.EventID,
			&i.ChatID,
			&i.UserID,
			&i.IsAdmin,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatByID = `-- name: ChatByID :one
SELECT id, title, creator_id, version, date, pinned_message_id, default_banned_rights FROM chats WHERE id = $1
`

func (q *Queries) ChatByID(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, chatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.DefaultBannedRights,
	)
	return i, err
}

const chatByIDForUpdate = `-- name: ChatByIDForUpdate :one
SELECT id, title, creator_id, version, date, pinned_message_id, default_banned_rights FROM chats WHERE id = $1 FOR UPDATE
`

// ChatByIDForUpdate takes the chats row lock that serialises everything touching
// one chat's member set: the fan-out reads the member set under it, and the
// membership mutations take it before changing that set. See the lock-order
// comment at the top of chats.go.
func (q *Queries) ChatByIDForUpdate(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, chatByIDForUpdate, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.DefaultBannedRights,
	)
	return i, err
}

const chatParticipantCountsByChatIDs = `-- name: ChatParticipantCountsByChatIDs :many
SELECT chat_id, count(*)::bigint AS participant_count
FROM chat_participants
WHERE chat_id = ANY($1::bigint[])
GROUP BY chat_id
ORDER BY chat_id
`

type ChatParticipantCountsByChatIDsRow struct {
	ChatID           int64
	ParticipantCount int64
}

func (q *Queries) ChatParticipantCountsByChatIDs(ctx context.Context, chatIds []int64) ([]ChatParticipantCountsByChatIDsRow, error) {
	rows, err := q.db.Query(ctx, chatParticipantCountsByChatIDs, chatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatParticipantCountsByChatIDsRow
	for rows.Next() {
		var i ChatParticipantCountsByChatIDsRow
		if err := rows.Scan(&i.ChatID, &i.ParticipantCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatParticipants = `-- name: ChatParticipants :many
SELECT chat_id, user_id, inviter_id, date, is_admin FROM chat_participants WHERE chat_id = $1 ORDER BY user_id
`

// ChatParticipants is ascending by user_id: the fan-out takes its advisory locks
// in that order, so a stable ascending member list is what keeps it deadlock-free.
func (q *Queries) ChatParticipants(ctx context.Context, chatID int64) ([]ChatParticipant, error) {
	rows, err := q.db.Query(ctx, chatParticipants, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatParticipant
	for rows.Next() {
		var i ChatParticipant
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.InviterID,
			&i.Date,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatPinSnapshot = `-- name: ChatPinSnapshot :many
SELECT p.user_id,
       c.pinned_message_id,
       viewer_copy.local_id
FROM chats c
JOIN chat_participants p ON p.chat_id = c.id
LEFT JOIN messages creator_copy
  ON creator_copy.owner_id = c.creator_id
 AND creator_copy.local_id = c.pinned_message_id
 AND creator_copy.peer_type = $1::smallint
 AND creator_copy.peer_id = c.id
 AND creator_copy.fanout_id <> 0
 AND creator_copy.deleted = false
LEFT JOIN messages viewer_copy
  ON viewer_copy.owner_id = p.user_id
 AND viewer_copy.fanout_id = creator_copy.fanout_id
 AND viewer_copy.peer_type = $1::smallint
 AND viewer_copy.peer_id = c.id
 AND viewer_copy.deleted = false
WHERE c.id = $2::bigint
ORDER BY p.user_id
`

type ChatPinSnapshotParams struct {
	PeerType int16
	ChatID   int64
}

type ChatPinSnapshotRow struct {
	UserID          int64
	PinnedMessageID *int32
	LocalID         *int64
}

// ChatPinSnapshot reads the selected pin and each member's local copy from one
// statement snapshot, so a concurrent repin cannot split one notification.
// Missing or deleted copies remain NULL while the participant still receives
// the pinned state.
func (q *Queries) ChatPinSnapshot(ctx context.Context, arg ChatPinSnapshotParams) ([]ChatPinSnapshotRow, error) {
	rows, err := q.db.Query(ctx, chatPinSnapshot, arg.PeerType, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatPinSnapshotRow
	for rows.Next() {
		var i ChatPinSnapshotRow
		if err := rows.Scan(&i.UserID, &i.PinnedMessageID, &i.LocalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatPinnedMessageForOwner = `-- name: ChatPinnedMessageForOwner :one
SELECT viewer_copy.local_id
FROM chats c
JOIN chat_participants p ON p.chat_id = c.id AND p.user_id = $1::bigint
JOIN messages creator_copy
  ON creator_copy.owner_id = c.creator_id
 AND creator_copy.local_id = c.pinned_message_id
 AND creator_copy.peer_type = $2::smallint
 AND creator_copy.peer_id = c.id
 AND creator_copy.fanout_id <> 0
 AND creator_copy.deleted = false
JOIN messages viewer_copy
  ON viewer_copy.owner_id = p.user_id
 AND viewer_copy.fanout_id = creator_copy.fanout_id
 AND viewer_copy.peer_type = $2::smallint
 AND viewer_copy.peer_id = c.id
 AND viewer_copy.deleted = false
WHERE c.id = $3::bigint
  AND c.pinned_message_id IS NOT NULL
`

type ChatPinnedMessageForOwnerParams struct {
	OwnerID  int64
	PeerType int16
	ChatID   int64
}

// ChatPinnedMessageForOwner resolves the creator-owned pin to the requested
// member's copy. fanout_id identifies one logical chat message across each
// member-owned row; the returned local_id always belongs to owner_id.
// Deleted or missing source/member copies intentionally produce no row.
func (q *Queries) ChatPinnedMessageForOwner(ctx context.Context, arg ChatPinnedMessageForOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, chatPinnedMessageForOwner, arg.OwnerID, arg.PeerType, arg.ChatID)
	var local_id int64
	err := row.Scan(&local_id)
	return local_id, err
}

const chatsByIDsForMember = `-- name: ChatsByIDsForMember :many
SELECT c.id, c.title, c.creator_id, c.version, c.date, c.pinned_message_id, c.default_banned_rights FROM chats c
JOIN chat_participants p ON p.chat_id = c.id
WHERE p.user_id = $1::bigint
  AND c.id = ANY($2::bigint[])
ORDER BY c.id
`

type ChatsByIDsForMemberParams struct {
	UserID  int64
	ChatIds []int64
}

// A missing chat and a chat without a membership row for the viewer both
// produce no result. Keep the read on the basic-chat tables so equal numeric
// ids in users or channels cannot resolve to those peer types.
func (q *Queries) ChatsByIDsForMember(ctx context.Context, arg ChatsByIDsForMemberParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, chatsByIDsForMember, arg.UserID, arg.ChatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatorID,
			&i.Version,
			&i.Date,
			&i.PinnedMessageID,
			&i.DefaultBannedRights,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatsForUser = `-- name: ChatsForUser :many
SELECT c.id, c.title, c.creator_id, c.version, c.date, c.pinned_message_id, c.default_banned_rights FROM chats c
JOIN chat_participants p ON p.chat_id = c.id
WHERE p.user_id = $1
ORDER BY c.id
`

func (q *Queries) ChatsForUser(ctx context.Context, userID int64) ([]Chat, error) {
	rows, err := q.db.Query(ctx, chatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatorID,
			&i.Version,
			&i.Date,
			&i.PinnedMessageID,
			&i.DefaultBannedRights,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChatAdminStateMarkersByEventIDs = `-- name: DeleteChatAdminStateMarkersByEventIDs :exec
DELETE FROM chat_admin_state_markers
WHERE owner_id = $1
  AND event_id = ANY($2::bigint[])
`

type DeleteChatAdminStateMarkersByEventIDsParams struct {
	OwnerID  int64
	EventIds []int64
}

// DeleteChatAdminStateMarkersByEventIDs consumes the exact versions included
// in a successfully written difference response.
func (q *Queries) DeleteChatAdminStateMarkersByEventIDs(ctx context.Context, arg DeleteChatAdminStateMarkersByEventIDsParams) error {
	_, err := q.db.Exec(ctx, deleteChatAdminStateMarkersByEventIDs, arg.OwnerID, arg.EventIds)
	return err
}

const deleteChatParticipant = `-- name: DeleteChatParticipant :execrows
DELETE FROM chat_participants WHERE chat_id = $1 AND user_id = $2
`

type DeleteChatParticipantParams struct {
	ChatID int64
	UserID int64
}

// DeleteChatParticipant is called from exactly one place: removeParticipant in
// chats.go, which also takes the removed user's advisory lock. See its comment.
func (q *Queries) DeleteChatParticipant(ctx context.Context, arg DeleteChatParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatParticipant, arg.ChatID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatPinnedMessage = `-- name: GetChatPinnedMessage :one
SELECT pinned_message_id FROM chats WHERE id = $1
`

// GetChatPinnedMessage reads the current pinned message id for a chat.
func (q *Queries) GetChatPinnedMessage(ctx context.Context, id int64) (*int32, error) {
	row := q.db.QueryRow(ctx, getChatPinnedMessage, id)
	var pinned_message_id *int32
	err := row.Scan(&pinned_message_id)
	return pinned_message_id, err
}

const insertChat = `-- name: InsertChat :one
INSERT INTO chats (title, creator_id) VALUES ($1, $2)
RETURNING id, title, creator_id, version, date, pinned_message_id, default_banned_rights
`

type InsertChatParams struct {
	Title     string
	CreatorID int64
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, insertChat, arg.Title, arg.CreatorID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.DefaultBannedRights,
	)
	return i, err
}

const insertChatAdminEvent = `-- name: InsertChatAdminEvent :one
INSERT INTO chat_admin_events (chat_id, user_id, is_admin, version)
VALUES ($1, $2, $3, $4)
RETURNING id, chat_id, user_id, is_admin, version
`

type InsertChatAdminEventParams struct {
	ChatID  int64
	UserID  int64
	IsAdmin bool
	Version int32
}

func (q *Queries) InsertChatAdminEvent(ctx context.Context, arg InsertChatAdminEventParams) (ChatAdminEvent, error) {
	row := q.db.QueryRow(ctx, insertChatAdminEvent,
		arg.ChatID,
		arg.UserID,
		arg.IsAdmin,
		arg.Version,
	)
	var i ChatAdminEvent
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.IsAdmin,
		&i.Version,
	)
	return i, err
}

const insertChatParticipant = `-- name: InsertChatParticipant :exec
INSERT INTO chat_participants (chat_id, user_id, inviter_id) VALUES ($1, $2, $3)
`

type InsertChatParticipantParams struct {
	ChatID    int64
	UserID    int64
	InviterID int64
}

func (q *Queries) InsertChatParticipant(ctx context.Context, arg InsertChatParticipantParams) error {
	_, err := q.db.Exec(ctx, insertChatParticipant, arg.ChatID, arg.UserID, arg.InviterID)
	return err
}

const insertChatParticipantIfAbsent = `-- name: InsertChatParticipantIfAbsent :execrows
INSERT INTO chat_participants (chat_id, user_id, inviter_id) VALUES ($1, $2, $3)
ON CONFLICT (chat_id, user_id) DO NOTHING
`

type InsertChatParticipantIfAbsentParams struct {
	ChatID    int64
	UserID    int64
	InviterID int64
}

// InsertChatParticipantIfAbsent reports 0 rows when the user is already a member,
// which is what makes a repeated add a no-op instead of an error.
func (q *Queries) InsertChatParticipantIfAbsent(ctx context.Context, arg InsertChatParticipantIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertChatParticipantIfAbsent, arg.ChatID, arg.UserID, arg.InviterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isChatMember = `-- name: IsChatMember :one
SELECT EXISTS(SELECT 1 FROM chat_participants WHERE chat_id = $1 AND user_id = $2)
`

type IsChatMemberParams struct {
	ChatID int64
	UserID int64
}

func (q *Queries) IsChatMember(ctx context.Context, arg IsChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatMember, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchPinnedChatMessageForOwner = `-- name: SearchPinnedChatMessageForOwner :many
SELECT viewer_copy.owner_id, viewer_copy.local_id, viewer_copy.peer_id, viewer_copy.from_id, viewer_copy.date, viewer_copy.message, viewer_copy.out, viewer_copy.edit_date, viewer_copy.deleted, viewer_copy.random_id, viewer_copy.peer_local_id, viewer_copy.peer_type, viewer_copy.fanout_id, viewer_copy.action_type, viewer_copy.action_user_id, viewer_copy.file_id, viewer_copy.reply_to_msg_id, viewer_copy.fwd_from_id, viewer_copy.fwd_date, viewer_copy.fwd_channel_id, viewer_copy.fwd_channel_post, viewer_copy.message_tsv, viewer_copy.reply_to_trusted
FROM chats c
JOIN chat_participants p
  ON p.chat_id = c.id AND p.user_id = $1::bigint
JOIN messages creator_copy
  ON creator_copy.owner_id = c.creator_id
 AND creator_copy.local_id = c.pinned_message_id
 AND creator_copy.peer_type = $2::smallint
 AND creator_copy.peer_id = c.id
 AND creator_copy.fanout_id <> 0
 AND creator_copy.deleted = false
JOIN messages viewer_copy
  ON viewer_copy.owner_id = p.user_id
 AND viewer_copy.fanout_id = creator_copy.fanout_id
 AND viewer_copy.peer_type = $2::smallint
 AND viewer_copy.peer_id = c.id
 AND viewer_copy.deleted = false
WHERE c.id = $3::bigint
  AND c.pinned_message_id IS NOT NULL
  AND ($4::text = '' OR viewer_copy.message_tsv @@ plainto_tsquery('simple', $4))
  AND ($5::bigint = 0 OR viewer_copy.local_id < $5::bigint)
ORDER BY viewer_copy.local_id DESC
LIMIT $6::int
`

type SearchPinnedChatMessageForOwnerParams struct {
	OwnerID  int64
	PeerType int16
	ChatID   int64
	Query    string
	OffsetID int64
	Lim      int32
}

// SearchPinnedChatMessageForOwner returns the active viewer-owned copy of the
// chat's current pin. The creator row identifies the logical fan-out, while
// the participant join and viewer copy keep the result scoped to this member's
// local id space. Search text and pagination narrow that single pinned row.
func (q *Queries) SearchPinnedChatMessageForOwner(ctx context.Context, arg SearchPinnedChatMessageForOwnerParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, searchPinnedChatMessageForOwner,
		arg.OwnerID,
		arg.PeerType,
		arg.ChatID,
		arg.Query,
		arg.OffsetID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
			&i.ReplyToTrusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChatDefaultBannedRights = `-- name: SetChatDefaultBannedRights :one
UPDATE chats
SET default_banned_rights = $2, version = version + 1
WHERE id = $1
RETURNING id, title, creator_id, version, date, pinned_message_id, default_banned_rights
`

type SetChatDefaultBannedRightsParams struct {
	ID                  int64
	DefaultBannedRights []string
}

func (q *Queries) SetChatDefaultBannedRights(ctx context.Context, arg SetChatDefaultBannedRightsParams) (Chat, error) {
	row := q.db.QueryRow(ctx, setChatDefaultBannedRights, arg.ID, arg.DefaultBannedRights)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.DefaultBannedRights,
	)
	return i, err
}

const setChatParticipantAdmin = `-- name: SetChatParticipantAdmin :execrows
UPDATE chat_participants SET is_admin = $3 WHERE chat_id = $1 AND user_id = $2
`

type SetChatParticipantAdminParams struct {
	ChatID  int64
	UserID  int64
	IsAdmin bool
}

func (q *Queries) SetChatParticipantAdmin(ctx context.Context, arg SetChatParticipantAdminParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChatParticipantAdmin, arg.ChatID, arg.UserID, arg.IsAdmin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setChatPinnedMessage = `-- name: SetChatPinnedMessage :one
UPDATE chats SET pinned_message_id = $2, version = version + 1 WHERE id = $1 RETURNING id, title, creator_id, version, date, pinned_message_id, default_banned_rights
`

type SetChatPinnedMessageParams struct {
	ID              int64
	PinnedMessageID *int32
}

// SetChatPinnedMessage sets or clears the pinned message id on a chat.
// The pinned_message_id stores the creator-owned copy's local_id; fanout_id
// resolves that logical message to each member's local copy. NULL clears the pin.
func (q *Queries) SetChatPinnedMessage(ctx context.Context, arg SetChatPinnedMessageParams) (Chat, error) {
	row := q.db.QueryRow(ctx, setChatPinnedMessage, arg.ID, arg.PinnedMessageID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.DefaultBannedRights,
	)
	return i, err
}

const setChatTitle = `-- name: SetChatTitle :one
UPDATE chats SET title = $2, version = version + 1 WHERE id = $1 RETURNING id, title, creator_id, version, date, pinned_message_id, default_banned_rights
`

type SetChatTitleParams struct {
	ID    int64
	Title string
}

func (q *Queries) SetChatTitle(ctx context.Context, arg SetChatTitleParams) (Chat, error) {
	row := q.db.QueryRow(ctx, setChatTitle, arg.ID, arg.Title)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatorID,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.DefaultBannedRights,
	)
	return i, err
}

const upsertChatAdminEventRecipients = `-- name: UpsertChatAdminEventRecipients :exec
INSERT INTO chat_admin_event_recipients (owner_id, chat_id, target_id, event_id)
SELECT recipient.owner_id, $1::bigint, $2::bigint, $3::bigint
FROM unnest($4::bigint[]) AS recipient(owner_id)
ON CONFLICT (owner_id, chat_id, target_id)
DO UPDATE SET event_id = EXCLUDED.event_id
`

type UpsertChatAdminEventRecipientsParams struct {
	ChatID   int64
	TargetID int64
	EventID  int64
	OwnerIds []int64
}

// UpsertChatAdminEventRecipients keeps one current live recipient per
// member/chat/target tuple for transient fanout in the role mutation transaction.
func (q *Queries) UpsertChatAdminEventRecipients(ctx context.Context, arg UpsertChatAdminEventRecipientsParams) error {
	_, err := q.db.Exec(ctx, upsertChatAdminEventRecipients,
		arg.ChatID,
		arg.TargetID,
		arg.EventID,
		arg.OwnerIds,
	)
	return err
}

const upsertChatAdminStateMarkers = `-- name: UpsertChatAdminStateMarkers :exec
INSERT INTO chat_admin_state_markers (owner_id, chat_id, target_id, event_id)
SELECT recipient.owner_id, $1::bigint, $2::bigint, $3::bigint
FROM unnest($4::bigint[]) AS recipient(owner_id)
ON CONFLICT (owner_id, chat_id, target_id)
DO UPDATE SET event_id = EXCLUDED.event_id
`

type UpsertChatAdminStateMarkersParams struct {
	ChatID   int64
	TargetID int64
	EventID  int64
	OwnerIds []int64
}

// UpsertChatAdminStateMarkers keeps the latest pending pull version separately
// so acknowledging one connection's difference does not suppress live fanout.
func (q *Queries) UpsertChatAdminStateMarkers(ctx context.Context, arg UpsertChatAdminStateMarkersParams) error {
	_, err := q.db.Exec(ctx, upsertChatAdminStateMarkers,
		arg.ChatID,
		arg.TargetID,
		arg.EventID,
		arg.OwnerIds,
	)
	return err
}
