// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cloud_drafts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cloudDraftChangesForOwnerSince = `-- name: CloudDraftChangesForOwnerSince :many
SELECT changed.peer_type,
       changed.peer_id,
       changed.changed_at,
       (draft.owner_id IS NOT NULL) AS has_draft,
       COALESCE(draft.message, '') AS message,
       COALESCE(draft.no_webpage, false) AS no_webpage,
       CASE
           WHEN draft.reply_to_msg_id IS NULL THEN 0::bigint
           WHEN draft.peer_type = 3 AND EXISTS (
               SELECT 1 FROM channel_messages AS target
               WHERE target.channel_id = draft.peer_id
                 AND target.local_id = draft.reply_to_msg_id
                 AND target.deleted = false
                 AND target.action_type = 0
           ) THEN draft.reply_to_msg_id
           WHEN draft.peer_type <> 3 AND EXISTS (
               SELECT 1 FROM messages AS target
               WHERE target.owner_id = draft.owner_id
                 AND target.peer_type = draft.peer_type
                 AND target.peer_id = draft.peer_id
                 AND target.local_id = draft.reply_to_msg_id
                 AND target.deleted = false
                 AND target.action_type = 0
           ) THEN draft.reply_to_msg_id
           ELSE 0::bigint
       END AS reply_to_msg_id,
       COALESCE(draft.updated_at, changed.changed_at) AS updated_at
FROM cloud_draft_sync AS changed
LEFT JOIN cloud_drafts AS draft
  ON draft.owner_id = changed.owner_id
 AND draft.peer_type = changed.peer_type
 AND draft.peer_id = changed.peer_id
WHERE changed.owner_id = $1
  AND changed.changed_at >= $2
  AND (
      (changed.peer_type = 1 AND EXISTS (
          SELECT 1 FROM dialogs AS dialog
          WHERE dialog.owner_id = changed.owner_id
            AND dialog.peer_type = changed.peer_type
            AND dialog.peer_id = changed.peer_id
      ))
      OR (changed.peer_type = 2 AND EXISTS (
          SELECT 1 FROM chat_participants AS participant
          WHERE participant.chat_id = changed.peer_id AND participant.user_id = changed.owner_id
      ))
      OR (changed.peer_type = 3 AND EXISTS (
          SELECT 1 FROM channel_participants AS participant
          WHERE participant.channel_id = changed.peer_id
            AND participant.user_id = changed.owner_id
            AND (participant.banned_until IS NULL OR participant.banned_until <= now())
      ))
  )
ORDER BY changed.changed_at, changed.peer_type, changed.peer_id
LIMIT 501
`

type CloudDraftChangesForOwnerSinceParams struct {
	OwnerID      int64
	ChangedSince pgtype.Timestamptz
}

type CloudDraftChangesForOwnerSinceRow struct {
	PeerType     int16
	PeerID       int64
	ChangedAt    pgtype.Timestamptz
	HasDraft     interface{}
	Message      string
	NoWebpage    bool
	ReplyToMsgID int64
	UpdatedAt    pgtype.Timestamptz
}

// CloudDraftChangesForOwnerSince is a separate non-PTS recovery stream. The
// extra row lets the caller detect a capped page and continue from its marker
// date; the peer key carries no text, and current values resolve at read time.
func (q *Queries) CloudDraftChangesForOwnerSince(ctx context.Context, arg CloudDraftChangesForOwnerSinceParams) ([]CloudDraftChangesForOwnerSinceRow, error) {
	rows, err := q.db.Query(ctx, cloudDraftChangesForOwnerSince, arg.OwnerID, arg.ChangedSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CloudDraftChangesForOwnerSinceRow
	for rows.Next() {
		var i CloudDraftChangesForOwnerSinceRow
		if err := rows.Scan(
			&i.PeerType,
			&i.PeerID,
			&i.ChangedAt,
			&i.HasDraft,
			&i.Message,
			&i.NoWebpage,
			&i.ReplyToMsgID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cloudDraftStateForPeer = `-- name: CloudDraftStateForPeer :one
SELECT changed.peer_type,
       changed.peer_id,
       changed.changed_at,
       (draft.owner_id IS NOT NULL) AS has_draft,
       COALESCE(draft.message, '') AS message,
       COALESCE(draft.no_webpage, false) AS no_webpage,
       CASE
           WHEN draft.reply_to_msg_id IS NULL THEN 0::bigint
           WHEN draft.peer_type = 3 AND EXISTS (
               SELECT 1 FROM channel_messages AS target
               WHERE target.channel_id = draft.peer_id
                 AND target.local_id = draft.reply_to_msg_id
                 AND target.deleted = false
                 AND target.action_type = 0
           ) THEN draft.reply_to_msg_id
           WHEN draft.peer_type <> 3 AND EXISTS (
               SELECT 1 FROM messages AS target
               WHERE target.owner_id = draft.owner_id
                 AND target.peer_type = draft.peer_type
                 AND target.peer_id = draft.peer_id
                 AND target.local_id = draft.reply_to_msg_id
                 AND target.deleted = false
                 AND target.action_type = 0
           ) THEN draft.reply_to_msg_id
           ELSE 0::bigint
       END AS reply_to_msg_id,
       COALESCE(draft.updated_at, changed.changed_at) AS updated_at
FROM cloud_draft_sync AS changed
LEFT JOIN cloud_drafts AS draft
  ON draft.owner_id = changed.owner_id
 AND draft.peer_type = changed.peer_type
 AND draft.peer_id = changed.peer_id
WHERE changed.owner_id = $1
  AND changed.peer_type = $2
  AND changed.peer_id = $3
  AND (
      (changed.peer_type = 1 AND EXISTS (
          SELECT 1 FROM dialogs AS dialog
          WHERE dialog.owner_id = changed.owner_id
            AND dialog.peer_type = changed.peer_type
            AND dialog.peer_id = changed.peer_id
      ))
      OR (changed.peer_type = 2 AND EXISTS (
          SELECT 1 FROM chat_participants AS participant
          WHERE participant.chat_id = changed.peer_id AND participant.user_id = changed.owner_id
      ))
      OR (changed.peer_type = 3 AND EXISTS (
          SELECT 1 FROM channel_participants AS participant
          WHERE participant.channel_id = changed.peer_id
            AND participant.user_id = changed.owner_id
            AND (participant.banned_until IS NULL OR participant.banned_until <= now())
      ))
  )
`

type CloudDraftStateForPeerParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
}

type CloudDraftStateForPeerRow struct {
	PeerType     int16
	PeerID       int64
	ChangedAt    pgtype.Timestamptz
	HasDraft     interface{}
	Message      string
	NoWebpage    bool
	ReplyToMsgID int64
	UpdatedAt    pgtype.Timestamptz
}

// CloudDraftStateForPeer delivers the latest owner-visible value or clear
// tombstone after a peer-free NOTIFY. Access is checked with the same statement
// as the state read so a removal that committed first suppresses delivery.
func (q *Queries) CloudDraftStateForPeer(ctx context.Context, arg CloudDraftStateForPeerParams) (CloudDraftStateForPeerRow, error) {
	row := q.db.QueryRow(ctx, cloudDraftStateForPeer, arg.OwnerID, arg.PeerType, arg.PeerID)
	var i CloudDraftStateForPeerRow
	err := row.Scan(
		&i.PeerType,
		&i.PeerID,
		&i.ChangedAt,
		&i.HasDraft,
		&i.Message,
		&i.NoWebpage,
		&i.ReplyToMsgID,
		&i.UpdatedAt,
	)
	return i, err
}

const cloudDraftTimestamp = `-- name: CloudDraftTimestamp :one
SELECT clock_timestamp()::timestamptz AS updated_at
`

func (q *Queries) CloudDraftTimestamp(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, cloudDraftTimestamp)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}

const cloudDraftUserDialogExists = `-- name: CloudDraftUserDialogExists :one
SELECT EXISTS (
    SELECT 1 FROM dialogs
    WHERE owner_id = $1 AND peer_type = 1 AND peer_id = $2
)
`

type CloudDraftUserDialogExistsParams struct {
	OwnerID int64
	PeerID  int64
}

func (q *Queries) CloudDraftUserDialogExists(ctx context.Context, arg CloudDraftUserDialogExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, cloudDraftUserDialogExists, arg.OwnerID, arg.PeerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const cloudDraftsForPeers = `-- name: CloudDraftsForPeers :many
WITH selected AS (
    SELECT peer_types.peer_type, peer_ids.peer_id
    FROM unnest($2::smallint[]) WITH ORDINALITY AS peer_types(peer_type, ord)
    JOIN unnest($3::bigint[]) WITH ORDINALITY AS peer_ids(peer_id, ord) USING (ord)
)
SELECT draft.peer_type,
       draft.peer_id,
       draft.message,
       draft.no_webpage,
       CASE
           WHEN draft.reply_to_msg_id IS NULL THEN 0::bigint
           WHEN draft.peer_type = 3 AND EXISTS (
               SELECT 1 FROM channel_messages AS target
               WHERE target.channel_id = draft.peer_id
                 AND target.local_id = draft.reply_to_msg_id
                 AND target.deleted = false
                 AND target.action_type = 0
           ) THEN draft.reply_to_msg_id
           WHEN draft.peer_type <> 3 AND EXISTS (
               SELECT 1 FROM messages AS target
               WHERE target.owner_id = draft.owner_id
                 AND target.peer_type = draft.peer_type
                 AND target.peer_id = draft.peer_id
                 AND target.local_id = draft.reply_to_msg_id
                 AND target.deleted = false
                 AND target.action_type = 0
           ) THEN draft.reply_to_msg_id
           ELSE 0::bigint
       END AS reply_to_msg_id,
       draft.updated_at
FROM cloud_drafts AS draft
JOIN selected
  ON selected.peer_type = draft.peer_type AND selected.peer_id = draft.peer_id
WHERE draft.owner_id = $1
  AND (
      (draft.peer_type = 1 AND EXISTS (
          SELECT 1 FROM dialogs AS dialog
          WHERE dialog.owner_id = draft.owner_id
            AND dialog.peer_type = draft.peer_type
            AND dialog.peer_id = draft.peer_id
      ))
      OR (draft.peer_type = 2 AND EXISTS (
          SELECT 1 FROM chat_participants AS participant
          WHERE participant.chat_id = draft.peer_id AND participant.user_id = draft.owner_id
      ))
      OR (draft.peer_type = 3 AND EXISTS (
          SELECT 1 FROM channel_participants AS participant
          WHERE participant.channel_id = draft.peer_id
            AND participant.user_id = draft.owner_id
            AND (participant.banned_until IS NULL OR participant.banned_until <= now())
      ))
  )
ORDER BY draft.peer_type, draft.peer_id
`

type CloudDraftsForPeersParams struct {
	OwnerID   int64
	PeerTypes []int16
	PeerIds   []int64
}

type CloudDraftsForPeersRow struct {
	PeerType     int16
	PeerID       int64
	Message      string
	NoWebpage    bool
	ReplyToMsgID int64
	UpdatedAt    pgtype.Timestamptz
}

// CloudDraftsForPeers hydrates only the selected current dialogs, and rechecks
// current group/channel membership in the same query that reads the private
// text. A removed member's retained dialogs row cannot expose its draft.
func (q *Queries) CloudDraftsForPeers(ctx context.Context, arg CloudDraftsForPeersParams) ([]CloudDraftsForPeersRow, error) {
	rows, err := q.db.Query(ctx, cloudDraftsForPeers, arg.OwnerID, arg.PeerTypes, arg.PeerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CloudDraftsForPeersRow
	for rows.Next() {
		var i CloudDraftsForPeersRow
		if err := rows.Scan(
			&i.PeerType,
			&i.PeerID,
			&i.Message,
			&i.NoWebpage,
			&i.ReplyToMsgID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCloudDraft = `-- name: DeleteCloudDraft :execrows
DELETE FROM cloud_drafts
WHERE owner_id = $1 AND peer_type = $2 AND peer_id = $3
`

type DeleteCloudDraftParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
}

func (q *Queries) DeleteCloudDraft(ctx context.Context, arg DeleteCloudDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCloudDraft, arg.OwnerID, arg.PeerType, arg.PeerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCloudDraftChanged = `-- name: MarkCloudDraftChanged :exec
INSERT INTO cloud_draft_sync (owner_id, peer_type, peer_id, changed_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_id, peer_type, peer_id) DO UPDATE
SET changed_at = EXCLUDED.changed_at
`

type MarkCloudDraftChangedParams struct {
	OwnerID   int64
	PeerType  int16
	PeerID    int64
	ChangedAt pgtype.Timestamptz
}

func (q *Queries) MarkCloudDraftChanged(ctx context.Context, arg MarkCloudDraftChangedParams) error {
	_, err := q.db.Exec(ctx, markCloudDraftChanged,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.ChangedAt,
	)
	return err
}

const upsertCloudDraft = `-- name: UpsertCloudDraft :exec
INSERT INTO cloud_drafts (owner_id, peer_type, peer_id, message, no_webpage, reply_to_msg_id, updated_at)
VALUES ($1, $2, $3, $4, $5, NULLIF($6, 0), $7)
ON CONFLICT (owner_id, peer_type, peer_id) DO UPDATE SET
    message = EXCLUDED.message,
    no_webpage = EXCLUDED.no_webpage,
    reply_to_msg_id = EXCLUDED.reply_to_msg_id,
    updated_at = EXCLUDED.updated_at
`

type UpsertCloudDraftParams struct {
	OwnerID   int64
	PeerType  int16
	PeerID    int64
	Message   string
	NoWebpage bool
	Column6   interface{}
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertCloudDraft(ctx context.Context, arg UpsertCloudDraftParams) error {
	_, err := q.db.Exec(ctx, upsertCloudDraft,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.Message,
		arg.NoWebpage,
		arg.Column6,
		arg.UpdatedAt,
	)
	return err
}
