// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dialog_unread_marks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dialogUnreadMarkChangesForOwnerSince = `-- name: DialogUnreadMarkChangesForOwnerSince :many
SELECT mark.peer_type, mark.peer_id, mark.unread, mark.changed_at
FROM user_dialog_unread_marks AS mark
WHERE mark.owner_id = $1
  AND mark.changed_at >= $2
  AND (
      (mark.peer_type = 1 AND EXISTS (
          SELECT 1 FROM dialogs AS dialog
          WHERE dialog.owner_id = mark.owner_id
            AND dialog.peer_type = mark.peer_type
            AND dialog.peer_id = mark.peer_id
      ))
      OR (mark.peer_type = 2 AND EXISTS (
          SELECT 1 FROM chat_participants AS participant
          WHERE participant.chat_id = mark.peer_id AND participant.user_id = mark.owner_id
      ))
      OR (mark.peer_type = 3 AND EXISTS (
          SELECT 1 FROM channel_participants AS participant
          WHERE participant.channel_id = mark.peer_id
            AND participant.user_id = mark.owner_id
            AND (participant.banned_until IS NULL OR participant.banned_until <= now())
      ))
  )
ORDER BY mark.changed_at, mark.peer_type, mark.peer_id
LIMIT 501
`

type DialogUnreadMarkChangesForOwnerSinceParams struct {
	OwnerID      int64
	ChangedSince pgtype.Timestamptz
}

type DialogUnreadMarkChangesForOwnerSinceRow struct {
	PeerType  int16
	PeerID    int64
	Unread    bool
	ChangedAt pgtype.Timestamptz
}

// DialogUnreadMarkChangesForOwnerSince is the separate guarded non-PTS recovery
// stream. The extra row detects truncation; current visibility is rechecked and
// false rows are retained to recover unmark transitions.
func (q *Queries) DialogUnreadMarkChangesForOwnerSince(ctx context.Context, arg DialogUnreadMarkChangesForOwnerSinceParams) ([]DialogUnreadMarkChangesForOwnerSinceRow, error) {
	rows, err := q.db.Query(ctx, dialogUnreadMarkChangesForOwnerSince, arg.OwnerID, arg.ChangedSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DialogUnreadMarkChangesForOwnerSinceRow
	for rows.Next() {
		var i DialogUnreadMarkChangesForOwnerSinceRow
		if err := rows.Scan(
			&i.PeerType,
			&i.PeerID,
			&i.Unread,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dialogUnreadMarkChannelMember = `-- name: DialogUnreadMarkChannelMember :one
SELECT EXISTS (
    SELECT 1 FROM channel_participants
    WHERE channel_id = $1 AND user_id = $2
      AND (banned_until IS NULL OR banned_until <= now())
)
`

type DialogUnreadMarkChannelMemberParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) DialogUnreadMarkChannelMember(ctx context.Context, arg DialogUnreadMarkChannelMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, dialogUnreadMarkChannelMember, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const dialogUnreadMarkChatMember = `-- name: DialogUnreadMarkChatMember :one
SELECT EXISTS (
    SELECT 1 FROM chat_participants
    WHERE chat_id = $1 AND user_id = $2
)
`

type DialogUnreadMarkChatMemberParams struct {
	ChatID int64
	UserID int64
}

func (q *Queries) DialogUnreadMarkChatMember(ctx context.Context, arg DialogUnreadMarkChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, dialogUnreadMarkChatMember, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const dialogUnreadMarkCurrent = `-- name: DialogUnreadMarkCurrent :one
SELECT unread, changed_at
FROM user_dialog_unread_marks
WHERE owner_id = $1 AND peer_type = $2 AND peer_id = $3
`

type DialogUnreadMarkCurrentParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
}

type DialogUnreadMarkCurrentRow struct {
	Unread    bool
	ChangedAt pgtype.Timestamptz
}

func (q *Queries) DialogUnreadMarkCurrent(ctx context.Context, arg DialogUnreadMarkCurrentParams) (DialogUnreadMarkCurrentRow, error) {
	row := q.db.QueryRow(ctx, dialogUnreadMarkCurrent, arg.OwnerID, arg.PeerType, arg.PeerID)
	var i DialogUnreadMarkCurrentRow
	err := row.Scan(&i.Unread, &i.ChangedAt)
	return i, err
}

const dialogUnreadMarkStateForPeer = `-- name: DialogUnreadMarkStateForPeer :one
SELECT mark.peer_type, mark.peer_id, mark.unread, mark.changed_at
FROM user_dialog_unread_marks AS mark
WHERE mark.owner_id = $1
  AND mark.peer_type = $2
  AND mark.peer_id = $3
  AND (
      (mark.peer_type = 1 AND EXISTS (
          SELECT 1 FROM dialogs AS dialog
          WHERE dialog.owner_id = mark.owner_id
            AND dialog.peer_type = mark.peer_type
            AND dialog.peer_id = mark.peer_id
      ))
      OR (mark.peer_type = 2 AND EXISTS (
          SELECT 1 FROM chat_participants AS participant
          WHERE participant.chat_id = mark.peer_id AND participant.user_id = mark.owner_id
      ))
      OR (mark.peer_type = 3 AND EXISTS (
          SELECT 1 FROM channel_participants AS participant
          WHERE participant.channel_id = mark.peer_id
            AND participant.user_id = mark.owner_id
            AND (participant.banned_until IS NULL OR participant.banned_until <= now())
      ))
  )
`

type DialogUnreadMarkStateForPeerParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
}

type DialogUnreadMarkStateForPeerRow struct {
	PeerType  int16
	PeerID    int64
	Unread    bool
	ChangedAt pgtype.Timestamptz
}

// DialogUnreadMarkStateForPeer rechecks visibility in the same statement as
// the current value read so stale NOTIFY payloads cannot reveal a removed peer.
func (q *Queries) DialogUnreadMarkStateForPeer(ctx context.Context, arg DialogUnreadMarkStateForPeerParams) (DialogUnreadMarkStateForPeerRow, error) {
	row := q.db.QueryRow(ctx, dialogUnreadMarkStateForPeer, arg.OwnerID, arg.PeerType, arg.PeerID)
	var i DialogUnreadMarkStateForPeerRow
	err := row.Scan(
		&i.PeerType,
		&i.PeerID,
		&i.Unread,
		&i.ChangedAt,
	)
	return i, err
}

const dialogUnreadMarkTimestamp = `-- name: DialogUnreadMarkTimestamp :one
SELECT now()::timestamptz AS changed_at
`

func (q *Queries) DialogUnreadMarkTimestamp(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, dialogUnreadMarkTimestamp)
	var changed_at pgtype.Timestamptz
	err := row.Scan(&changed_at)
	return changed_at, err
}

const dialogUnreadMarkUserDialogExists = `-- name: DialogUnreadMarkUserDialogExists :one
SELECT EXISTS (
    SELECT 1 FROM dialogs
    WHERE owner_id = $1 AND peer_type = 1 AND peer_id = $2
)
`

type DialogUnreadMarkUserDialogExistsParams struct {
	OwnerID int64
	PeerID  int64
}

func (q *Queries) DialogUnreadMarkUserDialogExists(ctx context.Context, arg DialogUnreadMarkUserDialogExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, dialogUnreadMarkUserDialogExists, arg.OwnerID, arg.PeerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const dialogUnreadMarksForPeers = `-- name: DialogUnreadMarksForPeers :many
WITH selected AS (
    SELECT peer_types.peer_type, peer_ids.peer_id
    FROM unnest($2::smallint[]) WITH ORDINALITY AS peer_types(peer_type, ord)
    JOIN unnest($3::bigint[]) WITH ORDINALITY AS peer_ids(peer_id, ord) USING (ord)
)
SELECT mark.peer_type, mark.peer_id
FROM user_dialog_unread_marks AS mark
JOIN selected
  ON selected.peer_type = mark.peer_type AND selected.peer_id = mark.peer_id
WHERE mark.owner_id = $1
  AND mark.unread = true
  AND (
      (mark.peer_type = 1 AND EXISTS (
          SELECT 1 FROM dialogs AS dialog
          WHERE dialog.owner_id = mark.owner_id
            AND dialog.peer_type = mark.peer_type
            AND dialog.peer_id = mark.peer_id
      ))
      OR (mark.peer_type = 2 AND EXISTS (
          SELECT 1 FROM chat_participants AS participant
          WHERE participant.chat_id = mark.peer_id AND participant.user_id = mark.owner_id
      ))
      OR (mark.peer_type = 3 AND EXISTS (
          SELECT 1 FROM channel_participants AS participant
          WHERE participant.channel_id = mark.peer_id
            AND participant.user_id = mark.owner_id
            AND (participant.banned_until IS NULL OR participant.banned_until <= now())
      ))
  )
ORDER BY mark.peer_type, mark.peer_id
`

type DialogUnreadMarksForPeersParams struct {
	OwnerID   int64
	PeerTypes []int16
	PeerIds   []int64
}

type DialogUnreadMarksForPeersRow struct {
	PeerType int16
	PeerID   int64
}

// DialogUnreadMarksForPeers reads only currently visible, marked dialogs.
// Removed or banned group/channel members cannot hydrate stale private marks.
func (q *Queries) DialogUnreadMarksForPeers(ctx context.Context, arg DialogUnreadMarksForPeersParams) ([]DialogUnreadMarksForPeersRow, error) {
	rows, err := q.db.Query(ctx, dialogUnreadMarksForPeers, arg.OwnerID, arg.PeerTypes, arg.PeerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DialogUnreadMarksForPeersRow
	for rows.Next() {
		var i DialogUnreadMarksForPeersRow
		if err := rows.Scan(&i.PeerType, &i.PeerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyDialogUnreadMark = `-- name: NotifyDialogUnreadMark :exec
SELECT pg_notify('tg_updates', $1)
`

func (q *Queries) NotifyDialogUnreadMark(ctx context.Context, pgNotify string) error {
	_, err := q.db.Exec(ctx, notifyDialogUnreadMark, pgNotify)
	return err
}

const upsertDialogUnreadMark = `-- name: UpsertDialogUnreadMark :exec
INSERT INTO user_dialog_unread_marks (owner_id, peer_type, peer_id, unread, changed_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (owner_id, peer_type, peer_id) DO UPDATE
SET unread = EXCLUDED.unread,
    changed_at = EXCLUDED.changed_at
`

type UpsertDialogUnreadMarkParams struct {
	OwnerID   int64
	PeerType  int16
	PeerID    int64
	Unread    bool
	ChangedAt pgtype.Timestamptz
}

func (q *Queries) UpsertDialogUnreadMark(ctx context.Context, arg UpsertDialogUnreadMarkParams) error {
	_, err := q.db.Exec(ctx, upsertDialogUnreadMark,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.Unread,
		arg.ChangedAt,
	)
	return err
}
