// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dialog_pins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDialogPinsForOwner = `-- name: DeleteDialogPinsForOwner :exec
DELETE FROM user_dialog_pins
WHERE owner_id = $1 AND peer_type <> 0
`

func (q *Queries) DeleteDialogPinsForOwner(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, deleteDialogPinsForOwner, ownerID)
	return err
}

const deleteEmptySelfDialogForOwner = `-- name: DeleteEmptySelfDialogForOwner :exec
DELETE FROM dialogs
WHERE owner_id = $1 AND peer_type = 1 AND peer_id = $1 AND top_message = 0
`

// DeleteEmptySelfDialogForOwner removes only the synthetic Saved Messages row
// after its final pin is removed; a real conversation remains untouched.
func (q *Queries) DeleteEmptySelfDialogForOwner(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, deleteEmptySelfDialogForOwner, ownerID)
	return err
}

const dialogPinChangeAt = `-- name: DialogPinChangeAt :one
SELECT changed_at
FROM user_dialog_pins
WHERE owner_id = $1 AND peer_type = 0 AND peer_id = 0
`

func (q *Queries) DialogPinChangeAt(ctx context.Context, ownerID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, dialogPinChangeAt, ownerID)
	var changed_at pgtype.Timestamptz
	err := row.Scan(&changed_at)
	return changed_at, err
}

const dialogPinDialogsForOwner = `-- name: DialogPinDialogsForOwner :many
SELECT peer_type, peer_id
FROM dialogs
WHERE owner_id = $1
  AND peer_type = ANY($2::smallint[])
  AND peer_id = ANY($3::bigint[])
`

type DialogPinDialogsForOwnerParams struct {
	OwnerID   int64
	PeerTypes []int16
	PeerIds   []int64
}

type DialogPinDialogsForOwnerRow struct {
	PeerType int16
	PeerID   int64
}

func (q *Queries) DialogPinDialogsForOwner(ctx context.Context, arg DialogPinDialogsForOwnerParams) ([]DialogPinDialogsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, dialogPinDialogsForOwner, arg.OwnerID, arg.PeerTypes, arg.PeerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DialogPinDialogsForOwnerRow
	for rows.Next() {
		var i DialogPinDialogsForOwnerRow
		if err := rows.Scan(&i.PeerType, &i.PeerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureSelfDialogForOwner = `-- name: EnsureSelfDialogForOwner :exec
INSERT INTO dialogs (owner_id, peer_type, peer_id, top_message, unread_count)
VALUES ($1, 1, $1, 0, 0)
ON CONFLICT (owner_id, peer_type, peer_id) DO NOTHING
`

// EnsureSelfDialogForOwner creates the empty Saved Messages dialog on its
// first pin without advancing message pts.
func (q *Queries) EnsureSelfDialogForOwner(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, ensureSelfDialogForOwner, ownerID)
	return err
}

const insertDialogPin = `-- name: InsertDialogPin :exec
INSERT INTO user_dialog_pins (owner_id, peer_type, peer_id, position)
VALUES ($1, $2, $3, $4)
`

type InsertDialogPinParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
	Position *int16
}

func (q *Queries) InsertDialogPin(ctx context.Context, arg InsertDialogPinParams) error {
	_, err := q.db.Exec(ctx, insertDialogPin,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.Position,
	)
	return err
}

const listDialogPins = `-- name: ListDialogPins :many
SELECT owner_id, peer_type, peer_id, position
FROM user_dialog_pins
WHERE owner_id = $1 AND peer_type <> 0
ORDER BY position
`

type ListDialogPinsRow struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
	Position *int16
}

func (q *Queries) ListDialogPins(ctx context.Context, ownerID int64) ([]ListDialogPinsRow, error) {
	rows, err := q.db.Query(ctx, listDialogPins, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDialogPinsRow
	for rows.Next() {
		var i ListDialogPinsRow
		if err := rows.Scan(
			&i.OwnerID,
			&i.PeerType,
			&i.PeerID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDialogPinsChanged = `-- name: MarkDialogPinsChanged :exec
INSERT INTO user_dialog_pins (owner_id, peer_type, peer_id, position, changed_at)
VALUES ($1, 0, 0, NULL, clock_timestamp())
ON CONFLICT (owner_id, peer_type, peer_id)
DO UPDATE SET changed_at = clock_timestamp()
`

func (q *Queries) MarkDialogPinsChanged(ctx context.Context, ownerID int64) error {
	_, err := q.db.Exec(ctx, markDialogPinsChanged, ownerID)
	return err
}

const notifyDialogPinMutation = `-- name: NotifyDialogPinMutation :exec
SELECT pg_notify('tg_dialog_pins', $1)
`

func (q *Queries) NotifyDialogPinMutation(ctx context.Context, pgNotify string) error {
	_, err := q.db.Exec(ctx, notifyDialogPinMutation, pgNotify)
	return err
}
