// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dialogs.sql

package db

import (
	"context"
)

const advanceChatReadInbox = `-- name: AdvanceChatReadInbox :one
UPDATE dialogs SET
  read_inbox_max_id = GREATEST(read_inbox_max_id, $1::bigint),
  unread_count = (
    SELECT count(*) FROM messages m
    WHERE m.owner_id = dialogs.owner_id AND m.peer_type = dialogs.peer_type AND m.peer_id = dialogs.peer_id
      AND m.out = false AND m.deleted = false
      AND m.local_id > GREATEST(dialogs.read_inbox_max_id, $1::bigint)
  )::int
WHERE owner_id = $2::bigint AND peer_type = $3::smallint
  AND peer_id = $4::bigint
RETURNING read_inbox_max_id, unread_count
`

type AdvanceChatReadInboxParams struct {
	MaxID    int64
	OwnerID  int64
	PeerType int16
	PeerID   int64
}

type AdvanceChatReadInboxRow struct {
	ReadInboxMaxID int64
	UnreadCount    int32
}

// AdvanceChatReadInbox leaves the chat's outbox marker alone even when its id
// numerically equals the reader's user id.
func (q *Queries) AdvanceChatReadInbox(ctx context.Context, arg AdvanceChatReadInboxParams) (AdvanceChatReadInboxRow, error) {
	row := q.db.QueryRow(ctx, advanceChatReadInbox,
		arg.MaxID,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
	)
	var i AdvanceChatReadInboxRow
	err := row.Scan(&i.ReadInboxMaxID, &i.UnreadCount)
	return i, err
}

const advanceReadInbox = `-- name: AdvanceReadInbox :one
UPDATE dialogs SET
  read_inbox_max_id = GREATEST(read_inbox_max_id, $1::bigint),
  read_outbox_max_id = CASE
    WHEN dialogs.owner_id = dialogs.peer_id
      THEN GREATEST(dialogs.read_outbox_max_id, $1::bigint)
    ELSE dialogs.read_outbox_max_id
  END,
  unread_count = (
    SELECT count(*) FROM messages m
    WHERE m.owner_id = dialogs.owner_id AND m.peer_type = dialogs.peer_type AND m.peer_id = dialogs.peer_id
      AND m.out = false AND m.deleted = false
      AND m.local_id > GREATEST(dialogs.read_inbox_max_id, $1::bigint)
  )::int
WHERE owner_id = $2::bigint AND peer_type = $3::smallint
  AND peer_id = $4::bigint
RETURNING read_inbox_max_id, unread_count
`

type AdvanceReadInboxParams struct {
	MaxID    int64
	OwnerID  int64
	PeerType int16
	PeerID   int64
}

type AdvanceReadInboxRow struct {
	ReadInboxMaxID int64
	UnreadCount    int32
}

// AdvanceReadInbox raises the reader's read_inbox_max_id monotonically and
// recomputes unread as the count of still-unread inbound messages above it.
func (q *Queries) AdvanceReadInbox(ctx context.Context, arg AdvanceReadInboxParams) (AdvanceReadInboxRow, error) {
	row := q.db.QueryRow(ctx, advanceReadInbox,
		arg.MaxID,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
	)
	var i AdvanceReadInboxRow
	err := row.Scan(&i.ReadInboxMaxID, &i.UnreadCount)
	return i, err
}

const advanceReadOutbox = `-- name: AdvanceReadOutbox :execrows
UPDATE dialogs SET read_outbox_max_id = GREATEST(read_outbox_max_id, $4)
WHERE owner_id = $1 AND peer_type = $2 AND peer_id = $3
`

type AdvanceReadOutboxParams struct {
	OwnerID         int64
	PeerType        int16
	PeerID          int64
	ReadOutboxMaxID int64
}

// AdvanceReadOutbox raises the peer's read_outbox_max_id monotonically.
func (q *Queries) AdvanceReadOutbox(ctx context.Context, arg AdvanceReadOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceReadOutbox,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.ReadOutboxMaxID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const captureChatReadReceipts = `-- name: CaptureChatReadReceipts :execrows
INSERT INTO chat_read_receipts (chat_id, fanout_id, reader_id, sent_at)
SELECT $1::bigint, m.fanout_id, $2::bigint, m.date
FROM messages AS m
WHERE m.owner_id = $2::bigint
  AND m.peer_type = $3::smallint
  AND m.peer_id = $1::bigint
  AND m.out = false AND m.deleted = false AND m.fanout_id <> 0
  AND m.local_id > $4::bigint
  AND m.local_id <= $5::bigint
  AND m.from_id = ANY($6::bigint[])
  AND m.date > statement_timestamp() - interval '604800 seconds'
  AND EXISTS (
      SELECT 1 FROM messages AS sender
      WHERE sender.owner_id = m.from_id
        AND sender.fanout_id = m.fanout_id
        AND sender.out = true
        AND sender.peer_type = m.peer_type
        AND sender.peer_id = m.peer_id
  )
ON CONFLICT (chat_id, fanout_id, reader_id) DO NOTHING
`

type CaptureChatReadReceiptsParams struct {
	PeerID    int64
	OwnerID   int64
	PeerType  int16
	AfterID   int64
	MaxID     int64
	MemberIds []int64
}

// CaptureChatReadReceipts records one immutable first-read date for each live
// inbound copy newly covered by this authorized read advance. The message date
// is retained separately for the seven-day send-age window and cleanup.
func (q *Queries) CaptureChatReadReceipts(ctx context.Context, arg CaptureChatReadReceiptsParams) (int64, error) {
	result, err := q.db.Exec(ctx, captureChatReadReceipts,
		arg.PeerID,
		arg.OwnerID,
		arg.PeerType,
		arg.AfterID,
		arg.MaxID,
		arg.MemberIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const chatReadReceiptTargets = `-- name: ChatReadReceiptTargets :many
WITH covered AS (
    SELECT DISTINCT m.from_id, m.fanout_id
    FROM messages AS m
    WHERE m.owner_id = $3::bigint
      AND m.peer_type = $1::smallint
      AND m.peer_id = $2::bigint
      AND m.out = false AND m.deleted = false AND m.fanout_id <> 0
      AND m.local_id > $4::bigint
      AND m.local_id <= $5::bigint
      AND m.from_id = ANY($6::bigint[])
)
SELECT covered.from_id AS sender_id, MAX(sender.local_id)::bigint AS max_id
FROM covered
JOIN messages AS sender
  ON sender.owner_id = covered.from_id
 AND sender.fanout_id = covered.fanout_id
 AND sender.fanout_id <> 0
 AND sender.out = true
 AND sender.peer_type = $1::smallint
 AND sender.peer_id = $2::bigint
GROUP BY covered.from_id
ORDER BY covered.from_id
`

type ChatReadReceiptTargetsParams struct {
	PeerType  int16
	PeerID    int64
	OwnerID   int64
	AfterID   int64
	MaxID     int64
	MemberIds []int64
}

type ChatReadReceiptTargetsRow struct {
	SenderID int64
	MaxID    int64
}

// ChatReadReceiptTargets maps covered inbound chat copies to each current
// sender's own outbound message-id space. The current participant list is
// supplied only after its owners have been locked and rechecked.
func (q *Queries) ChatReadReceiptTargets(ctx context.Context, arg ChatReadReceiptTargetsParams) ([]ChatReadReceiptTargetsRow, error) {
	rows, err := q.db.Query(ctx, chatReadReceiptTargets,
		arg.PeerType,
		arg.PeerID,
		arg.OwnerID,
		arg.AfterID,
		arg.MaxID,
		arg.MemberIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatReadReceiptTargetsRow
	for rows.Next() {
		var i ChatReadReceiptTargetsRow
		if err := rows.Scan(&i.SenderID, &i.MaxID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDialogsExcludingPinned = `-- name: CountDialogsExcludingPinned :one
SELECT count(*)::int
FROM dialogs d
WHERE d.owner_id = $1
  AND NOT (
        EXISTS (
            SELECT 1 FROM user_dialog_pins p
            WHERE p.owner_id = d.owner_id AND p.peer_type = d.peer_type
              AND p.peer_id = d.peer_id AND p.position IS NOT NULL
        ) AND (d.peer_type <> 2 OR EXISTS (
            SELECT 1 FROM chat_participants cp
            WHERE cp.chat_id = d.peer_id AND cp.user_id = d.owner_id
        ))
  )
`

// CountDialogsExcludingPinned is the unpaged count for the same active-pin
// predicate as DialogsForOwnerWithPins.
func (q *Queries) CountDialogsExcludingPinned(ctx context.Context, ownerID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countDialogsExcludingPinned, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countDialogsForOwner = `-- name: CountDialogsForOwner :one
SELECT count(*)::int FROM dialogs WHERE owner_id = $1
`

// CountDialogsForOwner is the total the truncated reply advertises, so a client
// knows more pages exist. Unfiltered by offset on purpose: it is the size of the
// whole list, not of the remainder.
func (q *Queries) CountDialogsForOwner(ctx context.Context, ownerID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countDialogsForOwner, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExpiredChatReadReceipts = `-- name: DeleteExpiredChatReadReceipts :execrows
WITH expired AS (
    SELECT chat_id, fanout_id, reader_id
    FROM chat_read_receipts
    WHERE sent_at <= statement_timestamp() - interval '604800 seconds'
    ORDER BY sent_at, chat_id, fanout_id, reader_id
    LIMIT $1::int
    FOR UPDATE SKIP LOCKED
)
DELETE FROM chat_read_receipts AS receipt
USING expired
WHERE receipt.chat_id = expired.chat_id
  AND receipt.fanout_id = expired.fanout_id
  AND receipt.reader_id = expired.reader_id
`

// DeleteExpiredChatReadReceipts retires one bounded batch. The caller repeats
// passes until the expired backlog is drained; every pass uses the database
// clock and measures retention from the original message send date.
func (q *Queries) DeleteExpiredChatReadReceipts(ctx context.Context, lim int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChatReadReceipts, lim)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dialogsForOwner = `-- name: DialogsForOwner :many
SELECT owner_id, peer_id, top_message, unread_count, read_inbox_max_id, read_outbox_max_id, peer_type FROM dialogs
WHERE owner_id = $1
  AND ($2::bigint = 0 OR top_message < $2::bigint)
ORDER BY top_message DESC
LIMIT $3::int
`

type DialogsForOwnerParams struct {
	OwnerID  int64
	OffsetID int64
	Lim      int32
}

func (q *Queries) DialogsForOwner(ctx context.Context, arg DialogsForOwnerParams) ([]Dialog, error) {
	rows, err := q.db.Query(ctx, dialogsForOwner, arg.OwnerID, arg.OffsetID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dialog
	for rows.Next() {
		var i Dialog
		if err := rows.Scan(
			&i.OwnerID,
			&i.PeerID,
			&i.TopMessage,
			&i.UnreadCount,
			&i.ReadInboxMaxID,
			&i.ReadOutboxMaxID,
			&i.PeerType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dialogsForOwnerWithPins = `-- name: DialogsForOwnerWithPins :many
SELECT d.owner_id, d.peer_id, d.top_message, d.unread_count,
       d.read_inbox_max_id, d.read_outbox_max_id, d.peer_type,
       (EXISTS (
            SELECT 1 FROM user_dialog_pins p
            WHERE p.owner_id = d.owner_id AND p.peer_type = d.peer_type
              AND p.peer_id = d.peer_id AND p.position IS NOT NULL
        ) AND (d.peer_type <> 2 OR EXISTS (
            SELECT 1 FROM chat_participants cp
            WHERE cp.chat_id = d.peer_id AND cp.user_id = d.owner_id
        ))) AS pinned
FROM dialogs d
WHERE d.owner_id = $1
  AND ($2::bigint = 0 OR d.top_message < $2::bigint)
  AND (NOT $3::boolean OR NOT (
        EXISTS (
            SELECT 1 FROM user_dialog_pins p
            WHERE p.owner_id = d.owner_id AND p.peer_type = d.peer_type
              AND p.peer_id = d.peer_id AND p.position IS NOT NULL
        ) AND (d.peer_type <> 2 OR EXISTS (
            SELECT 1 FROM chat_participants cp
            WHERE cp.chat_id = d.peer_id AND cp.user_id = d.owner_id
        ))
  ))
ORDER BY d.top_message DESC
LIMIT $4::int
`

type DialogsForOwnerWithPinsParams struct {
	OwnerID       int64
	OffsetID      int64
	ExcludePinned bool
	Lim           int32
}

type DialogsForOwnerWithPinsRow struct {
	OwnerID         int64
	PeerID          int64
	TopMessage      int64
	UnreadCount     int32
	ReadInboxMaxID  int64
	ReadOutboxMaxID int64
	PeerType        int16
	Pinned          *bool
}

// DialogsForOwnerWithPins preserves the ordinary top-message page cursor while
// marking only currently visible pins. Removed group members keep their dialog
// row, but their stale pin neither hides the row nor remains client-visible.
func (q *Queries) DialogsForOwnerWithPins(ctx context.Context, arg DialogsForOwnerWithPinsParams) ([]DialogsForOwnerWithPinsRow, error) {
	rows, err := q.db.Query(ctx, dialogsForOwnerWithPins,
		arg.OwnerID,
		arg.OffsetID,
		arg.ExcludePinned,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DialogsForOwnerWithPinsRow
	for rows.Next() {
		var i DialogsForOwnerWithPinsRow
		if err := rows.Scan(
			&i.OwnerID,
			&i.PeerID,
			&i.TopMessage,
			&i.UnreadCount,
			&i.ReadInboxMaxID,
			&i.ReadOutboxMaxID,
			&i.PeerType,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxChatReadMessageID = `-- name: MaxChatReadMessageID :one
SELECT COALESCE(MAX(local_id), 0)::bigint AS max_id
FROM messages
WHERE owner_id = $1 AND peer_type = $2 AND peer_id = $3
  AND deleted = false AND local_id <= $4
`

type MaxChatReadMessageIDParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
	LocalID  int64
}

func (q *Queries) MaxChatReadMessageID(ctx context.Context, arg MaxChatReadMessageIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, maxChatReadMessageID,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.LocalID,
	)
	var max_id int64
	err := row.Scan(&max_id)
	return max_id, err
}

const peerDialogExists = `-- name: PeerDialogExists :one
SELECT EXISTS (
    SELECT 1 FROM dialogs
    WHERE owner_id = $1 AND peer_type = $2 AND peer_id = $3
)
`

type PeerDialogExistsParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
}

// PeerDialogExists is the caller-owned 1:1 dialog predicate for peer settings.
func (q *Queries) PeerDialogExists(ctx context.Context, arg PeerDialogExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, peerDialogExists, arg.OwnerID, arg.PeerType, arg.PeerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const readMarkers = `-- name: ReadMarkers :one
SELECT read_inbox_max_id, read_outbox_max_id FROM dialogs
WHERE owner_id = $1 AND peer_type = $2 AND peer_id = $3
`

type ReadMarkersParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
}

type ReadMarkersRow struct {
	ReadInboxMaxID  int64
	ReadOutboxMaxID int64
}

// ReadMarkers reads the current inbox and outbox boundaries for one dialog.
func (q *Queries) ReadMarkers(ctx context.Context, arg ReadMarkersParams) (ReadMarkersRow, error) {
	row := q.db.QueryRow(ctx, readMarkers, arg.OwnerID, arg.PeerType, arg.PeerID)
	var i ReadMarkersRow
	err := row.Scan(&i.ReadInboxMaxID, &i.ReadOutboxMaxID)
	return i, err
}

const upsertDialog = `-- name: UpsertDialog :exec
INSERT INTO dialogs (owner_id, peer_type, peer_id, top_message, unread_count)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (owner_id, peer_type, peer_id) DO UPDATE
  SET top_message  = EXCLUDED.top_message,
      unread_count = dialogs.unread_count + EXCLUDED.unread_count
`

type UpsertDialogParams struct {
	OwnerID     int64
	PeerType    int16
	PeerID      int64
	TopMessage  int64
	UnreadCount int32
}

// UpsertDialog advances top_message and adds an unread delta (0 for the sender's
// outbox side, 1 for the recipient's inbox side).
func (q *Queries) UpsertDialog(ctx context.Context, arg UpsertDialogParams) error {
	_, err := q.db.Exec(ctx, upsertDialog,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.TopMessage,
		arg.UnreadCount,
	)
	return err
}
