// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: erasure_outbox.sql

package db

import (
	"context"
)

const erasureEpochCompletionTotal = `-- name: ErasureEpochCompletionTotal :one
SELECT count(*)::bigint AS total FROM erasure_epoch_completion
`

func (q *Queries) ErasureEpochCompletionTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, erasureEpochCompletionTotal)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const erasureEpochLineageState = `-- name: ErasureEpochLineageState :one
SELECT e.epoch,
       e.lineage_id,
       (c.lineage_id IS NOT NULL)::boolean AS completed
FROM erasure_epoch e
LEFT JOIN erasure_epoch_completion c ON c.epoch = e.epoch AND c.lineage_id = e.lineage_id
WHERE e.epoch = $1 AND e.lineage_id = $2
`

type ErasureEpochLineageStateParams struct {
	Epoch     int64
	LineageID []byte
}

type ErasureEpochLineageStateRow struct {
	Epoch     int64
	LineageID []byte
	Completed bool
}

// ErasureEpochLineageState answers the admission question in the only form that
// is safe to answer: for this epoch AND this lineage, is it complete. A lineage
// with no completion row is reported not complete even when another lineage
// shares the epoch number and is complete.
func (q *Queries) ErasureEpochLineageState(ctx context.Context, arg ErasureEpochLineageStateParams) (ErasureEpochLineageStateRow, error) {
	row := q.db.QueryRow(ctx, erasureEpochLineageState, arg.Epoch, arg.LineageID)
	var i ErasureEpochLineageStateRow
	err := row.Scan(&i.Epoch, &i.LineageID, &i.Completed)
	return i, err
}

const erasureEpochLineagesForEpoch = `-- name: ErasureEpochLineagesForEpoch :many
SELECT epoch, lineage_id FROM erasure_epoch
WHERE epoch = $1
ORDER BY lineage_id
`

// ErasureEpochLineagesForEpoch lists the lineages that established one epoch,
// which is how a restore sees that two lineages share an epoch number.
func (q *Queries) ErasureEpochLineagesForEpoch(ctx context.Context, epoch int64) ([]ErasureEpoch, error) {
	rows, err := q.db.Query(ctx, erasureEpochLineagesForEpoch, epoch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErasureEpoch
	for rows.Next() {
		var i ErasureEpoch
		if err := rows.Scan(&i.Epoch, &i.LineageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const erasureEpochMarkerTotal = `-- name: ErasureEpochMarkerTotal :one
SELECT count(*)::bigint AS total FROM erasure_epoch
`

func (q *Queries) ErasureEpochMarkerTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, erasureEpochMarkerTotal)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const erasureOutboxByOperationKey = `-- name: ErasureOutboxByOperationKey :one
SELECT operation_key, epoch, stream_id, seq, kind, record FROM erasure_outbox WHERE operation_key = $1
`

func (q *Queries) ErasureOutboxByOperationKey(ctx context.Context, operationKey []byte) (ErasureOutbox, error) {
	row := q.db.QueryRow(ctx, erasureOutboxByOperationKey, operationKey)
	var i ErasureOutbox
	err := row.Scan(
		&i.OperationKey,
		&i.Epoch,
		&i.StreamID,
		&i.Seq,
		&i.Kind,
		&i.Record,
	)
	return i, err
}

const erasureOutboxStreamRecords = `-- name: ErasureOutboxStreamRecords :many
SELECT operation_key, epoch, stream_id, seq, kind, record FROM erasure_outbox
WHERE epoch = $1 AND stream_id = $2
ORDER BY seq
`

type ErasureOutboxStreamRecordsParams struct {
	Epoch    int64
	StreamID []byte
}

// ErasureOutboxStreamRecords walks one (epoch, stream) in seq order, the
// enumeration order the completeness contract is read in: a gap in seq is
// then visible to the caller rather than absorbed by the walk.
func (q *Queries) ErasureOutboxStreamRecords(ctx context.Context, arg ErasureOutboxStreamRecordsParams) ([]ErasureOutbox, error) {
	rows, err := q.db.Query(ctx, erasureOutboxStreamRecords, arg.Epoch, arg.StreamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErasureOutbox
	for rows.Next() {
		var i ErasureOutbox
		if err := rows.Scan(
			&i.OperationKey,
			&i.Epoch,
			&i.StreamID,
			&i.Seq,
			&i.Kind,
			&i.Record,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const erasureOutboxTotal = `-- name: ErasureOutboxTotal :one
SELECT count(*)::bigint AS total FROM erasure_outbox
`

func (q *Queries) ErasureOutboxTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, erasureOutboxTotal)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const insertErasureEpochCompletion = `-- name: InsertErasureEpochCompletion :exec
INSERT INTO erasure_epoch_completion (epoch, lineage_id)
VALUES ($1, $2)
`

type InsertErasureEpochCompletionParams struct {
	Epoch     int64
	LineageID []byte
}

// InsertErasureEpochCompletion records that one lineage finished replay for one
// epoch. It is an INSERT because completion is monotone: the row's existence is
// the fact, and no write here can lower it.
func (q *Queries) InsertErasureEpochCompletion(ctx context.Context, arg InsertErasureEpochCompletionParams) error {
	_, err := q.db.Exec(ctx, insertErasureEpochCompletion, arg.Epoch, arg.LineageID)
	return err
}

const insertErasureEpochMarker = `-- name: InsertErasureEpochMarker :exec
INSERT INTO erasure_epoch (epoch, lineage_id)
VALUES ($1, $2)
`

type InsertErasureEpochMarkerParams struct {
	Epoch     int64
	LineageID []byte
}

func (q *Queries) InsertErasureEpochMarker(ctx context.Context, arg InsertErasureEpochMarkerParams) error {
	_, err := q.db.Exec(ctx, insertErasureEpochMarker, arg.Epoch, arg.LineageID)
	return err
}

const insertErasureOutboxRecord = `-- name: InsertErasureOutboxRecord :exec

INSERT INTO erasure_outbox (operation_key, epoch, stream_id, seq, kind, record)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertErasureOutboxRecordParams struct {
	OperationKey []byte
	Epoch        int64
	StreamID     []byte
	Seq          int64
	Kind         int16
	Record       []byte
}

// Generated access to the inert erasure-ledger tables. There is no store method
// over any of these: the persistence slice is inert, so the only callers in the
// repository are the acceptance tests that prove the storage contract. A runtime
// writer is a later slice, and its absence is asserted by
// TestErasureLedgerPersistenceHasNoRuntimeCaller.
// InsertErasureOutboxRecord writes one record of the outbox. It is an INSERT and
// not an upsert on purpose: the operation key is the idempotency interlock, so a
// retried write must be refused by the database rather than replace the committed
// record it names. The envelope columns are a projection of the canonical record
// bytes, which a caller produces with the codec.
func (q *Queries) InsertErasureOutboxRecord(ctx context.Context, arg InsertErasureOutboxRecordParams) error {
	_, err := q.db.Exec(ctx, insertErasureOutboxRecord,
		arg.OperationKey,
		arg.Epoch,
		arg.StreamID,
		arg.Seq,
		arg.Kind,
		arg.Record,
	)
	return err
}
