// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeOrdinaryMessageInDialog = `-- name: ActiveOrdinaryMessageInDialog :one
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv, reply_to_trusted FROM messages
WHERE owner_id = $1::bigint
  AND local_id = $2::bigint
  AND peer_type = $3::smallint
  AND peer_id = $4::bigint
  AND deleted = false
  AND action_type = 0
`

type ActiveOrdinaryMessageInDialogParams struct {
	OwnerID  int64
	LocalID  int64
	PeerType int16
	PeerID   int64
}

// ActiveOrdinaryMessageInDialog is the authoritative lookup for a client reply.
// It deliberately checks owner-local id, exact peer namespace, live state, and
// ordinary-message type in the statement that runs inside the send transaction.
func (q *Queries) ActiveOrdinaryMessageInDialog(ctx context.Context, arg ActiveOrdinaryMessageInDialogParams) (Message, error) {
	row := q.db.QueryRow(ctx, activeOrdinaryMessageInDialog,
		arg.OwnerID,
		arg.LocalID,
		arg.PeerType,
		arg.PeerID,
	)
	var i Message
	err := row.Scan(
		&i.OwnerID,
		&i.LocalID,
		&i.PeerID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.Out,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.PeerLocalID,
		&i.PeerType,
		&i.FanoutID,
		&i.ActionType,
		&i.ActionUserID,
		&i.FileID,
		&i.ReplyToMsgID,
		&i.FwdFromID,
		&i.FwdDate,
		&i.FwdChannelID,
		&i.FwdChannelPost,
		&i.MessageTsv,
		&i.ReplyToTrusted,
	)
	return i, err
}

const countFilteredMessages = `-- name: CountFilteredMessages :one
SELECT count(*)::bigint
FROM messages m
WHERE m.owner_id = $1::bigint
  AND m.peer_type = $2::smallint
  AND m.peer_id = $3::bigint
  AND m.peer_type IN (1, 2)
  AND m.deleted = false
  AND (m.peer_type <> 2 OR EXISTS (
      SELECT 1 FROM chat_participants cp
      WHERE cp.chat_id = m.peer_id AND cp.user_id = m.owner_id
  ))
  AND CASE $4::smallint
      WHEN 1 THEN m.file_id <> 0 AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
            AND f.media_kind = 'document'
      )
      WHEN 2 THEN m.file_id <> 0 AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
            AND f.media_kind = 'photo'
      )
      WHEN 3 THEN m.message ~* '(^|[^[:alnum:]_@])(([[:alpha:]][[:alnum:]+.-]*://|www[.])[^[:space:]]+|[[:alnum:]-]+[.][[:alpha:]]{2,}(:[0-9]{1,5})?(/[[:graph:]]*)?)' -- noqa: LT05
      WHEN 4 THEN m.file_id <> 0 AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
            AND f.subtype_rights @> ARRAY['send_videos']::text[]
      )
      WHEN 5 THEN m.file_id <> 0 AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
            AND f.subtype_rights @> ARRAY['send_gifs']::text[]
      )
      WHEN 6 THEN EXISTS (
          SELECT 1 FROM poll_message_copies pmc
          WHERE pmc.owner_id = m.owner_id AND pmc.local_id = m.local_id
      )
      WHEN 7 THEN m.file_id <> 0 AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
            AND f.subtype_rights && ARRAY['send_roundvideos', 'send_voices']::text[]
      )
      WHEN 8 THEN m.file_id <> 0 AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
            AND f.subtype_rights @> ARRAY['send_audios']::text[]
      )
      WHEN 9 THEN m.file_id <> 0 AND EXISTS (
          SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
            AND (f.media_kind = 'photo' OR f.subtype_rights @> ARRAY['send_videos']::text[])
      )
      ELSE false
  END
  AND ($5::text = '' OR m.message_tsv @@ plainto_tsquery('simple', $5))
`

type CountFilteredMessagesParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
	Filter   int16
	Query    string
}

// Filtered shared-media searches count and page only the caller's owned rows.
// Chat membership is repeated in the predicate so a removal between the
// handler's admission check and this read cannot expose retained chat copies.
// Filter values are 1=document, 2=photo, 3=URL, 4=video, 5=GIF, 6=poll,
// 7=round video or voice, 8=audio, and 9=photo or video. The two file-backed
// tabs are split on files.media_kind, so a photo is counted and listed under
// Photos only and a document under Files only.
// Polls are matched only through the caller's own local message copy. File
// subtypes are matched only while the stored body can be rendered. URL
// detection runs in Postgres over one authorized peer's rows; the app does not
// load a dialog history to classify links.
func (q *Queries) CountFilteredMessages(ctx context.Context, arg CountFilteredMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredMessages,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.Filter,
		arg.Query,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const historyPage = `-- name: HistoryPage :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv, reply_to_trusted FROM messages
WHERE owner_id = $1
  AND peer_type = $2
  AND peer_id = $3
  AND deleted = false
  AND ($4::bigint = 0 OR local_id < $4::bigint)
ORDER BY local_id DESC
LIMIT $6::int
OFFSET GREATEST(0::bigint, $5::bigint)
`

type HistoryPageParams struct {
	OwnerID   int64
	PeerType  int16
	PeerID    int64
	OffsetID  int64
	AddOffset int64
	Lim       int32
}

func (q *Queries) HistoryPage(ctx context.Context, arg HistoryPageParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, historyPage,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.OffsetID,
		arg.AddOffset,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
			&i.ReplyToTrusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyPageAround = `-- name: HistoryPageAround :many
WITH page_offset AS (
    SELECT GREATEST(0::bigint, COUNT(*) + $5::bigint) AS skip
    FROM messages AS offset_message
    WHERE offset_message.owner_id = $1
      AND offset_message.peer_type = $2
      AND offset_message.peer_id = $3
      AND offset_message.deleted = false
      AND offset_message.local_id >= $6::bigint
)
SELECT page_message.owner_id, page_message.local_id, page_message.peer_id, page_message.from_id, page_message.date, page_message.message, page_message.out, page_message.edit_date, page_message.deleted, page_message.random_id, page_message.peer_local_id, page_message.peer_type, page_message.fanout_id, page_message.action_type, page_message.action_user_id, page_message.file_id, page_message.reply_to_msg_id, page_message.fwd_from_id, page_message.fwd_date, page_message.fwd_channel_id, page_message.fwd_channel_post, page_message.message_tsv, page_message.reply_to_trusted FROM messages AS page_message
WHERE page_message.owner_id = $1
  AND page_message.peer_type = $2
  AND page_message.peer_id = $3
  AND page_message.deleted = false
ORDER BY page_message.local_id DESC
LIMIT $4::int
OFFSET (SELECT skip FROM page_offset)
`

type HistoryPageAroundParams struct {
	OwnerID   int64
	PeerType  int16
	PeerID    int64
	Lim       int32
	AddOffset int64
	OffsetID  int64
}

// HistoryPageAround handles negative add_offset by converting offset_id to its
// ordinal in the owner's filtered newest-first history before selecting a page.
func (q *Queries) HistoryPageAround(ctx context.Context, arg HistoryPageAroundParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, historyPageAround,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.Lim,
		arg.AddOffset,
		arg.OffsetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
			&i.ReplyToTrusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (owner_id, local_id, peer_type, peer_id, from_id, message, out, random_id, peer_local_id,
                      fanout_id, action_type, action_user_id, file_id, reply_to_msg_id,
                      fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, reply_to_trusted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
`

type InsertMessageParams struct {
	OwnerID        int64
	LocalID        int64
	PeerType       int16
	PeerID         int64
	FromID         int64
	Message        string
	Out            bool
	RandomID       int64
	PeerLocalID    int64
	FanoutID       int64
	ActionType     int16
	ActionUserID   int64
	FileID         int64
	ReplyToMsgID   *int32
	FwdFromID      *int64
	FwdDate        pgtype.Timestamptz
	FwdChannelID   *int64
	FwdChannelPost *int32
	ReplyToTrusted bool
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.OwnerID,
		arg.LocalID,
		arg.PeerType,
		arg.PeerID,
		arg.FromID,
		arg.Message,
		arg.Out,
		arg.RandomID,
		arg.PeerLocalID,
		arg.FanoutID,
		arg.ActionType,
		arg.ActionUserID,
		arg.FileID,
		arg.ReplyToMsgID,
		arg.FwdFromID,
		arg.FwdDate,
		arg.FwdChannelID,
		arg.FwdChannelPost,
		arg.ReplyToTrusted,
	)
	return err
}

const messageByOwnerLocal = `-- name: MessageByOwnerLocal :one
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv, reply_to_trusted FROM messages WHERE owner_id = $1 AND local_id = $2
`

type MessageByOwnerLocalParams struct {
	OwnerID int64
	LocalID int64
}

func (q *Queries) MessageByOwnerLocal(ctx context.Context, arg MessageByOwnerLocalParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageByOwnerLocal, arg.OwnerID, arg.LocalID)
	var i Message
	err := row.Scan(
		&i.OwnerID,
		&i.LocalID,
		&i.PeerID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.Out,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.PeerLocalID,
		&i.PeerType,
		&i.FanoutID,
		&i.ActionType,
		&i.ActionUserID,
		&i.FileID,
		&i.ReplyToMsgID,
		&i.FwdFromID,
		&i.FwdDate,
		&i.FwdChannelID,
		&i.FwdChannelPost,
		&i.MessageTsv,
		&i.ReplyToTrusted,
	)
	return i, err
}

const messageByRandomID = `-- name: MessageByRandomID :one
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv, reply_to_trusted FROM messages WHERE owner_id = $1 AND random_id = $2 AND random_id <> 0
`

type MessageByRandomIDParams struct {
	OwnerID  int64
	RandomID int64
}

func (q *Queries) MessageByRandomID(ctx context.Context, arg MessageByRandomIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageByRandomID, arg.OwnerID, arg.RandomID)
	var i Message
	err := row.Scan(
		&i.OwnerID,
		&i.LocalID,
		&i.PeerID,
		&i.FromID,
		&i.Date,
		&i.Message,
		&i.Out,
		&i.EditDate,
		&i.Deleted,
		&i.RandomID,
		&i.PeerLocalID,
		&i.PeerType,
		&i.FanoutID,
		&i.ActionType,
		&i.ActionUserID,
		&i.FileID,
		&i.ReplyToMsgID,
		&i.FwdFromID,
		&i.FwdDate,
		&i.FwdChannelID,
		&i.FwdChannelPost,
		&i.MessageTsv,
		&i.ReplyToTrusted,
	)
	return i, err
}

const messagesByFanout = `-- name: MessagesByFanout :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv, reply_to_trusted FROM messages
WHERE fanout_id = $1 AND fanout_id <> 0
ORDER BY owner_id
`

// MessagesByFanout returns every per-member copy of one chat message, ascending
// by owner_id so a caller can take its advisory locks in that order. The
// `fanout_id <> 0` predicate is not redundant with the equality: 0 is the "not a
// chat message" sentinel every 1:1 row carries, so a zero argument would select
// the entire table instead of nothing.
func (q *Queries) MessagesByFanout(ctx context.Context, fanoutID int64) ([]Message, error) {
	rows, err := q.db.Query(ctx, messagesByFanout, fanoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
			&i.ReplyToTrusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextFanoutID = `-- name: NextFanoutID :one
SELECT nextval('message_fanout_seq')::bigint AS fanout_id
`

// NextFanoutID allocates the id shared by every per-member copy of one chat
// message. One value per fan-out, never 0.
func (q *Queries) NextFanoutID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextFanoutID)
	var fanout_id int64
	err := row.Scan(&fanout_id)
	return fanout_id, err
}

const searchFilteredMessagesPage = `-- name: SearchFilteredMessagesPage :many
WITH page AS (
    SELECT m.local_id
    FROM messages m
    WHERE m.owner_id = $1::bigint
      AND m.peer_type = $2::smallint
      AND m.peer_id = $3::bigint
      AND m.peer_type IN (1, 2)
      AND m.deleted = false
      AND (m.peer_type <> 2 OR EXISTS (
          SELECT 1 FROM chat_participants cp
          WHERE cp.chat_id = m.peer_id AND cp.user_id = m.owner_id
      ))
      AND CASE $6::smallint
          WHEN 1 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.media_kind = 'document'
          )
          WHEN 2 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.media_kind = 'photo'
          )
          WHEN 3 THEN m.message ~* '(^|[^[:alnum:]_@])(([[:alpha:]][[:alnum:]+.-]*://|www[.])[^[:space:]]+|[[:alnum:]-]+[.][[:alpha:]]{2,}(:[0-9]{1,5})?(/[[:graph:]]*)?)' -- noqa: LT05
          WHEN 4 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.subtype_rights @> ARRAY['send_videos']::text[]
          )
          WHEN 5 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.subtype_rights @> ARRAY['send_gifs']::text[]
          )
          WHEN 6 THEN EXISTS (
              SELECT 1 FROM poll_message_copies pmc
              WHERE pmc.owner_id = m.owner_id AND pmc.local_id = m.local_id
          )
          WHEN 7 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.subtype_rights && ARRAY['send_roundvideos', 'send_voices']::text[]
          )
          WHEN 8 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.subtype_rights @> ARRAY['send_audios']::text[]
          )
          WHEN 9 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND (f.media_kind = 'photo' OR f.subtype_rights @> ARRAY['send_videos']::text[])
          )
          ELSE false
      END
      AND ($7::text = '' OR m.message_tsv @@ plainto_tsquery('simple', $7))
      AND ($8::bigint = 0 OR m.local_id < $8::bigint)
    ORDER BY m.local_id DESC
    LIMIT $10::int
    OFFSET GREATEST(0::bigint, $9::bigint)
)
SELECT m.owner_id, m.local_id, m.peer_id, m.from_id, m.date, m.message, m.out, m.edit_date, m.deleted, m.random_id, m.peer_local_id, m.peer_type, m.fanout_id, m.action_type, m.action_user_id, m.file_id, m.reply_to_msg_id, m.fwd_from_id, m.fwd_date, m.fwd_channel_id, m.fwd_channel_post, m.message_tsv, m.reply_to_trusted
FROM messages m
JOIN page ON page.local_id = m.local_id
WHERE m.owner_id = $1::bigint
  AND m.peer_type = $2::smallint
  AND m.peer_id = $3::bigint
  AND ($4::bigint <= 0 OR m.local_id < $4::bigint)
  AND ($5::bigint <= 0 OR m.local_id > $5::bigint)
ORDER BY m.local_id DESC
`

type SearchFilteredMessagesPageParams struct {
	OwnerID   int64
	PeerType  int16
	PeerID    int64
	MaxID     int64
	MinID     int64
	Filter    int16
	Query     string
	OffsetID  int64
	AddOffset int64
	Lim       int32
}

func (q *Queries) SearchFilteredMessagesPage(ctx context.Context, arg SearchFilteredMessagesPageParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, searchFilteredMessagesPage,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.MaxID,
		arg.MinID,
		arg.Filter,
		arg.Query,
		arg.OffsetID,
		arg.AddOffset,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
			&i.ReplyToTrusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFilteredMessagesPageAround = `-- name: SearchFilteredMessagesPageAround :many
WITH matching AS MATERIALIZED (
    SELECT m.local_id
    FROM messages m
    WHERE m.owner_id = $1::bigint
      AND m.peer_type = $2::smallint
      AND m.peer_id = $3::bigint
      AND m.peer_type IN (1, 2)
      AND m.deleted = false
      AND (m.peer_type <> 2 OR EXISTS (
          SELECT 1 FROM chat_participants cp
          WHERE cp.chat_id = m.peer_id AND cp.user_id = m.owner_id
      ))
      AND CASE $6::smallint
          WHEN 1 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.media_kind = 'document'
          )
          WHEN 2 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.media_kind = 'photo'
          )
          WHEN 3 THEN m.message ~* '(^|[^[:alnum:]_@])(([[:alpha:]][[:alnum:]+.-]*://|www[.])[^[:space:]]+|[[:alnum:]-]+[.][[:alpha:]]{2,}(:[0-9]{1,5})?(/[[:graph:]]*)?)' -- noqa: LT05
          WHEN 4 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.subtype_rights @> ARRAY['send_videos']::text[]
          )
          WHEN 5 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.subtype_rights @> ARRAY['send_gifs']::text[]
          )
          WHEN 6 THEN EXISTS (
              SELECT 1 FROM poll_message_copies pmc
              WHERE pmc.owner_id = m.owner_id AND pmc.local_id = m.local_id
          )
          WHEN 7 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.subtype_rights && ARRAY['send_roundvideos', 'send_voices']::text[]
          )
          WHEN 8 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND f.subtype_rights @> ARRAY['send_audios']::text[]
          )
          WHEN 9 THEN m.file_id <> 0 AND EXISTS (
              SELECT 1 FROM files f WHERE f.id = m.file_id AND f.stored = true
                AND (f.media_kind = 'photo' OR f.subtype_rights @> ARRAY['send_videos']::text[])
          )
          ELSE false
      END
      AND ($7::text = '' OR m.message_tsv @@ plainto_tsquery('simple', $7))
), page_offset AS (
    SELECT GREATEST(
        COUNT(*) FILTER (WHERE local_id >= $8::bigint) + $9::bigint,
        0::bigint
    ) AS skip
    FROM matching
), page AS (
    SELECT local_id FROM matching
    ORDER BY local_id DESC
    LIMIT $10::int
    OFFSET (SELECT skip FROM page_offset)
)
SELECT m.owner_id, m.local_id, m.peer_id, m.from_id, m.date, m.message, m.out, m.edit_date, m.deleted, m.random_id, m.peer_local_id, m.peer_type, m.fanout_id, m.action_type, m.action_user_id, m.file_id, m.reply_to_msg_id, m.fwd_from_id, m.fwd_date, m.fwd_channel_id, m.fwd_channel_post, m.message_tsv, m.reply_to_trusted
FROM messages m
JOIN page ON page.local_id = m.local_id
WHERE m.owner_id = $1::bigint
  AND m.peer_type = $2::smallint
  AND m.peer_id = $3::bigint
  AND ($4::bigint <= 0 OR m.local_id < $4::bigint)
  AND ($5::bigint <= 0 OR m.local_id > $5::bigint)
ORDER BY m.local_id DESC
`

type SearchFilteredMessagesPageAroundParams struct {
	OwnerID   int64
	PeerType  int16
	PeerID    int64
	MaxID     int64
	MinID     int64
	Filter    int16
	Query     string
	OffsetID  int64
	AddOffset int64
	Lim       int32
}

// SearchFilteredMessagesPageAround counts the filter-matched rows before the
// anchor so negative add_offset can select a page around offset_id.
func (q *Queries) SearchFilteredMessagesPageAround(ctx context.Context, arg SearchFilteredMessagesPageAroundParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, searchFilteredMessagesPageAround,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.MaxID,
		arg.MinID,
		arg.Filter,
		arg.Query,
		arg.OffsetID,
		arg.AddOffset,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
			&i.ReplyToTrusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv, reply_to_trusted FROM messages
WHERE owner_id = $1
  AND peer_type = $2
  AND peer_id = $3
  AND deleted = false
  AND message_tsv @@ plainto_tsquery('simple', $4)
  AND ($5::bigint = 0 OR local_id < $5::bigint)
ORDER BY local_id DESC
LIMIT $6::int
`

type SearchMessagesParams struct {
	OwnerID  int64
	PeerType int16
	PeerID   int64
	Query    string
	OffsetID int64
	Lim      int32
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.OwnerID,
		arg.PeerType,
		arg.PeerID,
		arg.Query,
		arg.OffsetID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
			&i.ReplyToTrusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeleted = `-- name: SetDeleted :execrows
UPDATE messages SET deleted = true WHERE owner_id = $1 AND local_id = $2 AND NOT deleted
`

type SetDeletedParams struct {
	OwnerID int64
	LocalID int64
}

// SetDeleted marks one owner-local message deleted and reports how many rows
// it changed. The `AND NOT deleted` predicate is the whole point: it makes the
// write the authority on whether the row was already gone, so a caller decides
// under the same serialisation as the update rather than off a `deleted` flag
// read before the per-owner locks. A second delete of the same row — a repeat
// self-delete, or a revoke walk resuming after a concurrent self-delete landed
// on the copy it is about to touch — changes zero rows instead of silently
// re-marking a row that is already deleted.
func (q *Queries) SetDeleted(ctx context.Context, arg SetDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDeleted, arg.OwnerID, arg.LocalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEditedText = `-- name: SetEditedText :exec
UPDATE messages SET message = $3, edit_date = now() WHERE owner_id = $1 AND local_id = $2
`

type SetEditedTextParams struct {
	OwnerID int64
	LocalID int64
	Message string
}

func (q *Queries) SetEditedText(ctx context.Context, arg SetEditedTextParams) error {
	_, err := q.db.Exec(ctx, setEditedText, arg.OwnerID, arg.LocalID, arg.Message)
	return err
}
