// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSession struct {
	SessionHash      []byte
	TokenFingerprint []byte
	ExpiresAt        pgtype.Timestamptz
	LastActivity     pgtype.Timestamptz
}

type AuthKey struct {
	ID               int64
	KeyValue         []byte
	UserID           *int64
	CreatedAt        pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	PendingUserID    *int64
	PendingStartedAt pgtype.Timestamptz
}

type BlockedUser struct {
	BlockerID int64
	BlockedID int64
	CreatedAt pgtype.Timestamptz
}

type Channel struct {
	// Random, not sequential. New ids are a uniform crypto/rand draw over [2^31, 10^12 - 2^31] (internal/store/channels.go); ids below 2^31 predate that and came from channels_id_seq. Never reset or re-point the sequence, and never treat the id as an authorization input.
	ID                   int64
	Title                string
	About                string
	CreatorID            int64
	Megagroup            bool
	Version              int32
	Date                 pgtype.Timestamptz
	PinnedMessageID      *int32
	Username             *string
	TitleTsv             interface{}
	PubliclyDiscoverable bool
	DefaultBannedRights  []string
	SlowmodeSeconds      int16
}

type ChannelEvent struct {
	ChannelID int64
	Pts       int64
	Type      int16
	LocalID   int64
}

type ChannelInvite struct {
	Hash      string
	ChannelID int64
	CreatorID int64
	Date      pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type ChannelMessage struct {
	ChannelID    int64
	LocalID      int64
	FromID       int64
	Date         pgtype.Timestamptz
	Message      string
	EditDate     pgtype.Timestamptz
	Deleted      bool
	RandomID     int64
	FileID       *int64
	MessageTsv   interface{}
	ReplyToMsgID *int32
	ActionType   int16
}

type ChannelParticipant struct {
	ChannelID   int64
	UserID      int64
	Role        int16
	BannedUntil pgtype.Timestamptz
	JoinPts     int64
	Date        pgtype.Timestamptz
	LastPostAt  pgtype.Timestamptz
}

type ChannelPollMessage struct {
	ChannelID int64
	LocalID   int64
	PollID    int64
}

type ChannelPostMarker struct {
	ChannelID  int64
	UserID     int64
	LastPostAt pgtype.Timestamptz
}

type ChannelPostSummary struct {
	ChannelID int64
	ScopeKind int16
	AuthorID  int64
	Depth     int16
	Prefix    int64
	LiveCount int64
}

type ChannelPostSummaryState struct {
	ChannelID int64
	Version   int16
	Ready     bool
}

type ChannelReadState struct {
	ChannelID int64
	UserID    int64
	ReadMaxID int64
}

type ChannelState struct {
	ChannelID   int64
	Pts         int64
	NextLocalID int64
	Date        pgtype.Timestamptz
}

type ChannelUsernameChange struct {
	ChannelID int64
	ChangedAt pgtype.Timestamptz
}

type Chat struct {
	ID                  int64
	Title               string
	CreatorID           int64
	Version             int32
	Date                pgtype.Timestamptz
	PinnedMessageID     *int32
	DefaultBannedRights []string
}

type ChatAdminEvent struct {
	ID      int64
	ChatID  int64
	UserID  int64
	IsAdmin bool
	Version int32
}

type ChatAdminEventRecipient struct {
	OwnerID  int64
	ChatID   int64
	TargetID int64
	EventID  int64
}

type ChatAdminStateMarker struct {
	OwnerID  int64
	ChatID   int64
	TargetID int64
	EventID  int64
}

type ChatParticipant struct {
	ChatID    int64
	UserID    int64
	InviterID int64
	Date      pgtype.Timestamptz
	IsAdmin   bool
}

type Dialog struct {
	OwnerID         int64
	PeerID          int64
	TopMessage      int64
	UnreadCount     int32
	ReadInboxMaxID  int64
	ReadOutboxMaxID int64
	PeerType        int16
}

type EncryptedEvent struct {
	OwnerID  int64
	Qts      int64
	ChatID   int32
	RandomID int64
	Bytes    []byte
	Date     pgtype.Timestamptz
}

type File struct {
	ID            int64
	UploaderID    int64
	AccessHash    int64
	Size          int64
	MimeType      string
	FileName      string
	Stored        bool
	Date          pgtype.Timestamptz
	SubtypeRights []string
}

type FleetLiveAccount struct {
	Generation string
	UserID     int64
}

type FleetProcessSnapshot struct {
	Generation       string
	ReplicaID        *string
	Version          string
	ProcessStartedAt pgtype.Timestamptz
	HeartbeatAt      pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	Connections      int64
	Sessions         int64
	AccountsComplete bool
}

type LanguageCatalogChange struct {
	LangPack    string
	LangCode    string
	Version     int64
	Key         string
	Kind        int16
	Value       string
	PluralZero  *string
	PluralOne   *string
	PluralTwo   *string
	PluralFew   *string
	PluralMany  *string
	PluralOther *string
	Deleted     bool
}

type LanguageCatalogCurrentString struct {
	LangPack           string
	LangCode           string
	Key                string
	Kind               int16
	Value              string
	PluralZero         *string
	PluralOne          *string
	PluralTwo          *string
	PluralFew          *string
	PluralMany         *string
	PluralOther        *string
	Deleted            bool
	LastChangedVersion int64
}

type LanguageCatalogPack struct {
	LangPack              string
	LangCode              string
	CurrentVersion        int64
	Name                  string
	NativeName            string
	PluralCode            string
	CurrentContentSha256  []byte
	CurrentManifestSha256 []byte
	SourceUrl             string
	SourceRevision        string
	SourceSha256          []byte
	SourceNotice          string
	Attribution           string
	UpdatedAt             pgtype.Timestamptz
}

type LanguageCatalogPublicationAudit struct {
	ID              int64
	LangPack        string
	LangCode        string
	OldVersion      *int64
	NewVersion      int64
	SourceCommitSha string
	SourceRevision  string
	SourceSha256    []byte
	ContentSha256   []byte
	ManifestSha256  []byte
	ValidatorResult string
	OsUser          string
	CreatedAt       pgtype.Timestamptz
}

type LanguageCatalogTombstone struct {
	LangPack string
	LangCode string
	Version  int64
	Key      string
}

type LanguageCatalogVersion struct {
	LangPack       string
	LangCode       string
	Version        int64
	Name           string
	NativeName     string
	PluralCode     string
	ContentSha256  []byte
	ManifestSha256 []byte
	SourceUrl      string
	SourceRevision string
	SourceSha256   []byte
	SourceNotice   string
	Attribution    string
	PublishedAt    pgtype.Timestamptz
}

type Message struct {
	OwnerID        int64
	LocalID        int64
	PeerID         int64
	FromID         int64
	Date           pgtype.Timestamptz
	Message        string
	Out            bool
	EditDate       pgtype.Timestamptz
	Deleted        bool
	RandomID       int64
	PeerLocalID    int64
	PeerType       int16
	FanoutID       int64
	ActionType     int16
	ActionUserID   int64
	FileID         int64
	ReplyToMsgID   *int32
	FwdFromID      *int64
	FwdDate        pgtype.Timestamptz
	FwdChannelID   *int64
	FwdChannelPost *int32
	MessageTsv     interface{}
}

type MessageEvent struct {
	OwnerID int64
	Pts     int64
	Type    int16
	LocalID int64
}

type MessageReaction struct {
	OwnerID   int64
	LocalID   int64
	ReactorID int64
	Reaction  string
	CreatedAt pgtype.Timestamptz
}

type PhoneCode struct {
	Phone      string
	CodeHash   string
	Code       string
	ExpiresAt  pgtype.Timestamptz
	Attempts   int32
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	ID         *int64
}

type PhoneLookup struct {
	CallerID   int64
	Phone      string
	LookedUpAt pgtype.Timestamptz
}

type Poll struct {
	ID               int64
	CreatorID        int64
	RandomID         int64
	SourceLocalID    int64
	Question         []byte
	PublicVoters     bool
	MultipleChoice   bool
	Quiz             bool
	ShuffleAnswers   bool
	RevotingDisabled bool
	Closed           bool
	CloseDate        pgtype.Timestamptz
	Solution         []byte
	CreatedAt        pgtype.Timestamptz
}

type PollMessageCopy struct {
	OwnerID int64
	LocalID int64
	PollID  int64
}

type PollOption struct {
	PollID   int64
	Option   []byte
	Text     []byte
	Correct  bool
	Position int16
}

type PollVote struct {
	PollID       int64
	VoterID      int64
	FirstVotedAt pgtype.Timestamptz
}

type PollVoteOption struct {
	PollID  int64
	VoterID int64
	Option  []byte
}

type RateLimit struct {
	SubjectID   int64
	Surface     string
	TokenCount  int32
	WindowStart pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type RegistrationInvite struct {
	ID           int64
	Handle       string
	SecretDigest []byte
	IssuedAt     pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	State        string
	ConsumedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

type SecretChat struct {
	ID             int32
	AdminID        int64
	ParticipantID  int64
	State          string
	GAHash         []byte
	GA             []byte
	GAOrB          []byte
	KeyFingerprint *int64
	Date           pgtype.Timestamptz
	RandomID       int64
}

type SendCodeIpCall struct {
	IpKey       netip.Prefix
	TokenCount  int32
	WindowStart pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type SendCodeIpPhone struct {
	IpKey     netip.Prefix
	Phone     string
	ExpiresAt pgtype.Timestamptz
}

type ServerAdministration struct {
	SingletonID         int16
	ElectionClosed      bool
	AdministratorUserID *int64
}

type ServerLimitLease struct {
	LeaseID   []byte
	SubjectID int64
	Surface   string
	ExpiresAt pgtype.Timestamptz
}

type SignInFailCall struct {
	IpKey       netip.Prefix
	TokenCount  int32
	WindowStart pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type SrpChallenge struct {
	SrpID     int64
	AuthKeyID int64
	UserID    int64
	BSecret   []byte
	BPublic   []byte
	ExpiresAt pgtype.Timestamptz
}

type UpdateState struct {
	UserID      int64
	Pts         int64
	Seq         int64
	Date        pgtype.Timestamptz
	NextLocalID int64
	Qts         int64
}

type UploadPart struct {
	UserID    int64
	FileID    int64
	PartIndex int32
	Date      pgtype.Timestamptz
	Size      int64
	BlobKey   string
}

type User struct {
	ID         int64
	Phone      *string
	FirstName  string
	LastName   string
	CreatedAt  pgtype.Timestamptz
	IsOnline   bool
	LastSeenAt pgtype.Timestamptz
	Username   *string
	NameTsv    interface{}
	LoginMode  string
}

type UserContact struct {
	OwnerID   int64
	ContactID int64
}

type UserDialogFilter struct {
	OwnerID         int64
	FilterID        int16
	Title           string
	Emoticon        string
	Color           *int16
	Contacts        bool
	NonContacts     bool
	Groups          bool
	Broadcasts      bool
	Bots            bool
	ExcludeMuted    bool
	ExcludeRead     bool
	ExcludeArchived bool
	TitleNoanimate  bool
}

type UserDialogFilterEntity struct {
	OwnerID        int64
	FilterID       int16
	EntityPosition int16
	EntityOffset   int32
	Length         int32
	DocumentID     int64
}

type UserDialogFilterPeer struct {
	OwnerID      int64
	FilterID     int16
	ListType     int16
	PeerType     int16
	PeerID       int64
	PeerPosition int16
}

type UserDialogFilterState struct {
	OwnerID          int64
	OrderIds         []int16
	ChangedAt        pgtype.Timestamptz
	DefaultsSeededAt pgtype.Timestamptz
}

type UserPassword struct {
	UserID        int64
	Salt1         []byte
	Salt2         []byte
	Verifier      []byte
	Hint          string
	RecoveryEmail *string
	HasRecovery   bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Username struct {
	Handle    string
	OwnerType string
	OwnerID   int64
}

type UsernameChange struct {
	UserID    int64
	ChangedAt pgtype.Timestamptz
}

type UsernameLookup struct {
	CallerID   int64
	Handle     string
	LookedUpAt pgtype.Timestamptz
}
