// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: peer_dialogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const basicUnreadCountForOwner = `-- name: BasicUnreadCountForOwner :one
SELECT COALESCE(SUM(dialog.unread_count), 0)::bigint AS unread_count
FROM dialogs AS dialog
WHERE dialog.owner_id = $1::bigint
`

// BasicUnreadCountForOwner is used by getDifference, which must preserve
// ordinary dialog unread state without depending on channel summary readiness.
func (q *Queries) BasicUnreadCountForOwner(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, basicUnreadCountForOwner, ownerID)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const chatParticipantsByChatIDs = `-- name: ChatParticipantsByChatIDs :many
SELECT chat_id, user_id, inviter_id, date, is_admin FROM chat_participants
WHERE chat_id = ANY($1::bigint[])
ORDER BY chat_id, user_id
`

func (q *Queries) ChatParticipantsByChatIDs(ctx context.Context, chatIds []int64) ([]ChatParticipant, error) {
	rows, err := q.db.Query(ctx, chatParticipantsByChatIDs, chatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatParticipant
	for rows.Next() {
		var i ChatParticipant
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.InviterID,
			&i.Date,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chatsByIDs = `-- name: ChatsByIDs :many
SELECT id, title, creator_id, version, date, pinned_message_id, default_banned_rights FROM chats
WHERE id = ANY($1::bigint[])
`

func (q *Queries) ChatsByIDs(ctx context.Context, chatIds []int64) ([]Chat, error) {
	rows, err := q.db.Query(ctx, chatsByIDs, chatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatorID,
			&i.Version,
			&i.Date,
			&i.PinnedMessageID,
			&i.DefaultBannedRights,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesByOwnerLocals = `-- name: MessagesByOwnerLocals :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv, reply_to_trusted FROM messages
WHERE owner_id = $1::bigint
  AND local_id = ANY($2::bigint[])
`

type MessagesByOwnerLocalsParams struct {
	OwnerID  int64
	LocalIds []int64
}

func (q *Queries) MessagesByOwnerLocals(ctx context.Context, arg MessagesByOwnerLocalsParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, messagesByOwnerLocals, arg.OwnerID, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
			&i.ReplyToTrusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const peerChannelDialogsForOwner = `-- name: PeerChannelDialogsForOwner :many
SELECT
    c.id AS channel_id,
    c.title AS channel_title,
    c.about AS channel_about,
    c.creator_id AS channel_creator_id,
    c.megagroup AS channel_megagroup,
    c.version AS channel_version,
    c.date AS channel_date,
    c.pinned_message_id AS channel_pinned_message_id,
    c.username AS channel_username,
    c.default_banned_rights AS channel_default_banned_rights,
    p.role AS member_role,
    p.banned_until AS member_banned_until,
    p.join_pts AS member_join_pts,
    COALESCE(read_state.read_max_id, 0)::bigint AS read_inbox_max_id,
    unread.unread_count,
    unread.entitled::boolean AS summary_entitled,
    unread.status_exists::boolean AS summary_status_exists,
    unread.summary_version::smallint AS summary_version,
    unread.summary_ready::boolean AS summary_ready,
    unread.total_live::bigint AS summary_total_live,
    unread.author_live::bigint AS summary_author_live,
    cs.pts AS channel_pts,
    COALESCE(top.local_id, 0)::bigint AS top_local_id,
    COALESCE(top.from_id, 0)::bigint AS top_from_id,
    COALESCE(top.date, c.date) AS top_date,
    COALESCE(top.message, '') AS top_message,
    top.edit_date AS top_edit_date,
    COALESCE(top.random_id, 0)::bigint AS top_random_id,
    top.file_id AS top_file_id,
    top.reply_to_msg_id AS top_reply_to_msg_id,
    COALESCE(top.action_type, 0)::smallint AS top_action_type
FROM channels c
JOIN channel_participants p ON p.channel_id = c.id
JOIN channel_state cs ON cs.channel_id = c.id
LEFT JOIN channel_read_state read_state
  ON read_state.channel_id = c.id AND read_state.user_id = p.user_id
CROSS JOIN LATERAL (
    SELECT LEAST(GREATEST(summary.total_live - summary.author_live, 0), 1000)::int AS unread_count,
           summary.entitled::boolean AS entitled,
           summary.status_exists::boolean AS status_exists,
           summary.summary_version::smallint AS summary_version,
           summary.summary_ready::boolean AS summary_ready,
           summary.total_live::bigint AS total_live,
           summary.author_live::bigint AS author_live
    FROM channel_post_unread_suffix_counts(
        c.id,
        p.user_id,
        COALESCE(read_state.read_max_id, 0)
    ) AS summary(entitled, status_exists, summary_version, summary_ready, total_live, author_live)
) AS unread
LEFT JOIN LATERAL (
    SELECT cm.local_id, cm.from_id, cm.date, cm.message, cm.edit_date,
           cm.random_id, cm.file_id, cm.reply_to_msg_id, cm.action_type
    FROM channel_messages cm
    WHERE cm.channel_id = c.id AND cm.deleted = false AND cm.action_type = 0
    ORDER BY cm.local_id DESC
    LIMIT 1
) top ON true
WHERE c.id = ANY($1::bigint[])
  AND p.user_id = $2::bigint
  AND (p.banned_until IS NULL OR p.banned_until <= now())
`

type PeerChannelDialogsForOwnerParams struct {
	ChannelIds []int64
	OwnerID    int64
}

type PeerChannelDialogsForOwnerRow struct {
	ChannelID                  int64
	ChannelTitle               string
	ChannelAbout               string
	ChannelCreatorID           int64
	ChannelMegagroup           bool
	ChannelVersion             int32
	ChannelDate                pgtype.Timestamptz
	ChannelPinnedMessageID     *int32
	ChannelUsername            *string
	ChannelDefaultBannedRights []string
	MemberRole                 int16
	MemberBannedUntil          pgtype.Timestamptz
	MemberJoinPts              int64
	ReadInboxMaxID             int64
	UnreadCount                int32
	SummaryEntitled            bool
	SummaryStatusExists        bool
	SummaryVersion             int16
	SummaryReady               bool
	SummaryTotalLive           int64
	SummaryAuthorLive          int64
	ChannelPts                 int64
	TopLocalID                 int64
	TopFromID                  int64
	TopDate                    pgtype.Timestamptz
	TopMessage                 string
	TopEditDate                pgtype.Timestamptz
	TopRandomID                int64
	TopFileID                  *int64
	TopReplyToMsgID            *int32
	TopActionType              int16
}

// PeerChannelDialogsForOwner is the channel counterpart of
// PeerDialogsForOwner. A channel has no dialogs row; its current, unbanned
// membership selects the dialog, and the newest live post is optional. The
// membership predicate and top-post lookup are in this one statement so the
// selected post can never come from a channel the viewer is not entitled to
// read in the same snapshot.
func (q *Queries) PeerChannelDialogsForOwner(ctx context.Context, arg PeerChannelDialogsForOwnerParams) ([]PeerChannelDialogsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, peerChannelDialogsForOwner, arg.ChannelIds, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeerChannelDialogsForOwnerRow
	for rows.Next() {
		var i PeerChannelDialogsForOwnerRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelTitle,
			&i.ChannelAbout,
			&i.ChannelCreatorID,
			&i.ChannelMegagroup,
			&i.ChannelVersion,
			&i.ChannelDate,
			&i.ChannelPinnedMessageID,
			&i.ChannelUsername,
			&i.ChannelDefaultBannedRights,
			&i.MemberRole,
			&i.MemberBannedUntil,
			&i.MemberJoinPts,
			&i.ReadInboxMaxID,
			&i.UnreadCount,
			&i.SummaryEntitled,
			&i.SummaryStatusExists,
			&i.SummaryVersion,
			&i.SummaryReady,
			&i.SummaryTotalLive,
			&i.SummaryAuthorLive,
			&i.ChannelPts,
			&i.TopLocalID,
			&i.TopFromID,
			&i.TopDate,
			&i.TopMessage,
			&i.TopEditDate,
			&i.TopRandomID,
			&i.TopFileID,
			&i.TopReplyToMsgID,
			&i.TopActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const peerDialogsForOwner = `-- name: PeerDialogsForOwner :many
SELECT owner_id, peer_id, top_message, unread_count, read_inbox_max_id, read_outbox_max_id, peer_type FROM dialogs
WHERE owner_id = $1::bigint
  AND (
    (peer_type = 1 AND peer_id = ANY($2::bigint[]))
    OR (peer_type = 2 AND peer_id = ANY($3::bigint[]))
  )
`

type PeerDialogsForOwnerParams struct {
	OwnerID int64
	UserIds []int64
	ChatIds []int64
}

// PeerDialogsForOwner selects only owner-scoped basic dialogs named by the
// caller. The peer-type predicates stay separate so a user id and a chat id
// with the same numeric value cannot cross-match.
func (q *Queries) PeerDialogsForOwner(ctx context.Context, arg PeerDialogsForOwnerParams) ([]Dialog, error) {
	rows, err := q.db.Query(ctx, peerDialogsForOwner, arg.OwnerID, arg.UserIds, arg.ChatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dialog
	for rows.Next() {
		var i Dialog
		if err := rows.Scan(
			&i.OwnerID,
			&i.PeerID,
			&i.TopMessage,
			&i.UnreadCount,
			&i.ReadInboxMaxID,
			&i.ReadOutboxMaxID,
			&i.PeerType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unreadCountForOwner = `-- name: UnreadCountForOwner :one
WITH channel_unread AS MATERIALIZED (
    SELECT summary.entitled::boolean AS entitled,
           summary.status_exists::boolean AS status_exists,
           summary.summary_version::smallint AS summary_version,
           summary.summary_ready::boolean AS summary_ready,
           summary.total_live::bigint AS total_live,
           summary.author_live::bigint AS author_live,
           LEAST(GREATEST(summary.total_live - summary.author_live, 0), 1000)::bigint AS unread_count
    FROM channel_participants AS participant
    LEFT JOIN channel_read_state AS read_state
      ON read_state.channel_id = participant.channel_id
     AND read_state.user_id = participant.user_id
    CROSS JOIN LATERAL channel_post_unread_suffix_counts(
        participant.channel_id,
        participant.user_id,
        COALESCE(read_state.read_max_id, 0)
    ) AS summary(entitled, status_exists, summary_version, summary_ready, total_live, author_live)
    WHERE participant.user_id = $1::bigint
      AND (participant.banned_until IS NULL OR participant.banned_until <= now())
)
SELECT ((
           SELECT COALESCE(SUM(dialog.unread_count), 0)
           FROM dialogs AS dialog
           WHERE dialog.owner_id = $1::bigint
       ) + COALESCE((SELECT SUM(channel_unread.unread_count) FROM channel_unread), 0)::bigint)::bigint AS unread_count,
       (SELECT COUNT(*)::bigint
        FROM channel_unread
        WHERE NOT channel_unread.entitled
           OR NOT channel_unread.status_exists
           OR channel_unread.summary_version <> 1
           OR NOT channel_unread.summary_ready) AS unavailable_channel_count,
       (SELECT COUNT(*)::bigint
        FROM channel_unread
        WHERE channel_unread.total_live < channel_unread.author_live) AS corrupt_channel_count
`

type UnreadCountForOwnerRow struct {
	UnreadCount             int64
	UnavailableChannelCount int64
	CorruptChannelCount     int64
}

func (q *Queries) UnreadCountForOwner(ctx context.Context, ownerID int64) (UnreadCountForOwnerRow, error) {
	row := q.db.QueryRow(ctx, unreadCountForOwner, ownerID)
	var i UnreadCountForOwnerRow
	err := row.Scan(&i.UnreadCount, &i.UnavailableChannelCount, &i.CorruptChannelCount)
	return i, err
}
