// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: polls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closePoll = `-- name: ClosePoll :execrows
UPDATE polls SET closed = true
WHERE id = $1 AND closed = false
`

func (q *Queries) ClosePoll(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, closePoll, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePollVote = `-- name: DeletePollVote :exec
DELETE FROM poll_votes WHERE poll_id = $1 AND voter_id = $2
`

type DeletePollVoteParams struct {
	PollID  int64
	VoterID int64
}

func (q *Queries) DeletePollVote(ctx context.Context, arg DeletePollVoteParams) error {
	_, err := q.db.Exec(ctx, deletePollVote, arg.PollID, arg.VoterID)
	return err
}

const deletePollVoteOptionsByVoter = `-- name: DeletePollVoteOptionsByVoter :exec
DELETE FROM poll_vote_options WHERE poll_id = $1 AND voter_id = $2
`

type DeletePollVoteOptionsByVoterParams struct {
	PollID  int64
	VoterID int64
}

func (q *Queries) DeletePollVoteOptionsByVoter(ctx context.Context, arg DeletePollVoteOptionsByVoterParams) error {
	_, err := q.db.Exec(ctx, deletePollVoteOptionsByVoter, arg.PollID, arg.VoterID)
	return err
}

const insertPoll = `-- name: InsertPoll :one
INSERT INTO polls (
    id, creator_id, random_id, source_local_id, question, public_voters,
    multiple_choice, quiz, shuffle_answers, revoting_disabled, close_date, solution,
    description_entities
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT DO NOTHING
RETURNING id, creator_id, random_id, source_local_id, question, public_voters, multiple_choice, quiz, shuffle_answers, revoting_disabled, closed, close_date, solution, created_at, description_entities
`

type InsertPollParams struct {
	ID                  int64
	CreatorID           int64
	RandomID            int64
	SourceLocalID       int64
	Question            []byte
	PublicVoters        bool
	MultipleChoice      bool
	Quiz                bool
	ShuffleAnswers      bool
	RevotingDisabled    bool
	CloseDate           pgtype.Timestamptz
	Solution            []byte
	DescriptionEntities []byte
}

func (q *Queries) InsertPoll(ctx context.Context, arg InsertPollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, insertPoll,
		arg.ID,
		arg.CreatorID,
		arg.RandomID,
		arg.SourceLocalID,
		arg.Question,
		arg.PublicVoters,
		arg.MultipleChoice,
		arg.Quiz,
		arg.ShuffleAnswers,
		arg.RevotingDisabled,
		arg.CloseDate,
		arg.Solution,
		arg.DescriptionEntities,
	)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.RandomID,
		&i.SourceLocalID,
		&i.Question,
		&i.PublicVoters,
		&i.MultipleChoice,
		&i.Quiz,
		&i.ShuffleAnswers,
		&i.RevotingDisabled,
		&i.Closed,
		&i.CloseDate,
		&i.Solution,
		&i.CreatedAt,
		&i.DescriptionEntities,
	)
	return i, err
}

const insertPollMessageCopy = `-- name: InsertPollMessageCopy :execrows
INSERT INTO poll_message_copies (owner_id, local_id, poll_id)
VALUES ($1, $2, $3)
ON CONFLICT (owner_id, local_id) DO NOTHING
`

type InsertPollMessageCopyParams struct {
	OwnerID int64
	LocalID int64
	PollID  int64
}

func (q *Queries) InsertPollMessageCopy(ctx context.Context, arg InsertPollMessageCopyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPollMessageCopy, arg.OwnerID, arg.LocalID, arg.PollID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPollOption = `-- name: InsertPollOption :exec
INSERT INTO poll_options (poll_id, option, text, correct, position)
VALUES ($1, $2, $3, $4, $5)
`

type InsertPollOptionParams struct {
	PollID   int64
	Option   []byte
	Text     []byte
	Correct  bool
	Position int16
}

func (q *Queries) InsertPollOption(ctx context.Context, arg InsertPollOptionParams) error {
	_, err := q.db.Exec(ctx, insertPollOption,
		arg.PollID,
		arg.Option,
		arg.Text,
		arg.Correct,
		arg.Position,
	)
	return err
}

const insertPollVote = `-- name: InsertPollVote :exec
INSERT INTO poll_votes (poll_id, voter_id) VALUES ($1, $2)
ON CONFLICT (poll_id, voter_id) DO NOTHING
`

type InsertPollVoteParams struct {
	PollID  int64
	VoterID int64
}

func (q *Queries) InsertPollVote(ctx context.Context, arg InsertPollVoteParams) error {
	_, err := q.db.Exec(ctx, insertPollVote, arg.PollID, arg.VoterID)
	return err
}

const insertPollVoteOption = `-- name: InsertPollVoteOption :exec
INSERT INTO poll_vote_options (poll_id, voter_id, option) VALUES ($1, $2, $3)
`

type InsertPollVoteOptionParams struct {
	PollID  int64
	VoterID int64
	Option  []byte
}

func (q *Queries) InsertPollVoteOption(ctx context.Context, arg InsertPollVoteOptionParams) error {
	_, err := q.db.Exec(ctx, insertPollVoteOption, arg.PollID, arg.VoterID, arg.Option)
	return err
}

const pollByCreatorRandomID = `-- name: PollByCreatorRandomID :one
SELECT id, creator_id, random_id, source_local_id, question, public_voters, multiple_choice, quiz, shuffle_answers, revoting_disabled, closed, close_date, solution, created_at, description_entities FROM polls
WHERE creator_id = $1 AND random_id = $2 AND random_id <> 0
`

type PollByCreatorRandomIDParams struct {
	CreatorID int64
	RandomID  int64
}

func (q *Queries) PollByCreatorRandomID(ctx context.Context, arg PollByCreatorRandomIDParams) (Poll, error) {
	row := q.db.QueryRow(ctx, pollByCreatorRandomID, arg.CreatorID, arg.RandomID)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.RandomID,
		&i.SourceLocalID,
		&i.Question,
		&i.PublicVoters,
		&i.MultipleChoice,
		&i.Quiz,
		&i.ShuffleAnswers,
		&i.RevotingDisabled,
		&i.Closed,
		&i.CloseDate,
		&i.Solution,
		&i.CreatedAt,
		&i.DescriptionEntities,
	)
	return i, err
}

const pollByIDForUpdate = `-- name: PollByIDForUpdate :one
SELECT id, creator_id, random_id, source_local_id, question, public_voters, multiple_choice, quiz, shuffle_answers, revoting_disabled, closed, close_date, solution, created_at, description_entities FROM polls WHERE id = $1 FOR UPDATE
`

func (q *Queries) PollByIDForUpdate(ctx context.Context, id int64) (Poll, error) {
	row := q.db.QueryRow(ctx, pollByIDForUpdate, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.RandomID,
		&i.SourceLocalID,
		&i.Question,
		&i.PublicVoters,
		&i.MultipleChoice,
		&i.Quiz,
		&i.ShuffleAnswers,
		&i.RevotingDisabled,
		&i.Closed,
		&i.CloseDate,
		&i.Solution,
		&i.CreatedAt,
		&i.DescriptionEntities,
	)
	return i, err
}

const pollByMessage = `-- name: PollByMessage :one
SELECT p.id, p.creator_id, p.random_id, p.source_local_id, p.question, p.public_voters, p.multiple_choice, p.quiz, p.shuffle_answers, p.revoting_disabled, p.closed, p.close_date, p.solution, p.created_at, p.description_entities
FROM polls p
JOIN poll_message_copies c ON c.poll_id = p.id
JOIN messages m ON m.owner_id = c.owner_id AND m.local_id = c.local_id
WHERE c.owner_id = $1
  AND c.local_id = $2
  AND m.peer_type = $3
  AND m.peer_id = $4
  AND m.deleted = false
`

type PollByMessageParams struct {
	OwnerID  int64
	LocalID  int64
	PeerType int16
	PeerID   int64
}

func (q *Queries) PollByMessage(ctx context.Context, arg PollByMessageParams) (Poll, error) {
	row := q.db.QueryRow(ctx, pollByMessage,
		arg.OwnerID,
		arg.LocalID,
		arg.PeerType,
		arg.PeerID,
	)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.RandomID,
		&i.SourceLocalID,
		&i.Question,
		&i.PublicVoters,
		&i.MultipleChoice,
		&i.Quiz,
		&i.ShuffleAnswers,
		&i.RevotingDisabled,
		&i.Closed,
		&i.CloseDate,
		&i.Solution,
		&i.CreatedAt,
		&i.DescriptionEntities,
	)
	return i, err
}

const pollIDsForMessageCopies = `-- name: PollIDsForMessageCopies :many
SELECT DISTINCT c.poll_id
FROM unnest($1::bigint[]) WITH ORDINALITY AS owners(owner_id, ord)
JOIN unnest($2::bigint[]) WITH ORDINALITY AS locals(local_id, ord) USING (ord)
JOIN poll_message_copies c
  ON c.owner_id = owners.owner_id AND c.local_id = locals.local_id
ORDER BY c.poll_id
`

type PollIDsForMessageCopiesParams struct {
	OwnerIds []int64
	LocalIds []int64
}

// PollIDsForMessageCopies finds every canonical poll row a message batch will
// touch. The caller locks the returned IDs in order before changing any message
// rows, so per-copy cleanup triggers already hold the same locks when they run.
func (q *Queries) PollIDsForMessageCopies(ctx context.Context, arg PollIDsForMessageCopiesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, pollIDsForMessageCopies, arg.OwnerIds, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var poll_id int64
		if err := rows.Scan(&poll_id); err != nil {
			return nil, err
		}
		items = append(items, poll_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollIsClosed = `-- name: PollIsClosed :one
SELECT COALESCE(closed OR (close_date IS NOT NULL AND close_date <= clock_timestamp()), false)::boolean AS is_closed
FROM polls
WHERE id = $1
`

// Poll close_date is evaluated by Postgres while the caller holds the poll row
// lock, so replicas with different wall clocks agree on vote admission.
func (q *Queries) PollIsClosed(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, pollIsClosed, id)
	var is_closed bool
	err := row.Scan(&is_closed)
	return is_closed, err
}

const pollMessageCopiesByOwnerLocalIDs = `-- name: PollMessageCopiesByOwnerLocalIDs :many
SELECT local_id
FROM poll_message_copies
WHERE owner_id = $1
  AND local_id = ANY($2::bigint[])
ORDER BY local_id
`

type PollMessageCopiesByOwnerLocalIDsParams struct {
	OwnerID  int64
	LocalIds []int64
}

func (q *Queries) PollMessageCopiesByOwnerLocalIDs(ctx context.Context, arg PollMessageCopiesByOwnerLocalIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, pollMessageCopiesByOwnerLocalIDs, arg.OwnerID, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var local_id int64
		if err := rows.Scan(&local_id); err != nil {
			return nil, err
		}
		items = append(items, local_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollMessageForOwner = `-- name: PollMessageForOwner :one
SELECT m.peer_type, m.peer_id, m.local_id
FROM poll_message_copies c
JOIN messages m ON m.owner_id = c.owner_id AND m.local_id = c.local_id
WHERE c.owner_id = $1 AND c.poll_id = $2 AND m.deleted = false
`

type PollMessageForOwnerParams struct {
	OwnerID int64
	PollID  int64
}

type PollMessageForOwnerRow struct {
	PeerType int16
	PeerID   int64
	LocalID  int64
}

func (q *Queries) PollMessageForOwner(ctx context.Context, arg PollMessageForOwnerParams) (PollMessageForOwnerRow, error) {
	row := q.db.QueryRow(ctx, pollMessageForOwner, arg.OwnerID, arg.PollID)
	var i PollMessageForOwnerRow
	err := row.Scan(&i.PeerType, &i.PeerID, &i.LocalID)
	return i, err
}

const pollOptionExists = `-- name: PollOptionExists :one
SELECT EXISTS(SELECT 1 FROM poll_options WHERE poll_id = $1 AND option = $2)
`

type PollOptionExistsParams struct {
	PollID int64
	Option []byte
}

func (q *Queries) PollOptionExists(ctx context.Context, arg PollOptionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, pollOptionExists, arg.PollID, arg.Option)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pollOptionResults = `-- name: PollOptionResults :many
SELECT o.option, o.text, o.correct, o.position,
       count(v.voter_id)::bigint AS voter_count,
       EXISTS (
           SELECT 1 FROM poll_vote_options selected
           WHERE selected.poll_id = o.poll_id
             AND selected.option = o.option
             AND selected.voter_id = $1::bigint
       ) AS chosen
FROM poll_options o
LEFT JOIN poll_vote_options v
  ON v.poll_id = o.poll_id AND v.option = o.option
WHERE o.poll_id = $2
GROUP BY o.poll_id, o.option, o.text, o.correct, o.position
ORDER BY o.position
`

type PollOptionResultsParams struct {
	ViewerID int64
	PollID   int64
}

type PollOptionResultsRow struct {
	Option     []byte
	Text       []byte
	Correct    bool
	Position   int16
	VoterCount int64
	Chosen     bool
}

func (q *Queries) PollOptionResults(ctx context.Context, arg PollOptionResultsParams) ([]PollOptionResultsRow, error) {
	rows, err := q.db.Query(ctx, pollOptionResults, arg.ViewerID, arg.PollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollOptionResultsRow
	for rows.Next() {
		var i PollOptionResultsRow
		if err := rows.Scan(
			&i.Option,
			&i.Text,
			&i.Correct,
			&i.Position,
			&i.VoterCount,
			&i.Chosen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollVoteByVoter = `-- name: PollVoteByVoter :one
SELECT poll_id, voter_id, first_voted_at
FROM poll_votes
WHERE poll_id = $1 AND voter_id = $2
`

type PollVoteByVoterParams struct {
	PollID  int64
	VoterID int64
}

func (q *Queries) PollVoteByVoter(ctx context.Context, arg PollVoteByVoterParams) (PollVote, error) {
	row := q.db.QueryRow(ctx, pollVoteByVoter, arg.PollID, arg.VoterID)
	var i PollVote
	err := row.Scan(&i.PollID, &i.VoterID, &i.FirstVotedAt)
	return i, err
}

const pollVoteOptionsByVoter = `-- name: PollVoteOptionsByVoter :many
SELECT option FROM poll_vote_options
WHERE poll_id = $1 AND voter_id = $2
ORDER BY option
`

type PollVoteOptionsByVoterParams struct {
	PollID  int64
	VoterID int64
}

func (q *Queries) PollVoteOptionsByVoter(ctx context.Context, arg PollVoteOptionsByVoterParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, pollVoteOptionsByVoter, arg.PollID, arg.VoterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var option []byte
		if err := rows.Scan(&option); err != nil {
			return nil, err
		}
		items = append(items, option)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollVoterCount = `-- name: PollVoterCount :one
SELECT count(*)::bigint FROM poll_votes WHERE poll_id = $1
`

func (q *Queries) PollVoterCount(ctx context.Context, pollID int64) (int64, error) {
	row := q.db.QueryRow(ctx, pollVoterCount, pollID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pollVoterCountForOption = `-- name: PollVoterCountForOption :one
SELECT count(*)::bigint
FROM poll_votes v
WHERE v.poll_id = $1
  AND (octet_length($2::bytea) = 0 OR EXISTS (
      SELECT 1 FROM poll_vote_options selected
      WHERE selected.poll_id = v.poll_id
        AND selected.voter_id = v.voter_id
        AND selected.option = $2::bytea
  ))
`

type PollVoterCountForOptionParams struct {
	PollID int64
	Option []byte
}

func (q *Queries) PollVoterCountForOption(ctx context.Context, arg PollVoterCountForOptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, pollVoterCountForOption, arg.PollID, arg.Option)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pollVotersPage = `-- name: PollVotersPage :many
SELECT v.voter_id, v.first_voted_at,
       COALESCE(string_agg(encode(selected.option, 'base64'), '.' ORDER BY selected.option)
           FILTER (WHERE selected.option IS NOT NULL), '') AS options
FROM poll_votes v
LEFT JOIN poll_vote_options selected
  ON selected.poll_id = v.poll_id AND selected.voter_id = v.voter_id
WHERE v.poll_id = $1
  AND (octet_length($2::bytea) = 0 OR EXISTS (
      SELECT 1 FROM poll_vote_options filtered
      WHERE filtered.poll_id = v.poll_id
        AND filtered.voter_id = v.voter_id
        AND filtered.option = $2::bytea
  ))
  AND (NOT $3::boolean OR
       (v.first_voted_at, v.voter_id) <
       ($4::timestamptz, $5::bigint))
GROUP BY v.voter_id, v.first_voted_at
ORDER BY v.first_voted_at DESC, v.voter_id DESC
LIMIT $6::int
`

type PollVotersPageParams struct {
	PollID       int64
	Option       []byte
	HasCursor    bool
	CursorAt     pgtype.Timestamptz
	CursorUserID int64
	Lim          int32
}

type PollVotersPageRow struct {
	VoterID      int64
	FirstVotedAt pgtype.Timestamptz
	Options      interface{}
}

// PollVotersPage returns one row per voter. The composite first-vote timestamp
// and voter id cursor is stable even when multiple votes share one timestamp.
func (q *Queries) PollVotersPage(ctx context.Context, arg PollVotersPageParams) ([]PollVotersPageRow, error) {
	rows, err := q.db.Query(ctx, pollVotersPage,
		arg.PollID,
		arg.Option,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorUserID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollVotersPageRow
	for rows.Next() {
		var i PollVotersPageRow
		if err := rows.Scan(&i.VoterID, &i.FirstVotedAt, &i.Options); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
