// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reactions.sql

package db

import (
	"context"
)

const deleteReaction = `-- name: DeleteReaction :exec
DELETE FROM message_reactions
WHERE owner_id = $1 AND local_id = $2 AND reactor_id = $3
`

type DeleteReactionParams struct {
	OwnerID   int64
	LocalID   int64
	ReactorID int64
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) error {
	_, err := q.db.Exec(ctx, deleteReaction, arg.OwnerID, arg.LocalID, arg.ReactorID)
	return err
}

const messagesByOwnerLocalIDs = `-- name: MessagesByOwnerLocalIDs :many
SELECT owner_id, local_id, peer_id, from_id, date, message, out, edit_date, deleted, random_id, peer_local_id, peer_type, fanout_id, action_type, action_user_id, file_id, reply_to_msg_id, fwd_from_id, fwd_date, fwd_channel_id, fwd_channel_post, message_tsv, reply_to_trusted FROM messages
WHERE owner_id = $1
  AND local_id = ANY($2::bigint[])
`

type MessagesByOwnerLocalIDsParams struct {
	OwnerID  int64
	LocalIds []int64
}

func (q *Queries) MessagesByOwnerLocalIDs(ctx context.Context, arg MessagesByOwnerLocalIDsParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, messagesByOwnerLocalIDs, arg.OwnerID, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.PeerID,
			&i.FromID,
			&i.Date,
			&i.Message,
			&i.Out,
			&i.EditDate,
			&i.Deleted,
			&i.RandomID,
			&i.PeerLocalID,
			&i.PeerType,
			&i.FanoutID,
			&i.ActionType,
			&i.ActionUserID,
			&i.FileID,
			&i.ReplyToMsgID,
			&i.FwdFromID,
			&i.FwdDate,
			&i.FwdChannelID,
			&i.FwdChannelPost,
			&i.MessageTsv,
			&i.ReplyToTrusted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactionsByMessage = `-- name: ReactionsByMessage :many
SELECT owner_id, local_id, reactor_id, reaction, created_at FROM message_reactions
WHERE owner_id = $1 AND local_id = $2
ORDER BY reactor_id
`

type ReactionsByMessageParams struct {
	OwnerID int64
	LocalID int64
}

func (q *Queries) ReactionsByMessage(ctx context.Context, arg ReactionsByMessageParams) ([]MessageReaction, error) {
	rows, err := q.db.Query(ctx, reactionsByMessage, arg.OwnerID, arg.LocalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageReaction
	for rows.Next() {
		var i MessageReaction
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.ReactorID,
			&i.Reaction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactionsByMessages = `-- name: ReactionsByMessages :many
SELECT owner_id, local_id, reactor_id, reaction, created_at FROM message_reactions
WHERE owner_id = $1
  AND local_id = ANY($2::bigint[])
ORDER BY local_id, reactor_id
`

type ReactionsByMessagesParams struct {
	OwnerID  int64
	LocalIds []int64
}

func (q *Queries) ReactionsByMessages(ctx context.Context, arg ReactionsByMessagesParams) ([]MessageReaction, error) {
	rows, err := q.db.Query(ctx, reactionsByMessages, arg.OwnerID, arg.LocalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageReaction
	for rows.Next() {
		var i MessageReaction
		if err := rows.Scan(
			&i.OwnerID,
			&i.LocalID,
			&i.ReactorID,
			&i.Reaction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReaction = `-- name: UpsertReaction :exec
INSERT INTO message_reactions (owner_id, local_id, reactor_id, reaction)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_id, local_id, reactor_id)
DO UPDATE SET reaction = $4
`

type UpsertReactionParams struct {
	OwnerID   int64
	LocalID   int64
	ReactorID int64
	Reaction  string
}

func (q *Queries) UpsertReaction(ctx context.Context, arg UpsertReactionParams) error {
	_, err := q.db.Exec(ctx, upsertReaction,
		arg.OwnerID,
		arg.LocalID,
		arg.ReactorID,
		arg.Reaction,
	)
	return err
}
