// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_administration.sql

package db

import (
	"context"
)

const closeServerAdministratorElection = `-- name: CloseServerAdministratorElection :one
UPDATE server_administration
SET election_closed = TRUE
WHERE singleton_id = 1
  AND election_closed = FALSE
  AND administrator_user_id IS NULL
RETURNING singleton_id, election_closed, administrator_user_id
`

// A locally provisioned ordinary account must close an open election without
// assigning administrator authority to itself.
func (q *Queries) CloseServerAdministratorElection(ctx context.Context) (ServerAdministration, error) {
	row := q.db.QueryRow(ctx, closeServerAdministratorElection)
	var i ServerAdministration
	err := row.Scan(&i.SingletonID, &i.ElectionClosed, &i.AdministratorUserID)
	return i, err
}

const electServerAdministrator = `-- name: ElectServerAdministrator :one
UPDATE server_administration
SET election_closed = TRUE,
    administrator_user_id = $1
WHERE singleton_id = 1
  AND election_closed = FALSE
  AND administrator_user_id IS NULL
RETURNING singleton_id, election_closed, administrator_user_id
`

// The conditional update is the durable concurrency arbiter for the first
// user. It must never be replaced by an application-side count or mutex.
func (q *Queries) ElectServerAdministrator(ctx context.Context, userID *int64) (ServerAdministration, error) {
	row := q.db.QueryRow(ctx, electServerAdministrator, userID)
	var i ServerAdministration
	err := row.Scan(&i.SingletonID, &i.ElectionClosed, &i.AdministratorUserID)
	return i, err
}

const isServerAdministrator = `-- name: IsServerAdministrator :one
SELECT CASE WHEN
    count(*) = 1
    AND bool_and(singleton_id = 1)
    AND bool_and(election_closed)
    AND bool_or(administrator_user_id = $1)
    THEN TRUE ELSE FALSE END
FROM server_administration
`

func (q *Queries) IsServerAdministrator(ctx context.Context, userID *int64) (bool, error) {
	row := q.db.QueryRow(ctx, isServerAdministrator, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const lockServerAdministration = `-- name: LockServerAdministration :many
SELECT singleton_id, election_closed, administrator_user_id
FROM server_administration
ORDER BY singleton_id
FOR UPDATE
`

// Lock every row while validating the singleton before an account commit.
func (q *Queries) LockServerAdministration(ctx context.Context) ([]ServerAdministration, error) {
	rows, err := q.db.Query(ctx, lockServerAdministration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerAdministration
	for rows.Next() {
		var i ServerAdministration
		if err := rows.Scan(&i.SingletonID, &i.ElectionClosed, &i.AdministratorUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
