// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_limit_leases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveServerLimitLeases = `-- name: CountActiveServerLimitLeases :one
SELECT count(*)::bigint AS active_count
FROM server_limit_leases
WHERE subject_id = $1 AND surface = $2 AND expires_at > clock_timestamp()
`

type CountActiveServerLimitLeasesParams struct {
	SubjectID int64
	Surface   string
}

func (q *Queries) CountActiveServerLimitLeases(ctx context.Context, arg CountActiveServerLimitLeasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveServerLimitLeases, arg.SubjectID, arg.Surface)
	var active_count int64
	err := row.Scan(&active_count)
	return active_count, err
}

const deleteExpiredServerLimitLeasesForSubject = `-- name: DeleteExpiredServerLimitLeasesForSubject :exec
DELETE FROM server_limit_leases
WHERE subject_id = $1 AND surface = $2 AND expires_at <= clock_timestamp()
`

type DeleteExpiredServerLimitLeasesForSubjectParams struct {
	SubjectID int64
	Surface   string
}

func (q *Queries) DeleteExpiredServerLimitLeasesForSubject(ctx context.Context, arg DeleteExpiredServerLimitLeasesForSubjectParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredServerLimitLeasesForSubject, arg.SubjectID, arg.Surface)
	return err
}

const deleteServerLimitLease = `-- name: DeleteServerLimitLease :execrows
DELETE FROM server_limit_leases
WHERE lease_id = $1 AND subject_id = $2 AND surface = $3
`

type DeleteServerLimitLeaseParams struct {
	LeaseID   []byte
	SubjectID int64
	Surface   string
}

func (q *Queries) DeleteServerLimitLease(ctx context.Context, arg DeleteServerLimitLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServerLimitLease, arg.LeaseID, arg.SubjectID, arg.Surface)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEarliestServerLimitLeaseExpiry = `-- name: GetEarliestServerLimitLeaseExpiry :one
SELECT expires_at
FROM server_limit_leases
WHERE subject_id = $1 AND surface = $2 AND expires_at > clock_timestamp()
ORDER BY expires_at
LIMIT 1
`

type GetEarliestServerLimitLeaseExpiryParams struct {
	SubjectID int64
	Surface   string
}

func (q *Queries) GetEarliestServerLimitLeaseExpiry(ctx context.Context, arg GetEarliestServerLimitLeaseExpiryParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getEarliestServerLimitLeaseExpiry, arg.SubjectID, arg.Surface)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const insertServerLimitLease = `-- name: InsertServerLimitLease :execrows
INSERT INTO server_limit_leases (lease_id, subject_id, surface, expires_at)
VALUES ($1, $2, $3, clock_timestamp() + $4::interval)
ON CONFLICT (lease_id) DO NOTHING
`

type InsertServerLimitLeaseParams struct {
	LeaseID   []byte
	SubjectID int64
	Surface   string
	Column4   pgtype.Interval
}

func (q *Queries) InsertServerLimitLease(ctx context.Context, arg InsertServerLimitLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertServerLimitLease,
		arg.LeaseID,
		arg.SubjectID,
		arg.Surface,
		arg.Column4,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewServerLimitLease = `-- name: RenewServerLimitLease :execrows
UPDATE server_limit_leases
SET expires_at = clock_timestamp() + $4::interval
WHERE lease_id = $1
  AND subject_id = $2
  AND surface = $3
  AND expires_at > clock_timestamp()
`

type RenewServerLimitLeaseParams struct {
	LeaseID   []byte
	SubjectID int64
	Surface   string
	Column4   pgtype.Interval
}

func (q *Queries) RenewServerLimitLease(ctx context.Context, arg RenewServerLimitLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewServerLimitLease,
		arg.LeaseID,
		arg.SubjectID,
		arg.Surface,
		arg.Column4,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepExpiredServerLimitLeases = `-- name: SweepExpiredServerLimitLeases :execrows
DELETE FROM server_limit_leases
WHERE expires_at <= clock_timestamp()
`

func (q *Queries) SweepExpiredServerLimitLeases(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredServerLimitLeases)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
