// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: srp_challenges.sql

package db

import (
	"context"
)

const consumeSRPChallenge = `-- name: ConsumeSRPChallenge :one
DELETE FROM srp_challenges
WHERE srp_id = $1
  AND auth_key_id = $2
  AND expires_at > now()
RETURNING user_id, b_secret, b_public
`

type ConsumeSRPChallengeParams struct {
	SrpID     int64
	AuthKeyID int64
}

type ConsumeSRPChallengeRow struct {
	UserID  int64
	BSecret []byte
	BPublic []byte
}

func (q *Queries) ConsumeSRPChallenge(ctx context.Context, arg ConsumeSRPChallengeParams) (ConsumeSRPChallengeRow, error) {
	row := q.db.QueryRow(ctx, consumeSRPChallenge, arg.SrpID, arg.AuthKeyID)
	var i ConsumeSRPChallengeRow
	err := row.Scan(&i.UserID, &i.BSecret, &i.BPublic)
	return i, err
}

const sweepExpiredSRPChallenges = `-- name: SweepExpiredSRPChallenges :execrows
DELETE FROM srp_challenges
WHERE srp_id IN (
    SELECT srp_id
    FROM srp_challenges
    WHERE expires_at <= now()
    ORDER BY expires_at, srp_id
    LIMIT $1::int
    FOR UPDATE SKIP LOCKED
)
`

func (q *Queries) SweepExpiredSRPChallenges(ctx context.Context, lim int32) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredSRPChallenges, lim)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSRPChallenge = `-- name: UpsertSRPChallenge :exec
INSERT INTO srp_challenges (srp_id, auth_key_id, user_id, b_secret, b_public, expires_at)
VALUES ($1, $2, $3, $4, $5,
        now() + ($6::bigint * interval '1 microsecond'))
ON CONFLICT (auth_key_id, user_id) DO UPDATE
SET srp_id = EXCLUDED.srp_id,
    b_secret = EXCLUDED.b_secret,
    b_public = EXCLUDED.b_public,
    expires_at = EXCLUDED.expires_at
`

type UpsertSRPChallengeParams struct {
	SrpID     int64
	AuthKeyID int64
	UserID    int64
	BSecret   []byte
	BPublic   []byte
	TtlUs     int64
}

func (q *Queries) UpsertSRPChallenge(ctx context.Context, arg UpsertSRPChallengeParams) error {
	_, err := q.db.Exec(ctx, upsertSRPChallenge,
		arg.SrpID,
		arg.AuthKeyID,
		arg.UserID,
		arg.BSecret,
		arg.BPublic,
		arg.TtlUs,
	)
	return err
}
