// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updatestate.sql

package db

import (
	"context"
)

const bumpPtsOnly = `-- name: BumpPtsOnly :one
UPDATE update_state SET pts = pts + 1, date = now()
WHERE user_id = $1 AND pts < 2147483647
RETURNING pts
`

// BumpPtsOnly advances pts without consuming a local_id (edit/delete/read).
func (q *Queries) BumpPtsOnly(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, bumpPtsOnly, userID)
	var pts int64
	err := row.Scan(&pts)
	return pts, err
}

const bumpState = `-- name: BumpState :one
UPDATE update_state
SET pts = pts + 1, next_local_id = next_local_id + 1, date = now()
WHERE user_id = $1 AND pts < 2147483647 AND next_local_id <= 2147483647
RETURNING pts, (next_local_id - 1)::bigint AS local_id
`

type BumpStateRow struct {
	Pts     int64
	LocalID int64
}

// BumpState allocates the next local_id and advances pts in one step. It returns
// the new pts and the local_id just consumed (pre-increment value).
// next_local_id is the next value to issue, so the last legal ID may advance the
// cursor to 2147483648. Refuse only when the ID or resulting pts would exceed
// Telegram's signed int32 wire range.
func (q *Queries) BumpState(ctx context.Context, userID int64) (BumpStateRow, error) {
	row := q.db.QueryRow(ctx, bumpState, userID)
	var i BumpStateRow
	err := row.Scan(&i.Pts, &i.LocalID)
	return i, err
}

const ensureUpdateState = `-- name: EnsureUpdateState :exec
INSERT INTO update_state (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureUpdateState(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, ensureUpdateState, userID)
	return err
}

const eventsSince = `-- name: EventsSince :many
SELECT owner_id, pts, type, local_id FROM message_events
WHERE owner_id = $1 AND pts > $2
ORDER BY pts
`

type EventsSinceParams struct {
	OwnerID int64
	Pts     int64
}

func (q *Queries) EventsSince(ctx context.Context, arg EventsSinceParams) ([]MessageEvent, error) {
	rows, err := q.db.Query(ctx, eventsSince, arg.OwnerID, arg.Pts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageEvent
	for rows.Next() {
		var i MessageEvent
		if err := rows.Scan(
			&i.OwnerID,
			&i.Pts,
			&i.Type,
			&i.LocalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsWindow = `-- name: EventsWindow :many
SELECT owner_id, pts, type, local_id FROM message_events
WHERE owner_id = $1 AND pts > $2 AND pts <= $3
ORDER BY pts
LIMIT $4::int
`

type EventsWindowParams struct {
	OwnerID int64
	FromPts int64
	ToPts   int64
	Lim     int32
}

// EventsWindow returns events in (from_pts, to_pts] ordered, capped by lim. The
// upper bound pins the read to a pts snapshot so the difference never advertises
// a pts past an event it omitted.
func (q *Queries) EventsWindow(ctx context.Context, arg EventsWindowParams) ([]MessageEvent, error) {
	rows, err := q.db.Query(ctx, eventsWindow,
		arg.OwnerID,
		arg.FromPts,
		arg.ToPts,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageEvent
	for rows.Next() {
		var i MessageEvent
		if err := rows.Scan(
			&i.OwnerID,
			&i.Pts,
			&i.Type,
			&i.LocalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getState = `-- name: GetState :one
SELECT user_id, pts, seq, date, next_local_id, qts FROM update_state WHERE user_id = $1
`

func (q *Queries) GetState(ctx context.Context, userID int64) (UpdateState, error) {
	row := q.db.QueryRow(ctx, getState, userID)
	var i UpdateState
	err := row.Scan(
		&i.UserID,
		&i.Pts,
		&i.Seq,
		&i.Date,
		&i.NextLocalID,
		&i.Qts,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO message_events (owner_id, pts, type, local_id) VALUES ($1, $2, $3, $4)
`

type InsertEventParams struct {
	OwnerID int64
	Pts     int64
	Type    int16
	LocalID int64
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.OwnerID,
		arg.Pts,
		arg.Type,
		arg.LocalID,
	)
	return err
}

const newMessagePts = `-- name: NewMessagePts :one
SELECT pts FROM message_events
WHERE owner_id = $1 AND local_id = $2 AND type = 1
`

type NewMessagePtsParams struct {
	OwnerID int64
	LocalID int64
}

// NewMessagePts returns the pts at which owner's local_id entered the log, for
// a resend that has to name the pts its stored message already occupies rather
// than the owner's current one. Exactly one row can match: a message is written
// with its new-message event in one transaction and neither is ever rewritten.
//
// type = 1 (new message) is a literal, not a parameter, because the partial
// index serving this read is predicated on it and a parameter cannot be proven
// against that predicate.
func (q *Queries) NewMessagePts(ctx context.Context, arg NewMessagePtsParams) (int64, error) {
	row := q.db.QueryRow(ctx, newMessagePts, arg.OwnerID, arg.LocalID)
	var pts int64
	err := row.Scan(&pts)
	return pts, err
}
