// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usernames.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimUsername = `-- name: ClaimUsername :one
INSERT INTO usernames (handle, owner_type, owner_id)
VALUES (lower($1), $2, $3)
RETURNING handle, owner_type, owner_id
`

type ClaimUsernameParams struct {
	Handle    string
	OwnerType string
	OwnerID   int64
}

func (q *Queries) ClaimUsername(ctx context.Context, arg ClaimUsernameParams) (Username, error) {
	row := q.db.QueryRow(ctx, claimUsername, arg.Handle, arg.OwnerType, arg.OwnerID)
	var i Username
	err := row.Scan(&i.Handle, &i.OwnerType, &i.OwnerID)
	return i, err
}

const getChannelByUsername = `-- name: GetChannelByUsername :one
SELECT c.id, c.title, c.about, c.creator_id, c.megagroup, c.version, c.date, c.pinned_message_id, c.username, c.title_tsv, c.publicly_discoverable, c.default_banned_rights, c.slowmode_seconds FROM channels c
JOIN usernames un ON un.owner_type = 'channel' AND un.owner_id = c.id
WHERE un.handle = lower($1)
`

func (q *Queries) GetChannelByUsername(ctx context.Context, handle string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByUsername, handle)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.About,
		&i.CreatorID,
		&i.Megagroup,
		&i.Version,
		&i.Date,
		&i.PinnedMessageID,
		&i.Username,
		&i.TitleTsv,
		&i.PubliclyDiscoverable,
		&i.DefaultBannedRights,
		&i.SlowmodeSeconds,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT u.id, u.phone, u.first_name, u.last_name, u.created_at, u.is_online, u.last_seen_at,
       un.handle AS username
FROM users u
JOIN usernames un ON un.owner_type = 'user' AND un.owner_id = u.id
WHERE un.handle = lower($1)
`

type GetUserByUsernameRow struct {
	ID         int64
	Phone      *string
	FirstName  string
	LastName   string
	CreatedAt  pgtype.Timestamptz
	IsOnline   bool
	LastSeenAt pgtype.Timestamptz
	Username   string
}

// The handle reported back is the joined usernames row — the one that admitted
// the account to this result — not the denormalized users.username copy.
func (q *Queries) GetUserByUsername(ctx context.Context, handle string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, handle)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.Username,
	)
	return i, err
}

const getUserByUsernameWithLoginMode = `-- name: GetUserByUsernameWithLoginMode :one
SELECT u.id, u.phone, u.first_name, u.last_name, u.created_at, u.is_online, u.last_seen_at,
       u.login_mode, un.handle AS username
FROM users u
JOIN usernames un ON un.owner_type = 'user' AND un.owner_id = u.id
WHERE un.handle = lower($1)
`

type GetUserByUsernameWithLoginModeRow struct {
	ID         int64
	Phone      *string
	FirstName  string
	LastName   string
	CreatedAt  pgtype.Timestamptz
	IsOnline   bool
	LastSeenAt pgtype.Timestamptz
	LoginMode  string
	Username   string
}

// Resolves a normalized username to the owning user, including login_mode.
// Only matches owner_type='user' — a channel with the same handle returns no row.
// Returns login_mode so the signIn handler can decide 2FA vs sign-up vs error.
func (q *Queries) GetUserByUsernameWithLoginMode(ctx context.Context, handle string) (GetUserByUsernameWithLoginModeRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameWithLoginMode, handle)
	var i GetUserByUsernameWithLoginModeRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.LoginMode,
		&i.Username,
	)
	return i, err
}

const getUsernameByHandle = `-- name: GetUsernameByHandle :one
SELECT handle, owner_type, owner_id FROM usernames WHERE handle = lower($1)
`

func (q *Queries) GetUsernameByHandle(ctx context.Context, handle string) (Username, error) {
	row := q.db.QueryRow(ctx, getUsernameByHandle, handle)
	var i Username
	err := row.Scan(&i.Handle, &i.OwnerType, &i.OwnerID)
	return i, err
}

const releaseUsername = `-- name: ReleaseUsername :execrows
DELETE FROM usernames
WHERE handle = lower($1)
  AND owner_type = $2
  AND owner_id = $3
`

type ReleaseUsernameParams struct {
	Handle    string
	OwnerType string
	OwnerID   int64
}

func (q *Queries) ReleaseUsername(ctx context.Context, arg ReleaseUsernameParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseUsername, arg.Handle, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseUsernameByOwner = `-- name: ReleaseUsernameByOwner :execrows
DELETE FROM usernames WHERE owner_type = $1 AND owner_id = $2
`

type ReleaseUsernameByOwnerParams struct {
	OwnerType string
	OwnerID   int64
}

func (q *Queries) ReleaseUsernameByOwner(ctx context.Context, arg ReleaseUsernameByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseUsernameByOwner, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
